In [3]:
for i in range(1,5):
    for j in range(1,5):
        for x in range(1,5):
            if i != j and j!= x and i!=x:
                print(i,j,x)
#由1234能组成多少个不同的三位数

1 2 3
1 2 4
1 3 2
1 3 4
1 4 2
1 4 3
2 1 3
2 1 4
2 3 1
2 3 4
2 4 1
2 4 3
3 1 2
3 1 4
3 2 1
3 2 4
3 4 1
3 4 2
4 1 2
4 1 3
4 2 1
4 2 3
4 3 1
4 3 2


In [4]:
for m in range(1,10):
    for n in range(1,10):
        if m>=n:
            print('%s×%s=%s'%(m,n,m*n),end=' ')
    print()

1×1=1 
2×1=2 2×2=4 
3×1=3 3×2=6 3×3=9 
4×1=4 4×2=8 4×3=12 4×4=16 
5×1=5 5×2=10 5×3=15 5×4=20 5×5=25 
6×1=6 6×2=12 6×3=18 6×4=24 6×5=30 6×6=36 
7×1=7 7×2=14 7×3=21 7×4=28 7×5=35 7×6=42 7×7=49 
8×1=8 8×2=16 8×3=24 8×4=32 8×5=40 8×6=48 8×7=56 8×8=64 
9×1=9 9×2=18 9×3=27 9×4=36 9×5=45 9×6=54 9×7=63 9×8=72 9×9=81 


In [5]:
for i in range(1, 10):
    for j in range(1, i + 1):
        print(("%sx%s=%s" % (i, j, i * j)).split(" "), end="")
    print()

['1x1=1']
['2x1=2']['2x2=4']
['3x1=3']['3x2=6']['3x3=9']
['4x1=4']['4x2=8']['4x3=12']['4x4=16']
['5x1=5']['5x2=10']['5x3=15']['5x4=20']['5x5=25']
['6x1=6']['6x2=12']['6x3=18']['6x4=24']['6x5=30']['6x6=36']
['7x1=7']['7x2=14']['7x3=21']['7x4=28']['7x5=35']['7x6=42']['7x7=49']
['8x1=8']['8x2=16']['8x3=24']['8x4=32']['8x5=40']['8x6=48']['8x7=56']['8x8=64']
['9x1=9']['9x2=18']['9x3=27']['9x4=36']['9x5=45']['9x6=54']['9x7=63']['9x8=72']['9x9=81']


In [7]:
def fib(n):
    if n==1 or n==2:
        return 1
    return fib(n-1)+fib(n-2)
fib(3)

2

In [8]:
print(range(3))

range(0, 3)


In [9]:
L = []
for i in range(3):
    x = input("")
    L.append(x)
L.sort()
print(L)

 5
 9
 5


['5', '5', '9']


In [10]:
import time
 
print time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time()))
 
# 暂停一秒
time.sleep(1)
print time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time()))

SyntaxError: invalid syntax (<ipython-input-10-9174e32ecdc0>, line 3)

In [14]:
def check(a, x):
    n = len(a)
    m = n // 2
    if n<1:
        return False
    if a[m] > x:
        return check(a[0:m],x)
    elif a[m] < x:
        return check(a[m+1:],x)
    else:
        return m
a=[1,2,3,4]
check(a,2)

1

In [15]:
def bubble_sort(li):
 
    for j in range(len(li)-1):
        for i in range(1, len(li)):
            if li[i] > li[i-1]:
                li[i], li[i-1] = li[i-1], li[i]
 
    return li
l=[1,2,3,4]
bubble_sort(l)

[4, 3, 2, 1]

In [ ]:
#!/usr/bin/env python3
#coding: utf-8
import numpy
import numpy as np
import random
from random import choice


class Game2048(object):
    '''2048游戏的类'''
    '''
        属性:
            self.dimension
            self.matrix
        方法：
            judge_gameover(self)
            generate_num(self)
            left_2048(self)
            right_2048(self)
            down_2048(self)
            up_2048(self)
            print_(self)
            input_(self)
    '''
    def __init__(self,dimension = 4):
        self.dimension = dimension  #维数，决定要构建几维的矩阵 
        self.matrix = np.zeros((dimension,dimension)) #创建一个全是0的n(n = dimension)维矩阵

    def judge_gameover(self):#判断是否游戏结束，如果游戏结束返回True，未结束则返回False
        '''如果水平方向上任意两个相邻的数字有相等的或者有为0的那么游戏未结束'''
        for a in range(0,self.dimension):
            for b in range(0,self.dimension-1):
                if self.matrix[a][b] == self.matrix[a][b+1] or self.matrix[a][b] == 0 or self.matrix[a][b+1] == 0:
                    return False
        '''如果垂直方向上任意两个相邻的数字有相等的或者有为0的那么游戏未结束'''
        self.matrix = np.transpose(self.matrix)#先转置垂直方向变作水平方向 eg:[[1,2],[3,4]]>>[[1,3],[2,4]]
        for a in range(0,self.dimension):
            for b in range(0,self.dimension-1):
                if self.matrix[a][b] == self.matrix[a][b+1] or self.matrix[a][b] == 0 or self.matrix[a][b+1] == 0:
                    return False
        return True
                    
    def generate_num(self):#在随机的空白(为0)的位置替换为1个随机的2或者4
        '''在随机的空白(为0)的位置替换为1个随机的2或者4'''
        
        #判断矩阵内为零的数的位置,并将索引放入到list_0中
        list_0 = []
        for a in range(0,self.dimension):
            for b in range(0,self.dimension):
                if self.matrix[a,b] == 0 :
                    list_0.append([a,b])
                    
        #判断矩阵内为0的数的个数，如果为0,那么就不再生成新的数字
        if len(list_0) != 0:
            x = random.sample(list_0,1)[0]#注意random.sample()函数返回值类型为列表
            self.matrix[x[0]][x[1]] = random.randrange(2, 5, 2)
    
    def left_2048(self):#向左平移合并
        '''数字向左平移'''
        for i in range(0,self.dimension):
            list_i = list(self.matrix[i])
            while 0 in list_i:
                list_i.remove(0)
            while len(list_i) != self.dimension:
                list_i.append(0)
            self.matrix[i] = list_i
            
        '''水平向左合并'''
        for a in range(0,self.dimension):
            for b in range(0,self.dimension-1):
                if self.matrix[a][b] != 0 and self.matrix[a][b] == self.matrix[a][b+1]:
                    self.matrix[a][b] = 2 * self.matrix[a][b]
                    self.matrix[a][b+1] = 0
                else:
                    pass
                    
        '''数字向左平移'''
        for i in range(0,self.dimension):
            list_i = list(self.matrix[i])
            while 0 in list_i:
                list_i.remove(0)
            while len(list_i) != self.dimension:
                list_i.append(0)
            self.matrix[i] = list_i
            
    def right_2048(self):#向右平移合并
        for i in range(0,self.dimension):#将矩阵水平方向反转 eg：[[1,2],[3,4]]>>[[2,1],[4,3]]
            self.matrix[i] = self.matrix[i][::-1]
        self.left_2048()#注意在类中内置函数互相调用前面要加self.，也注意不要循环调用
        for i in range(0,self.dimension):#再将矩阵水平方向反转回来
            self.matrix[i] = self.matrix[i][::-1]

    def down_2048(self):#向下平移合并
        self.matrix = self.matrix[::-1]#先上下反转 eg:[[1,2],[3,4]]>>[[3,4],[1,2]]
        self.up_2048()
        self.matrix = self.matrix[::-1]#再上下反转回来eg:[[3,4],[1,2]]>>[[1,2],[3,4]]
    
    def up_2048(self):#向上平移合并
        self.matrix = np.transpose(self.matrix)#先转置 eg:[[1,2],[3,4]]>>[[1,3],[2,4]]
        self.left_2048()
        self.matrix = np.transpose(self.matrix)#再转置回来 eg:[[1,3],[2,4]]>>[[1,2],[3,4]]
        
    def print_2048(self):#显示
        for i in self.matrix:
            print(i)
        
    def input_2048(self):#输入
        while True:
            s = input("w(↑) a(←) s(↓) d(右)：")
            if s == "w":
                self.up_2048()
                break
            elif s == "a":
                self.left_2048()
                break
            elif s == "s":
                self.down_2048()
                break
            elif s == "d":
                self.right_2048()
                break
            elif s=='q':
                print('Game Over')
                break
            else:
                print("输入有误请重新输入")
                continue
                

if __name__ == '__main__':#主程序
    g1 = Game2048()
    g1.generate_num()
    g1.generate_num()
    g1.generate_num()
    g1.print_2048()
    while True:
        g1.input_2048()
        g1.generate_num()
        g1.print_2048()
        if g1.judge_gameover() == True:
            print("Game over")
            break

[0. 0. 4. 2.]
[0. 4. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]


w(↑) a(←) s(↓) d(右)： 1


输入有误请重新输入


w(↑) a(←) s(↓) d(右)： 3


输入有误请重新输入


w(↑) a(←) s(↓) d(右)： 2


输入有误请重新输入


w(↑) a(←) s(↓) d(右)： q


Game Over
[0. 0. 4. 2.]
[0. 4. 0. 4.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]


w(↑) a(←) s(↓) d(右)： q


Game Over
[0. 0. 4. 2.]
[0. 4. 0. 4.]
[2. 0. 0. 0.]
[0. 0. 0. 0.]


w(↑) a(←) s(↓) d(右)： q


Game Over
[0. 0. 4. 2.]
[0. 4. 0. 4.]
[2. 0. 0. 0.]
[4. 0. 0. 0.]


w(↑) a(←) s(↓) d(右)： q


Game Over
[0. 0. 4. 2.]
[4. 4. 0. 4.]
[2. 0. 0. 0.]
[4. 0. 0. 0.]


In [4]:
from random import randint
from math import floor

def nim_silly(n):  # 愚钝版本随机取数
    if n <= 3:
        return 1
    return randint(1, floor(n / 2))

def nim_smart(n):  # 聪明版本自动选择最佳数
    if n <= 3:
        return 1
    x = 0
    while (True):
        if pow(2, x) < n <= pow(2, x + 1):
            break
        x += 1

    num = n - pow(2, x) + 1
    if 1 <= num <= n / 2:
        return num
    else:  # 若最佳数不在范围内，则选取随机数
        return randint(1, floor(n / 2))

def nim_game(n, choose):
    if choose == 'silly':
        print("你选择了低难度")
        f = nim_silly    # 函数指针选择silly函数
    else:
        print("你选择了高难度")
        f = nim_smart  # 函数指针选择smart函数

    while (True):
        print("现在共有" + str(n) + "个棋子")
        nim = f(n)
        print("Nim拿走了" + str(nim) + "个")
        n -= nim
        print("现在共有" + str(n) + "个棋子")
        if n == 0:
            print("你赢了！")
            return

        you = int(input("该你了，你要拿走:"))
        while (True):
            if 1 <= you <= n / 2 or n == 1:
                print("你拿走了" + str(you) + "个")
                break
            if you < 1:
                print("至少要拿走一个棋子！")
            else:
                print("最多只能拿走一半的棋子！")
            you = int(input("请重新输入，你要拿走:"))

        n -= you
        if n == 0:
            print("现在共有" + str(n) + "个棋子")
            print("你输了！")
            return

if __name__ == '__main__':
    num = int(input("请输入棋子的总数: "))
    choose = input("请输入你要选择的难度（'silly' or 'smart'）: ")
nim_game(num, choose)

请输入棋子的总数:  10
请输入你要选择的难度（'silly' or 'smart'）:  silly


你选择了低难度
现在共有10个棋子
Nim拿走了2个
现在共有8个棋子


该你了，你要拿走: 7


最多只能拿走一半的棋子！


请重新输入，你要拿走: n


ValueError: invalid literal for int() with base 10: 'n'