In [1]:
import numpy as np
#1、创建一个数值范围为0~1，间隔为0.01的数组
arr1 = np.arange(0,1,0.01)
print('arange函数创建的数值范围为0~1间隔为0.01的数组arr1为：\n',arr1)
#2、创建由100个服从正太分布的随机数构成的数组
arr2 = np.random.randn(100)
print('生成的随机数组arr1为：\n',arr2)
#3、对创建的两个数组进行四则运算
print('arr1 + arr2: \n',arr1+arr2)
print('arr1 - arr2: \n',arr1-arr2)
print('arr1 * arr2: \n',arr1*arr2)
print('arr1 / arr2: \n',arr1/arr2)
#4、对创建的数组进行简单的统计分析
print('正太分布数数组的累计和为：\n',np.cumsum(arr2))#计算所有元素的累计和
print('正态分布数去重后的值组为：\n',np.unique(arr2))#去除重复值
print('正态分布数组的均值为：',np.mean(arr2))#计算数组均值
print('正态分布数组的标准差为:',np.std(arr2))#计算数组标准差
print('正态分布数组的方差为：',np.var(arr2))#计算数组方差
print('正态分布数组的最小值为:',np.min(arr2))#计算最小值
print('正态分布数组的最大值为：',np.max(arr2))#计算最大值
print('正态分布数组的总和为：',np.sum(arr2))#计算数组总和

arange函数创建的数值范围为0~1间隔为0.01的数组arr1为：
 [0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]
生成的随机数组arr1为：
 [ 0.37517204 -0.90662187 -0.16842276  0.3506788  -0.60029186  0.77079894
 -0.16433354  0.55554588  2.04506682  0.82808001  0.55371444  0.81047621
 -1.04067402  0.26644084 -0.82842205  0.53251156  0.66490927  1.11431905
 -0.82703904  0.51522519  0.89696815 -1.14892814  0.1732837  -0.86799336
 -0.07724154 -0.98355631  1.28020565 -0.25502873  1.44239272  0.70815777
 -1.13214477 -0.58204981  0.83005     2.75880508 -0.46197594 -1.23308561
 

In [2]:
import numpy as np
matr1=np.ones((8,8))
for i in range(8):
    for j in range(8):
        if(i+j)%2==0:
            matr1[i,j]=0
print('国际棋盘对应的矩阵为：\n',matr1)

for i in range(0,8):
    for j in range(0,8):
        if matr1[i,j]==0:
            print("□",end='   ')
        else:
            print("■", end='   ')
    print('\n')

国际棋盘对应的矩阵为：
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   

□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   

□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   

□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   



In [5]:
# 正则表达式练习
# Internet URL
import re
pattern = re.compile(r'^(https?:\/\/)?([\da-z.-]+)\.([a-z.]{2,6})([\/\w .-])\/?$')
def is_url(url):
    if pattern.match(url):
        print("这是一个有效的InternetURL:",url)
    else:
        print("这是一个无效的InternetURL:", url)

is_url("3.com.-")
is_url("thisisaurl")
is_url("www.baidutaobao.com")

# 匹配首尾空白字符的正则表达式
pattern = re.compile(r'^\s|\s$')
def has_blank(blank):
    if pattern.search(blank):
        print("前或后有空白字符",blank)
    else:
        print("前或后都没有空白字符",blank)

has_blank("<span>01</span>")
has_blank(" text ")
has_blank(" string")

# 账号是否合法
pattern = re.compile(r'^[a-zA-Z][a-zA-Z0-9_]{4,15}$')
def is_user(username):
    if pattern.search(username):
        print("这是一个有效的账户名：",username)
    else:
        print("这是一个无效的账户名：",username)

is_user("01_kuaixue")
is_user("huawei-0912")
is_user("xuetang_01")

# 一年的12月
pattern = re.compile(r'^(0?[1-9]|1[0-2])$')
def is_month(month):
    if pattern.match(month):
        print("这是一个有效的月份：",month)
    else:
        print("这是一个无效的月份：",month)

is_month("03")
is_month("2")
is_month("18")

# 18位身份证号码(可识别出生年月日是否正常)
pattern = re.compile(r'^(\d{6})(19[5-9][0-9]|20[0-1][0-9]|2020)(0[1-9]|1[0-2])([0-2][0-9]|3[0-1])(\d{3}([0-9xX]))$')
def is_idcard(idcard):
    if pattern.match(idcard):
        print("这是一个有效的身份证号码：",idcard)
    else:
        print("这是一个无效的身份证号码：",idcard)

is_idcard("411624200502321815")
is_idcard("411664200513191815")
is_idcard("45986620200215187X")

这是一个有效的InternetURL: 3.com.-
这是一个无效的InternetURL: thisisaurl
这是一个有效的InternetURL: www.baidutaobao.com
前或后都没有空白字符 <span>01</span>
前或后有空白字符  text 
前或后有空白字符  string
这是一个无效的账户名： 01_kuaixue
这是一个无效的账户名： huawei-0912
这是一个有效的账户名： xuetang_01
这是一个有效的月份： 03
这是一个有效的月份： 2
这是一个无效的月份： 18
这是一个无效的身份证号码： 411624200502321815
这是一个无效的身份证号码： 411664200513191815
这是一个有效的身份证号码： 45986620200215187X


In [6]:
# 简单爬取网页上的一段文字

import requests
from bs4 import BeautifulSoup

link = "https://so.gushiwen.org/mingju/juv_7c9202538459.aspx"
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36'}

r = requests.get(link, headers = headers)

soup = BeautifulSoup(r.text,"lxml")
content = soup.find("div",class_="contson").text.strip()
print(content)
print("-----------------------------------")

# 爬取练习
out_ = []
link = "https://www.gushiwen.org/shiju/"
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36'}

r = requests.get(link, headers = headers)

soup = BeautifulSoup(r.text,"lxml")
content = soup.find_all("div",class_="cont")
for each in content:
    out = each.a.text.strip()
    out_.append(out)
print(out_)
print("-----------------------------------")

# 连续爬取多页内容上想要的文字
doc = open("古诗文.txt", "w+",encoding='utf-8')

for i in range(1,11):

    link = "https://so.gushiwen.cn/mingjus/default.aspx?page=" + str(i) + "&tstr=&astr=&cstr=&xstr="
    headers = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'
                            ' AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 '
                            'Safari/537.36'}

    r = requests.get(link, headers = headers)
    content_list = []

    soup = BeautifulSoup(r.text,"lxml")
    title = soup.find_all("div",class_ = "cont")
    for each in title[1:51]:
        content = each.text.strip()
        print(content,'\n')
        print(content,'\n',file=doc)

doc.close()
print("-----------------------------------")

# 动态页面的爬取
import json

for page in range(1,5):
    link1 = "https://api-zero.livere.com/v1/comments/list?callback=jQuery1124023920943234792968_1606811653945&limit=10&offset="
    link2 = "&repSeq=4272904&requestPath=%2Fv1%2Fcomments%2Flist&consumerSeq=1020&livereSeq=28583&smartloginSeq=5154&code=&_=1606811653951"
    page_str = str(page)
    link = link1 + page_str +link2
    print(link)

def single_page_comment(link):
    headers = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64)AppleWebKit/537.36 '
                            '(KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36'}
    r = requests.get(link, headers = headers)
    json_string = r.text
    json_string = json_string[json_string.find('{'):-2]
    json_data = json.loads(json_string)
    comment_list = json_data['results']['parents']
    for eachone in comment_list:
        message = eachone['content']
        print(message)

single_page_comment(link)

十年生死两茫茫，不思量，自难忘。千里孤坟，无处话凄凉。纵使相逢应不识，尘满面，鬓如霜。夜来幽梦忽还乡，小轩窗，正梳妆。相顾无言，惟有泪千行。料得年年肠断处，明月夜，短松冈。(肠断 一作：断肠)
-----------------------------------
['古诗文网', '山有木兮木有枝，心悦君兮君不知。', '人生若只如初见，何事秋风悲画扇。', '十年生死两茫茫，不思量，自难忘。', '曾经沧海难为水，除却巫山不是云。', '玲珑骰子安红豆，入骨相思知不知。', '只愿君心似我心，定不负相思意。', '平生不会相思，才会相思，便害相思。', '愿得一心人，白头不相离。', '山无陵，江水为竭。冬雷震震，夏雨雪。天地合，乃敢与君绝。', '入我相思门，知我相思苦。', '去年今日此门中，人面桃花相映红。', '雨打梨花深闭门，忘了青春，误了青春。', '人面不知何处去，桃花依旧笑春风。', '疏影横斜水清浅，暗香浮动月黄昏。', '宁可枝头抱香死，何曾吹落北风中。', '桃之夭夭，灼灼其华。', '寂寞空庭春欲晚，梨花满地不开门。', '人间四月芳菲尽，山寺桃花始盛开。', '不经一番寒彻骨，怎得梅花扑鼻香。', '竹外桃花三两枝，春江水暖鸭先知。', '春宵一刻值千金，花有清香月有阴。', '今人不见古时月，今月曾经照古人。', '海上生明月，天涯共此时。', '月上柳梢头，人约黄昏后。', '二十四桥明月夜，玉人何处教吹箫？', '露从今夜白，月是故乡明。', '沧海月明珠有泪，蓝田日暖玉生烟。', '春江潮水连海平，海上明月共潮生。', '明月几时有？把酒问青天。', '云中谁寄锦书来，雁字回时，月满西楼。', '世间无限丹青手，一片伤心画不成。', '黄沙百战穿金甲，不破楼兰终不还。', '男儿何不带吴钩，收取关山五十州。', '落红不是无情物，化作春泥更护花。', '风萧萧兮易水寒，壮士一去兮不复还。', '呜呼！楚虽三户能亡秦，岂有堂堂中国空无人！', '苟利国家生死以，岂因祸福避趋之！', '夜阑卧听风吹雨，铁马冰河入梦来。', '商女不知亡国恨，隔江犹唱后庭花。', '人生自古谁无死？留取丹心照汗青。', '写景']
-----------------------------------
不积小流，无以成江海。
——荀子《劝学》 

何