In [1]:
active=True
sites=[]
while active:
    site=input("如果你可以去世界的任何一个地方，你想去哪里？")
    sites.append(site)
    over=input("是否结束？Yes/No")
    if over=="Yes":
        active=False
print(sites)

如果你可以去世界的任何一个地方，你想去哪里？ sge
是否结束？Yes/No Yes


['sge']


In [2]:

def describe_city(city='reykjavik',country='iceland'):
    print(city.title()+" is in "+country.title())
describe_city()
describe_city('beijing','china')
describe_city(city='洛杉矶',country='美国')

Reykjavik is in Iceland
Beijing is in China
洛杉矶 is in 美国


In [3]:
def name(first_name,last_name,middle_name=''):
    if middle_name:
        full_name=first_name+' '+middle_name+' '+last_name
    else:
        full_name=first_name+' '+last_name
    return full_name.title()
musician=name('jimi','hendrix')
print(musician)
musician=name('john','lee','hooker')
print(musician)

Jimi Hendrix
John Hooker Lee


In [4]:
def name(first_name,last_name,middle_name):
    if middle_name:
        full_name=first_name+' '+middle_name+' '+last_name
    else:
        full_name=first_name+' '+last_name
    return full_name.title()
while True:
    print("\n请告诉我你的名字")
    print("输入q结束")
    print("如果没有中间名字，请输入空格")
    f_name=input("First_name:")
    l_name=input("Last_name:")
    m_name=input("Middle_name:")
    if f_name=='q':
        break
    if l_name=='q':
        break
    if m_name=='q':
        break
    musician=name(f_name,l_name,m_name)
    print(musician)


请告诉我你的名字
输入q结束
如果没有中间名字，请输入空格


First_name: wang
Last_name: shiyu
Middle_name: shi


Wang Shi Shiyu

请告诉我你的名字
输入q结束
如果没有中间名字，请输入空格


First_name: q
Last_name: q
Middle_name: q


In [5]:
import time
t0 = time.time()
print('显示程序开始的时间：',time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))

t1=time.time()
print('显示程序结束的时间：',time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))
print('用时：%.6fs'%(t1-t0))

显示程序开始的时间： 2020-12-30 17:34:22
显示程序结束的时间： 2020-12-30 17:34:22
用时：0.001000s


In [6]:
import numpy as np
#1、创建一个数值范围为0~1，间隔为0.01的数组
arr1 = np.arange(0,1,0.01)
print('arange函数创建的数值范围为0~1间隔为0.01的数组arr1为：\n',arr1)
#2、创建由100个服从正太分布的随机数构成的数组
arr2 = np.random.randn(100)
print('生成的随机数组arr1为：\n',arr2)
#3、对创建的两个数组进行四则运算
print('arr1 + arr2: \n',arr1+arr2)
print('arr1 - arr2: \n',arr1-arr2)
print('arr1 * arr2: \n',arr1*arr2)
print('arr1 / arr2: \n',arr1/arr2)
#4、对创建的数组进行简单的统计分析
print('正太分布数数组的累计和为：\n',np.cumsum(arr2))#计算所有元素的累计和
print('正态分布数去重后的值组为：\n',np.unique(arr2))#去除重复值
print('正态分布数组的均值为：',np.mean(arr2))#计算数组均值
print('正态分布数组的标准差为:',np.std(arr2))#计算数组标准差
print('正态分布数组的方差为：',np.var(arr2))#计算数组方差
print('正态分布数组的最小值为:',np.min(arr2))#计算最小值
print('正态分布数组的最大值为：',np.max(arr2))#计算最大值
print('正态分布数组的总和为：',np.sum(arr2))#计算数组总和

arange函数创建的数值范围为0~1间隔为0.01的数组arr1为：
 [0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]
生成的随机数组arr1为：
 [-0.30148351  0.67934109  2.41038969 -0.32710512  0.28384773 -0.18908166
  0.37382908  0.40431792  0.89436846  0.2459953   0.21370082  1.4986195
 -1.88741949 -0.25557772 -1.17734665  0.76269741 -1.10286961 -0.62890493
  0.5546019  -1.76801034 -1.02464672 -0.61414269  0.21975434  1.52695032
 -0.27527505  0.46433994  0.39200507 -1.09307698  0.96892757 -0.63628831
 -0.50519087  0.05876157  0.54225376 -0.13304635  0.91112923  0.52596069
  

In [7]:
import numpy as np
matr1=np.ones((8,8))
for i in range(8):
    for j in range(8):
        if(i+j)%2==0:
            matr1[i,j]=0
print('国际棋盘对应的矩阵为：\n',matr1)

for i in range(0,8):
    for j in range(0,8):
        if matr1[i,j]==0:
            print("□",end='   ')
        else:
            print("■", end='   ')
    print('\n')

国际棋盘对应的矩阵为：
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   

□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   

□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   

□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   



In [8]:
import pandas as pd
df = pd.DataFrame(np.array([[85, 68, 90], [82, 63, 88], [84, 90, 78]]), columns=['统计学', '高数', '英语'], index=['张三', '李四', '王五'])
df

统计学  高数  英语
张三   85  68  90
李四   82  63  88
王五   84  90  78

In [9]:
import numpy as np

a = [1, 2, 3]
b = np.array(a, dtype=np.float_)
# 或者
b = np.array(a, dtype=float)

print(b)
print(b.dtype)
print(type(b[0]))

[1. 2. 3.]
float64
<class 'numpy.float64'>


In [10]:
import numpy as np
import array

a = array.array('i', [1, 2, 3, 4])
print(a)

na = np.frombuffer(a, dtype=np.int_)
print(na)

a[0] = 10
print(a)
print(na)

array('i', [1, 2, 3, 4])
[1 2 3 4]
array('i', [10, 2, 3, 4])
[10  2  3  4]


In [12]:
import time
import threading

thread_lock = None
class mythread(threading.Thread):
    def __init__(self,threat_id):
        super(mythread, self).__init__()
        self.threat_id = threat_id

    def run(self):
        #锁定
        thread_lock.acquire()
        for i in range(3):
            print("Thread %d\t is printing!times:%d"%(self.threat_id,i))
        #释放
        thread_lock.release()
        time.sleep(1)

        #锁定
        thread_lock.acquire()
        for i in range(3):
            print("Thread %d\t is printing!times:%d"%(self.threat_id,i))
        # 释放
        thread_lock.release()

def main():
    print("main thread start")
    threads = []

    '''创建线程'''
    for i in range(5):
        thread = mythread(i)
        threads.append(thread)

    '''启动线程'''
    for i in range(5):
        threads[i].start()

    '''等待线程执行完毕'''
    for i in range(5):
        threads[i].join()

    print("main thread finish")

if __name__ == '__main__':
    #获取锁
    thread_lock = threading.Lock()
    main()

main thread start
Thread 0	 is printing!times:0
Thread 0	 is printing!times:1
Thread 0	 is printing!times:2
Thread 1	 is printing!times:0
Thread 1	 is printing!times:1
Thread 1	 is printing!times:2
Thread 2	 is printing!times:0
Thread 2	 is printing!times:1
Thread 2	 is printing!times:2
Thread 3	 is printing!times:0
Thread 3	 is printing!times:1
Thread 3	 is printing!times:2
Thread 4	 is printing!times:0
Thread 4	 is printing!times:1
Thread 4	 is printing!times:2
Thread 0	 is printing!times:0
Thread 0	 is printing!times:1
Thread 0	 is printing!times:2
Thread 1	 is printing!times:0
Thread 1	 is printing!times:1
Thread 1	 is printing!times:2
Thread 2	 is printing!times:0
Thread 2	 is printing!times:1
Thread 2	 is printing!times:2
Thread 3	 is printing!times:0
Thread 3	 is printing!times:1
Thread 3	 is printing!times:2
Thread 4	 is printing!times:0
Thread 4	 is printing!times:1
Thread 4	 is printing!times:2
main thread finish


In [13]:
#导入糖尿病数据
import numpy as np
from sklearn.datasets import load_diabetes
data = load_diabetes()
x = data.data
y = data.target
print(x[:5])
print(y[:5])

[[ 0.03807591  0.05068012  0.06169621  0.02187235 -0.0442235  -0.03482076
  -0.04340085 -0.00259226  0.01990842 -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 -0.02632783 -0.00844872 -0.01916334
   0.07441156 -0.03949338 -0.06832974 -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 -0.00567061 -0.04559945 -0.03419447
  -0.03235593 -0.00259226  0.00286377 -0.02593034]
 [-0.08906294 -0.04464164 -0.01159501 -0.03665645  0.01219057  0.02499059
  -0.03603757  0.03430886  0.02269202 -0.00936191]
 [ 0.00538306 -0.04464164 -0.03638469  0.02187235  0.00393485  0.01559614
   0.00814208 -0.00259226 -0.03199144 -0.04664087]]
[151.  75. 141. 206. 135.]


In [23]:
def is_number(s):
    try:
        float(s)
        return True
    except ValueError:
        pass

    import unicodedata
    try:
        unicodedata.numeric(s)
        return True
    except (TypeError, ValueError):
        pass
        
    if len(s) < 2:
        return False

    try:
        d = 0
        if s.startswith('－'):
            s = s[1:]
        for c in s:
            if c == '－': # 全角减号
                return False
                
            if c == '．': # 全角点号
                if d > 0:
                    return False
                else:
                    d = 1
                    continue
            unicodedata.numeric(c)
        return True
    except (TypeError, ValueError):
        pass

    return False

# 测试字符串和数字
print(f'{is_number("foo")}')
print(f'{is_number("1") }')
print(f'{is_number("1.3") }')
print(f'{is_number("-1.37") }')
print(f'{is_number("1e3") }')
print(f'{is_number("2.345.6") }')
print(f'{is_number("-5.2-8") }')
print(f'{is_number("52-8") }')
print(f'{is_number("-.5") }')
print(f'{is_number("-5.") }')
print(f'{is_number(".5") }')

# 测试Unicode
# 阿拉伯语 5
print(f'{is_number("٥") }')
# 泰语 2
print(f'{is_number("๒") }')
# 中文数字
print(f'{is_number("四") }')
print(f'{is_number("四卅") }')
# 全角数字
print(f'{is_number("１２３") }')
print(f'{is_number("-１２３") }')
print(f'{is_number("－１２３") }')
print(f'{is_number("１２－３") }')
print(f'{is_number("１２３－") }')
print(f'{is_number("１.２３") }')
print(f'{is_number("１．２３") }')
print(f'{is_number("．２３") }')
print(f'{is_number("－．２３") }')
print(f'{is_number("１．23") }')
print(f'{is_number("１．２．３") }')
# 版权号
print(f'{is_number("©") }')

False
True
True
True
True
False
False
False
True
True
True
True
True
True
True
True
True
True
False
False
True
True
True
True
True
False
False


In [24]:
# 获取用户输入数据
nterms = int(input("你需要几项？"))
 
# 第一和第二项
n1 = 0
n2 = 1
count = 2
 
# 判断输入的值是否合法
if nterms <= 0:
   print("请输入一个正整数。")
elif nterms == 1:
   print("斐波那契数列：")
   print(n1)
else:
   print("斐波那契数列：")
   print(n1,",",n2,end=" , ")
   while count < nterms:
       nth = n1 + n2
       print(nth,end=" , ")
       # 更新值
       n1 = n2
       n2 = nth
       count += 1

你需要几项？ 3


斐波那契数列：
0 , 1 , 1 , 

In [25]:
def leftRotate(arr, d, n):
    for i in range(gcd(d,n)):
         
        temp = arr[i]
        j = i
        while 1:
            k = j + d
            if k >= n:
                k = k - n
            if k == i:
                break
            arr[j] = arr[k]
            j = k
        arr[j] = temp

def printArray(arr, size):
    for i in range(size):
        print ("%d" % arr[i], end=" ")

def gcd(a, b):
    if b == 0:
        return a;
    else:
        return gcd(b, a%b)

arr = [1, 2, 3, 4, 5, 6, 7]
leftRotate(arr, 2, 7)
printArray(arr, 7)

3 4 5 6 7 1 2 

In [26]:
def leftRotate(arr, d, n):
    for i in range(d):
        leftRotatebyOne(arr, n)
def leftRotatebyOne(arr, n):
    temp = arr[0]
    for i in range(n-1):
        arr[i] = arr[i+1]
    arr[n-1] = temp
         
 
def printArray(arr,size):
    for i in range(size):
        print ("%d"% arr[i],end=" ")
 

arr = [1, 2, 3, 4, 5, 6, 7]
leftRotate(arr, 2, 7)
printArray(arr, 7)

3 4 5 6 7 1 2 