In [1]:
# Numpy和Pandas都是基于C语言实现的
# Pandas被认为是Numpy的升级版
import numpy as np
array = np.array([[1, 2, 3],
                  [2, 3, 4]])
print(array)
print('number of dim(矩阵的维数):', array.ndim)
print('shape(几行几列):', array.shape)
print('size:', array.size)


[[1 2 3]
 [2 3 4]]
number of dim(矩阵的维数): 2
shape(几行几列): (2, 3)
size: 6


In [2]:
import numpy as np

a = np.array([[2, 23, 4],
              [3, 32, 5],
              [2, 2, 2]])
b = np.zeros((3, 4))
c = np.ones((3, 4))
# 说是一个空的np其实是一个非常接近0的数字
d = np.empty((3, 4))
# 想要生成元素全是2的矩阵
e = 2 * np.ones((3, 4))
# 生成一个np数列从10到20(不包括20)，步长设置为2 
f = np.arange(10, 20, 2)
# 只有一个参数，默认从0开始,想把数列定义成3行4列只需要reshape
g = np.arange(12).reshape((3, 4))
# 生成一个从1到10(不包含10)的数列，第三个参数20，是将这个区间分为20段
h = np.linspace(1, 10, 20).reshape((4, 5))


# print(a.dtype)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)

[[ 2 23  4]
 [ 3 32  5]
 [ 2  2  2]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1.24447972e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.37961302e-306 8.38288416e+169 3.06072738e-057 5.15820460e-062]
 [2.00561523e-076 4.03641705e+175 7.71628549e-043 9.40898543e-047]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[10 12 14 16 18]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1.          1.47368421  1.94736842  2.42105263  2.89473684]
 [ 3.36842105  3.84210526  4.31578947  4.78947368  5.26315789]
 [ 5.73684211  6.21052632  6.68421053  7.15789474  7.63157895]
 [ 8.10526316  8.57894737  9.05263158  9.52631579 10.        ]]


In [3]:
import numpy as np
# 随机生成一个2行4列的矩阵,元素值从0到1
a = np.random.random((2, 4))
print(a)
# 分别对应求矩阵a的最小值，最大值，以及求和
# 其中axis参数表示你想来求每行还是每列的最大，最小或者和
# axis = 0 表示每列，axis = 1表示每行
print(np.min(a))
print(np.max(a))
print(np.sum(a))

print(np.min(a, axis=0))
print(np.max(a, axis=0))
print(np.sum(a, axis=0))


a = np.array([10, 20, 30, 40])
b = np.arange(4)
c = np.array([[1, 1],
              [0, 1]])
d = np.arange(4).reshape((2, 2))
print(c)
print(d)
# 直接相乘
e = c*d
# 矩阵相乘，下列两种方式等效
e_cot = np.dot(c, d)
e_ = c @ d

print(e)
print(e_cot)
print(e_)

print(c)
print(d)

c = a - b
print(c)

c = a + b
print(c)

c = a * b
print(c)

c = a**2
print(c)

print(b)
print(b < 3)


[[0.59166352 0.28094705 0.6324734  0.49806603]
 [0.80168466 0.83274288 0.47870623 0.86406948]]
0.2809470496918286
0.8640694839598247
4.9803532516532405
[0.59166352 0.28094705 0.47870623 0.49806603]
[0.80168466 0.83274288 0.6324734  0.86406948]
[1.39334818 1.11368993 1.11117964 1.36213551]
[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]
[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[10 19 28 37]
[10 21 32 43]
[  0  20  60 120]
[ 100  400  900 1600]
[0 1 2 3]
[ True  True  True False]


In [4]:
import numpy as np

A = np.arange(2, 14).reshape((3, 4))

print(A)
# 输出A中最小值或最大值的索引
print(np.argmin(A))
print(np.argmax(A))
# 逐项累加求和
print(np.cumsum(A).reshape((3, 4)))
# 输出A按照矩阵的排序是第几个(Python中默认从0，0开始)
print(np.nonzero(A))

# 输出矩阵A的转置
print(A.T)
print(np.transpose(A))

# 矩阵转置相乘
print(np.dot(A.T, A))
print(A.T.dot(A))
print(np.transpose(A).dot(A))

# numpy中所有大于9的都变为9，所有小于5的都变为5，在此之间的值保持不变
print(np.clip(A, 5, 9))
# 求A中的行的元素平均值
print(np.mean(A, axis=1))
# 求A中的列的元素平均值
print(np.mean(A, axis=0))


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
[[ 2  5  9 14]
 [20 27 35 44]
 [54 65 77 90]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[140 158 176 194]
 [158 179 200 221]
 [176 200 224 248]
 [194 221 248 275]]
[[140 158 176 194]
 [158 179 200 221]
 [176 200 224 248]
 [194 221 248 275]]
[[140 158 176 194]
 [158 179 200 221]
 [176 200 224 248]
 [194 221 248 275]]
[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]
[ 3.5  7.5 11.5]
[6. 7. 8. 9.]


In [5]:
import numpy as np
A = np.arange(3, 15).reshape((3, 4))
print(A)
# 求矩阵中索引对应的值
print(A[1][1])
print(A[1, 1])
# 求A中第二行所有元素
print(A[2, :])
# 求A中第一列的所有数
print(A[:, 1])
# 求A每一行的数
for row in A:
    print(row)
# 求A每一列的数(即A的转置每一行的数)
for column in A.T:
    print(column)

# 将A变为一行
print(A.flatten())
for item in A.flat:
    print(item)


[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
8
8
[11 12 13 14]
[ 4  8 12]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [6]:
import numpy as np

a = np.array([1, 1, 1])
b = np.array([2, 2, 2])
print(a)
print(b)
# 单行单列的无法直接进行转置，下面的操作则可以将单行转变为单列
A = a[:, np.newaxis]
B = b[:, np.newaxis]
print(A)
print(B)
print(a)
print(b)
a = A[np.newaxis, :]
b = B[np.newaxis, :]
print(A)
print(B)
print(a)
print(b)
# vertical stack上下合并
print(np.vstack((a, b)))
# horizental stack左右合并
print(np.hstack((a, b)))
C = np.vstack((a, b))
print(C)
print(a.shape, C.shape)

D = np.hstack((a, b))
print(D)
print(a.shape, D.shape)


[1 1 1]
[2 2 2]
[[1]
 [1]
 [1]]
[[2]
 [2]
 [2]]
[1 1 1]
[2 2 2]
[[1]
 [1]
 [1]]
[[2]
 [2]
 [2]]
[[[1]
  [1]
  [1]]]
[[[2]
  [2]
  [2]]]
[[[1]
  [1]
  [1]]

 [[2]
  [2]
  [2]]]
[[[1]
  [1]
  [1]
  [2]
  [2]
  [2]]]
[[[1]
  [1]
  [1]]

 [[2]
  [2]
  [2]]]
(1, 3, 1) (2, 3, 1)
[[[1]
  [1]
  [1]
  [2]
  [2]
  [2]]]
(1, 3, 1) (1, 6, 1)


In [7]:
import numpy as np

A = np.arange(12).reshape((3, 4))
print(A)
# 将A按照列分为两块，第二个参数只能是等量分割，4列可以分为2块或者4块
print(np.split(A, 2, axis=1))
# 将A按照行分为三块，同样是等量分割
print(np.split(A, 3, axis=0))

# 不均等分割
print(np.array_split(A, 3, axis=1))

# 行分割
print(np.vsplit(A, 3))
# 列分割
print(np.hsplit(A, 2))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [8]:
import numpy as np

a = np.arange(4)
print(a)
b = a
c = a
d = b

a[0] = 11
# 修改了a其他都变了，其实这些变量相当于都关联了a,即浅拷贝
print(a)
print(b)
print(c)
print(d)

# 深拷贝:只复制值，并不关联
# 所以以后只想要将a的值复制到b这里，而不想关联的话就可以用copy()进行深拷贝
b = a.copy()
print(b)
a[3] = 66
print(a)
print(b)


[0 1 2 3]
[11  1  2  3]
[11  1  2  3]
[11  1  2  3]
[11  1  2  3]
[11  1  2  3]
[11  1  2 66]
[11  1  2  3]


In [9]:
var1 = 'Hello World!'
var2 = "Runoob"
print(type(var1))
print(len(var1))
print ("var1[0]: ", var1[0])
print ("var2[1:5]: ", var2[1:5])

<class 'str'>
12
var1[0]:  H
var2[1:5]:  unoo


In [10]:
sentence = 'hello world'
print(sentence.capitalize())
print(sentence.upper())
print(sentence.title())

Hello world
HELLO WORLD
Hello World


In [11]:
var="www.runoob.com"
sub='o'
print ("var.count('o') : ", var.count(sub))

sub='run'
print ("var.count('run', 0, 10) : ", var.count(sub,0,10))

var.count('o') :  3
var.count('run', 0, 10) :  1


In [12]:
var='Runoob example....wow!!!'
suffix='!!'
print (var.endswith(suffix))
print (var.endswith(suffix, len(var) - 1))
suffix='Run'
print (var.endswith(suffix))
print (var.endswith(suffix, 0, 3))

True
False
False
True
