In [1]:
active=True
sites=[]
while active:
    site=input("你想去哪里？")
    sites.append(site)
    over=input("是否结束？Yes/No")
    if over=="yes":
        active=False
print(sites)

你想去哪里？芬兰
是否结束？Yes/Nono
你想去哪里？北极
是否结束？Yes/Noyes
['芬兰', '北极']


In [5]:
def describe_city(city='nanjing',country='iceland'):
    print(city.title()+" is in "+country.title())
describe_city()
describe_city('beijing','china')
describe_city(city='洛杉矶',country='美国')

Nanjing is in Iceland
Beijing is in China
洛杉矶 is in 美国


In [9]:
import time
t0=time.time()
print('显示程序开始的时间：',time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))

t1=time.time()
print('显示程序结束的时间：',time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))

print('用时：%.6fs'%(t1-t0))

显示程序开始的时间： 2020-12-30 15:29:07
显示程序结束的时间： 2020-12-30 15:29:07
用时：0.000000s


In [11]:
import numpy as np
matrl=np.ones((8,8))
for i in range(8):
    for j in range(8):
        if(i+j)%2==0:
            matrl[i,j]=0
print('国际棋盘对应的矩阵为：\n',matrl)

for i in range(0,8):
    for j in range(0,8):
        if matrl[i,j]==0:
            print("□",end='    ')
        else:
            print("■",end='    ')
    print('\n')

国际棋盘对应的矩阵为：
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
□    ■    □    ■    □    ■    □    ■    

■    □    ■    □    ■    □    ■    □    

□    ■    □    ■    □    ■    □    ■    

■    □    ■    □    ■    □    ■    □    

□    ■    □    ■    □    ■    □    ■    

■    □    ■    □    ■    □    ■    □    

□    ■    □    ■    □    ■    □    ■    

■    □    ■    □    ■    □    ■    □    



In [13]:
import pandas as pd
df = pd.DataFrame(np.array([[85,68,90],[82,63,88],[84,90,78]]),columns=['统计学','高数','英语'],index=['张三','李四','王五'])
df

统计学  高数  英语
张三   85  68  90
李四   82  63  88
王五   84  90  78

In [15]:
import numpy as np

a=[1,2,3]
b=np.array(a,dtype=np.float_)
b=np.array(a,dtype=float)

print(b)
print(b.dtype)
print(type(b[0]))

[1. 2. 3.]
float64
<class 'numpy.float64'>


In [16]:
parameters = initialize_parameters_deep([5,4,3])
print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))

NameError: name 'initialize_parameters_deep' is not defined

In [17]:
class washer(object):
    #定义类属性
    company="Le Xi"
    #1.11定义静态方法
    @staticmethod
    def spins_ml(spins):
        #1.13静态方法只能访问类属性不能访问实例属性
        print("company:",washer.company)
        return spins*0.4

In [20]:
#1.21定义类方法
    @classmethod
    def get_washer(cls,water,scour):
        #1.23类方法只能访问类属性不能访问实例属性
        print("company:",washer.company)
        return cls(water,cls.spins_ml(scour))
   
    def __init__(self,water=10,scour=2):
        self._water=water
        self.scour=scour
        self.year=2010
        
    @property
    def water(self):
        return self._water
    @property
    def total_year(self):
        return 2015-self.year
       
   
    @water.setter
    def water(self,water):
        self._water = water
    
     def set_water(self,water):
        self.water=water
    def set_scour(self,scour):
        self.scour=scour
           
    def add_water(self):
        print("add water",self.water)
    def add_scour(self):
        print("add scour",self.scour)
    def start_wash(self):
      
        self.add_water()
        self.add_scour()
        print("start wash ...")
# if __name__ == '__main__':
#     #1.12访问静态方法
#     print(washer.spins_ml(8))
#     w=washer(100,washer.spins_ml(8))
#     w.start_wash()
    #1.22访问类方法
#     w = washer.get_washer(100, 9)
#     w.start_wash()  
        
#2.类的继承和方法重载
class washerDry(washer):
    def dry(self):
        print("dry clothes...")
    #重载父类方法
    def start_wash(self):
        print("......")
        #使用super一定要指定其父类继承自object
        super(washerDry,self).start_wash()
        print("......")
        
if __name__ == '__main__':
    w = washerDry()
    w.start_wash()
    w.dry()
    

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 25)

In [22]:
bicycles=['trek','cannondale','readline','specialized']
print(bicycles)

['trek', 'cannondale', 'readline', 'specialized']


In [23]:
bicycles=['trek','cannondale','readline','specialized']
print(bicycles[-2])

readline


In [24]:
bicycles=['trek','cannondale','readline','specialized']
message='My first bicycle was a '+bicycles[0].title()+"."
print(message)

My first bicycle was a Trek.


In [25]:
motorcycles=['honda','yamaha','suzuki']
print(motorcycles)
motorcycles[0]='ducati'
print(motorcycles)

['honda', 'yamaha', 'suzuki']
['ducati', 'yamaha', 'suzuki']


In [26]:
motorcycles=[]
motorcycles.append('honda')
motorcycles.append('yamaha')
motorcycles.append('audi')
print(motorcycles)

['honda', 'yamaha', 'audi']


In [29]:
#在任何位置插入元素 insert()
motorcycles=['honda','yamaha','suzuki']
motorcycles.insert(3,'ducati')
print(motorcycles)
motorcycles.insert(1,'BWM')
print(motorcycles)

['honda', 'yamaha', 'suzuki', 'ducati']
['honda', 'BWM', 'yamaha', 'suzuki', 'ducati']


In [30]:
#3.2.3从列表删除元素 del语句
motorcycles=['honda','yamaha','suzuki']
print(motorcycles)
del motorcycles[2]
print(motorcycles)

['honda', 'yamaha', 'suzuki']
['honda', 'yamaha']


In [33]:
#pop()删除元素
motorcycles=['honda','yamaha','suzuki']
last_owned=motorcycles.pop()
print(last_owned)
motorcycles=['honda','yamaha','suzuki','audi']
a=motorcycles.pop()
print(a)

suzuki
audi


In [37]:
#pop()删除列表任何位置的元素
motorcycles=['honda','yamaha','suzuki']
owned=motorcycles.pop(1)
print(owned)
motorcycles=['honda','yamaha','suzuki']
a=motorcycles.pop(0)
print(a)

yamaha
honda


In [39]:
#根据值删除元素remove()
#只删除第一个指定的值，如果在列表出现多次，需要使用循环来判断
motorcycles=['honda','yamaha','suzuki','ducati']
motorcycles.remove('honda')
print(motorcycles)

['yamaha', 'suzuki', 'ducati']


In [41]:
#3.3组织列表
#3.3.1使用方法sort()对列表永久排列
cars=['BWM','AUDI','SUBARU']
cars.sort()
print(cars)
cars=['bmw','audi','subaru','candy']
cars.sort()
print(cars)

['AUDI', 'BWM', 'SUBARU']
['audi', 'bmw', 'candy', 'subaru']


In [42]:
#反转列表
cars=['bmw','audi','subaru','toyota']
cars.reverse()
print(cars)


['toyota', 'subaru', 'audi', 'bmw']


In [43]:
#sorted()临时排序
cars=['bmw','audi','subaru','toyota']
print(sorted(cars))
print(cars)

['audi', 'bmw', 'subaru', 'toyota']
['bmw', 'audi', 'subaru', 'toyota']


In [44]:
magicians=['alice','dayid','carolina']
for magician in magicians:
    print(magician)

alice
dayid
carolina


In [45]:
magicians=['alice','dayid','carolina']
for magician in magicians:
    print(magician.title()+",that was a great trick!")
    print("I!"+magician.title()+".\n")
print("Thank you")

Alice,that was a great trick!
I!Alice.

Dayid,that was a great trick!
I!Dayid.

Carolina,that was a great trick!
I!Carolina.

Thank you


In [47]:
for value in range(1,6):
    print(value)

1
2
3
4
5


In [48]:
#4.3.2list()把数字转化为列表
even_numbers=list(range(2,11,2))
print(even_numbers)

[2, 4, 6, 8, 10]


In [49]:
#**表示乘方运算
squares=[]
for value in range(1,11):
    square=value**2
    squares.append(square)
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [50]:
squares=[]
for value in range(1,100):
    squares.append(value**3)
print(squares)

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000, 1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859, 8000, 9261, 10648, 12167, 13824, 15625, 17576, 19683, 21952, 24389, 27000, 29791, 32768, 35937, 39304, 42875, 46656, 50653, 54872, 59319, 64000, 68921, 74088, 79507, 85184, 91125, 97336, 103823, 110592, 117649, 125000, 132651, 140608, 148877, 157464, 166375, 175616, 185193, 195112, 205379, 216000, 226981, 238328, 250047, 262144, 274625, 287496, 300763, 314432, 328509, 343000, 357911, 373248, 389017, 405224, 421875, 438976, 456533, 474552, 493039, 512000, 531441, 551368, 571787, 592704, 614125, 636056, 658503, 681472, 704969, 729000, 753571, 778688, 804357, 830584, 857375, 884736, 912673, 941192, 970299]


In [51]:
digits=[11,15,41,34]
print(min(digits))
print(max(digits))
print(sum(digits))

11
41
101


In [52]:
#4.3.4列表解析
squares=[value**3 for value in range(1,20)]
print(squares)

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000, 1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859]


In [53]:
#4.4对列表的所有元素处理，或者对一部分处理
#4.4.1切片
players = ['charles', 'martina', 'michael', 'florence', 'eli']
print(players[0:3])
print(players[:2])
print(players[2:])
print(players[-3:])

['charles', 'martina', 'michael']
['charles', 'martina']
['michael', 'florence', 'eli']
['michael', 'florence', 'eli']


In [59]:
players = ['charles', 'martina', 'michael', 'florence', 'eli']
for value in players[:3]:
    print(value.title())
    
for player in players[:3]:
    print(player.title())

Charles
Martina
Michael
Charles
Martina
Michael


In [60]:
my_foods=['pizza','cake','apple']
friend_foods=my_foods[:]
my_foods.append('carrot')
friend_foods.append('ice')
print(my_foods)
print(friend_foods)

['pizza', 'cake', 'apple', 'carrot']
['pizza', 'cake', 'apple', 'ice']
