In [1]:
#通过列表创建数组

import numpy as np
list1 = [0,1,2,3,4]
arr1 = np.array(list1)
print(type(arr1))
print(type(list1))
print(arr1)

#数组和列表的区别：数组基于向量化操作的，列表不是；


# 函数可以应用于数组的每一项，但是列表不行。
#list1+1 错误

print(arr1+2)

#已经定义的numpy数组不可以增加数组的大小，只能通过定义另一个数组来实现，但是列表可以增加大小


#numpy可以通过列表中的列表构建二维数组
list2 = [[0,1,2],[1,2,3],[2,3,4]]
arr2 = np.array(list2)
print(arr2)


#也可以通过dtype参数来指定数组的类型，常用‘float’，‘int‘，’bool‘，’str‘.'object'
arr2_f = np.array(list2,dtype=float)
print(arr2_f)

#可以通过astype转换成不同类型
arr2_int=arr2_f.astype('int')
print(arr2_int)

#先转换成int再转换成str
arr3i_f =arr2_f.astype('int').astype('str')
print(arr3i_f)

#数组要求所有项是同一个类型，如果要一个数组包含不同的类型。要设置’dtype‘为’object‘

arr2_b =np.array([1,0,10],dtype='bool')
print("arr2_b",arr2_b)
arr2_obj =np.array([1,'a'],dtype=object)
print("arr2_obj",arr2_obj)

print(arr2_obj.tolist())

#查看数组的属性和其中的元素

list3=[[1,2,3,4],[2,3,4,5],[3,4,5,6]]
arr3=np.array(list3,dtype='float')
print(arr3)

print('shape:',arr3.shape)
print('dadatype',arr3.dtype)
print('size:',arr3.size)
print('ndim:',arr3.ndim)
print('三行三列',arr3[2,2])


#从数组中提取特定的项

#选择数组的前两行前两列
print(arr3[:2,:2])
#支持bool类型的索引
b=arr3>4
print(b)
#取保留下的原始数据的值
print(arr3[b])

#反转数据的行
print(arr3[::-1,])
#反转数据的行和列
print(arr3[::-1,::-1])


#处理数组的缺省值和无穷大值
#缺省值可以用np.nan表示，np.inf表示无穷大值
arr3[1,2]=np.nan
arr3[1,3]=np.inf
print(arr3)
#用-1代替nan和inf
missing_bool=np.isnan(arr3)|np.isinf(arr3)
arr3[missing_bool]=-1
print(arr3)


#计算n维数组的平均值、最大值和最小值
print("mean value is:",arr3.mean())
print("max value is:",arr3.max())
print("min value is:",arr3.min())

#计算行或列的最小值
print("colum wise min:",np.amin(arr3,axis=0))
print("row wise min:",np.amin(arr3,axis=-1))
#对数组每个元素进行累加，得到一个一维数组，一维数组的大小和原二维数组的大小相等
print(np.cumsum(arr3))


#从现有的数组定义新数组
#如果直接用赋值运算符，则新数组与父数组共同占用一个内存空间，改变新数组的值，父数组的值也随之改变
#为了使新数组和父数组之间相互独立需要使用copy（）函数
arr3a=arr3[:2,:2]
arr3a[:1,:1]=100
print(arr3a)
print(arr3)

arr3b=arr3[:2,:2].copy()
arr3b[:1,:1]=101
print(arr3b)
print(arr3)


#数组的重构（reshaping）和扁平（flattening）
#重构是改变了数组项的排列，并未改变维数
#扁平则是将多维数组转化为一维数组
print(arr3.reshape(4,3))
#数组扁平化有两种方式flatten和ravel
#ravel()处理后的数组是父数组的引用，新数组的改变会影响父数组，并未构建新数组，内存使用率较高
#flatten（）是通过复制的方式构建新数组的
print(arr3.flatten())
#flatten()方法父数组并未改变
b1=arr3.flatten()
b1[0]=0
print(b1)
print(arr3)
#ravel（）父数组发生了改变
b2=arr3.ravel()
b2[0]=101
print(b2)
print(arr3)


#通过numpy生成序列数（sequences），重复数（repetitions）和随机数（random）
#np.arange函数手动生成指定数目的序列数，与ndarray作用一样

#默认下限是0
print(np.arange(5))
#0到9默认步长为1
print(np.arange(0,10))
#步长为2
print(np.arange(0,10,2))
#降序
print(np.arange(10,0,-1))


#上面例子是规定数组步长，下面将规定数组中元素的个数
#构建1到50的数组，一共有10个元素使用np.linspace
print(np.linspace(start=1,stop=50,num=10,dtype=int))#递增步长并不相等，采用四舍五入
#np.logspace以对数尺度的方式增长
np.set_printoptions(precision=2)#设置精度为小数点后两位
print(np.logspace(start=1,stop=50,num=10,base=10))#10作为底数


#初始化元素全为0或者全为1
print(np.zeros([2,2]))
print(np.ones([2,2]))

#构建重复序列数
#np.tile重复整个数组或列表n次，np.repeat重复数组的每一项n次
a=[1,2,3]
print('tile:',np.tile(a,2)) #重复数组a两次
print('repeat:',np.repeat(a,2)) #重复数组a的每一项两次


#生成随机数
print(np.random.rand(2,2))#生成2行2列的[0,1)随机数
print(np.random.randn(2,2))#生成均值为0方差为1的2行2列的正态分布值
print(np.random.randint(0,10,size=[2,2]))#生成[0,10)的2行2列的随机整数
print(np.random.random())#生成一个[0,1)的随机数
print(np.random.random(size=[2,2]))#生成[0,1)的2行2列随机数
print(np.random.choice(['a','b','c','d','f'],size=10))#从给定样本中抽样10次
print(np.random.choice(['a','d','f','x','q'],size=10,p=[0.3,.1,0.1,0.4,0.1]))#从给定的列表和对应的概率分布抽样10次


#如何得到数组独特的（unique）的项和个数（counts）
np.random.seed(100)
arr_rand=np.random.randint(0,10,size=10)
print(arr_rand)

uniqs,counts=np.unique(arr_rand,return_counts=True)
print("uniqs items:",uniqs)
print("counts:",counts)

<class 'numpy.ndarray'>
<class 'list'>
[0 1 2 3 4]
[2 3 4 5 6]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
[['0' '1' '2']
 ['1' '2' '3']
 ['2' '3' '4']]
arr2_b [ True False  True]
arr2_obj [1 'a']
[1, 'a']
[[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]
shape: (3, 4)
dadatype float64
size: 12
ndim: 2
三行三列 5.0
[[1. 2.]
 [2. 3.]]
[[False False False False]
 [False False False  True]
 [False False  True  True]]
[5. 5. 6.]
[[3. 4. 5. 6.]
 [2. 3. 4. 5.]
 [1. 2. 3. 4.]]
[[6. 5. 4. 3.]
 [5. 4. 3. 2.]
 [4. 3. 2. 1.]]
[[ 1.  2.  3.  4.]
 [ 2.  3. nan inf]
 [ 3.  4.  5.  6.]]
[[ 1.  2.  3.  4.]
 [ 2.  3. -1. -1.]
 [ 3.  4.  5.  6.]]
mean value is: 2.5833333333333335
max value is: 6.0
min value is: -1.0
colum wise min: [ 1.  2. -1. -1.]
row wise min: [ 1. -1.  3.]
[ 1.  3.  6. 10. 12. 15. 14. 13. 16. 20. 25. 31.]
[[100.   2.]
 [  2.   3.]]
[[100.   2.   3.   4.]
 [  2.   3.  -1.  -1.]
 [  3.   4.   5.   6.]]
[[101.   2.]
 [  2.   3.]]
[[100.   2.   3

In [2]:
import numpy as np
import pandas as pd

#如何从列表、数组、字典构建series
mylist=list('abcdefghijklmnopqrstuvwxyz') #列表
myarr=np.arange(26) #数组
mydict=dict(zip(mylist,myarr))
#构建方法
ser1=pd.Series(mylist)
ser2=pd.Series(myarr)
ser3=pd.Series(mydict)
print("ser1", ser1)
print("ser2",ser2)
print("ser3 head:",ser3.head())#打印前五个

#使series的索引列转化为dataframe的列
mylist=list('abcdefghijklmnopqrstuvwxyz') #列表
myarr=np.arange(26) #数组
mydict=dict(zip(mylist,myarr))
ser=pd.Series(mydict)
#series转化为dataframe
df=ser.to_frame()
#索引列换为dataframe的列
df.reset_index(inplace=True)
print(df.head())

#结合多个Series组成dataframe
#方法1，axis=1表示列拼接，0表示行拼接
df1=pd.concat([ser1,ser2],axis=1)
#与方法1相比，方法2增加了列名
df2=pd.DataFrame({'col1':ser1,'col2':ser2})
print(df1.head())
print(df2.head())

#命名列索引的名称
ser1.name='alphabets'
print(ser1.head())

#获得series对象A中不包含series对象B的元素
sera=pd.Series([1,2,3,4,5])
serb=pd.Series([4,5,6,7,8])
#返回sera不包含serb的布尔型series
serc=~sera.isin(serb)
print("serc",serc)
print(sera[serc])

#获得SeriesA和SeriseB不相同的项
#求两者的并集
ser_u=pd.Series(np.union1d(sera,serb))
#求两者的交集
ser_i=pd.Series(np.intersect1d(sera,serb))
#ser_i在ser_u上的补集就是两者不相同的项
print(ser_u[~ser_u.isin(ser_i)])

#获得series中单一项的频率计数
ser4=pd.Series(np.take(list('abcdefgh'),np.random.randint(8,size=30)))#随机从“abcdefgh”这8个值中抽取30个组成series
print("ser4:",ser4)
print("value_counts:",ser4.value_counts())

#保留series中前两个频次最多的项，其他替换成“other”
np.random.RandomState(100)
ser5=pd.Series(np.random.randint(1,5,[12]))#从1-4均匀采样12个点组成series
ser5[~ser5.isin(ser5.value_counts().index[:2])]='other'
print('ser5',ser5)


#将numpy数组转化为给定形状的dataframe
ser6=pd.Series(np.random.randint(1,10,35))
df6=pd.DataFrame(ser6.values.reshape(7,5))
print(df6)

#找到series的值是3的倍数的位置
ser7=pd.Series(np.random.randint(1,10,7))
print("ser7",ser7)
print(np.argwhere(ser7 %3 ==0))

#获取series中给定索引的元素
ser8=pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
index=[0,4,6,15,20]
print(ser8.take(index))

#水平和垂直拼接series
ser9=pd.Series(range(5))#0-4步长为1
ser10=pd.Series(list('abcde'))
#水平拼接
df9=pd.concat([ser9,ser10],axis=1)
#垂直拼接
df10=pd.concat([ser9,ser10],axis=0)
print(df9)
print("  ")
print(df10)

#计算series之间的均方差
truth=pd.Series(range(10))#生成0-9之间的整数。步长为1
pred=pd.Series(range(10))+np.random.random(10)#生成（0，9）之间的浮点数
#均方差
s=np.mean((truth-pred)**2)
print("均方差",s)

#如何计算series字符串的长度
ser11=pd.Series(['how','to','kick','ass?'])
len=ser11.map(lambda x:len(x))
print('len',len)

#series中的每个元素的首字母大写
ser12=pd.Series(['how','to','kick','ass?'])
#方法1
ser12new=ser12.map(lambda x:x.title())
#方法2
ser12.map(lambda x:x[0].upper()+x[1:])
#方法3
pd.Series([i.title()] for i in ser12)
print("ser12new",ser12new)

#计算series的一阶导和二阶导
ser13=pd.Series([1,3,6,10,15,21,27,35])
#求一阶导并转化为列表类型
print(ser13.diff().tolist())
#求二阶导并转化为列表类型
print(ser13.diff().diff().tolist())


#将日期字符串转换为timeseries
ser14 = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05'])
time1=pd.to_datetime(ser14)
print(time1)


#对series进行算术运算
#如何对series之间进行算法运算
series1 = pd.Series([3,4,4,4],['index1','index2','index3','index4'])
series2 = pd.Series([2,2,2,2],['index1','index2','index33','index44'])
# 加法
series_add = series1 + series2
print(series_add)
# 减法
series_minus = series1 - series2
# series_minus
#乘法
series_multi = series1 * series2
# series_multi
# 除法
series_div = series1/series2
#series_div

#series是基于索引进行算数运算操作的，pandas会根据索引对数据进行运算，若series之间有不同的索 引，对应的值就为Nan。


#如何用最少出现的字符替代空格符
my_str = 'dbc deb abed gade'
ser15 = pd.Series(list('dbc deb abed gade'))
# 统计元素的频数
freq = ser15.value_counts()
print(freq)
# 求最小频数的字符
least_freq = freq.dropna().index[-1]
print(least_freq)
ch1="".join(ser15.replace(' ', least_freq))
print(ch1)


ser1 0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
ser2 0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32
ser3 head: a    0
b    1
c    2
d    3
e    4
dtype: int64
  index  0
0     a  0
1     b  1
2     c  2
3     d  3
4     e  4
   0  1
0  a  0
1  b  1
2  c  2
3  d  3
4  e  4
  col1  col2
0    a     0
1    b     1
2    c     2
3    d     3
4    e     4
0    a
1    b
2    c
3    d
4    e
Name: alphabets, dtype: object
serc 0     True
1     True
2     True
3    False
4    False
dtype: bool
0    1
1    2
2    3
dtype: int64
0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64
ser4: 0     c
1     g
2     c
3     b
4    

ValueError: Length of passed values is 1, index implies 7.