In [1]:
import requests
import re
import os
import time
###弹幕存储路径
dirName="申论弹幕"
if not os.path.exists(dirName):
    os.mkdir(dirName)

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36'
}
url = 'https://www.bilibili.com/video/BV1W7411t7fy'
##此变量用于改变文件名
count = 0
###爬取106节课的弹幕数据
for each in range(1,106):
    params = {
        'p': str(each)
    }
    ###爬取原网址以获得oid
    response = requests.get(url=url,headers=headers,params=params)
    response.encoding = 'utf-8'
    page_text = response.text
    ##获取oid
    oid = re.findall(r'"base_url":".*?upgcxcode/\d+/\d+/(.*?)/.*?m4s.*?"',page_text,re.S)[0]
    ##获取这节课的名称
    name = re.findall(r'"part":.*?"(.*?)",',page_text,re.S)[count]
    ###爬取弹幕数据
    content_url = 'https://api.bilibili.com/x/v1/dm/list.so?oid='+str(oid)
    content = requests.get(url=content_url,headers= headers)
    content.encoding = 'utf-8'
    content_text = content.text
    ###弹幕数据清理
    real_content = re.findall(r'<.*?d.*?p.*?=.*?".*?".*?>(.*?)</d>',content_text,re.S)
    ###存储弹幕数据
    content_path = dirName + '/' + name + '.txt'
    with open(content_path,'w',encoding = 'utf-8') as fp:
        for cont in real_content:
            fp.write(cont)
            ###使数据更美观
            fp.write('\n')
#####分析每一节课弹幕最多的数据
###把数据存储为字典格式
    content_dict = {}
    for every in real_content:
        if every not in content_dict:
            content_dict[every] = 1
        else:
            content_dict[every] += 1
    ###获取弹幕数最多的数据
    max = list(content_dict.items())[0][1]
    for i in list(content_dict.items()):
        if i[1] >= max:
            max = i[1]
            content_max = i[0]
    print(name+'这节课'+'弹幕最多的是：'+content_max+'，'+'一共有'+str(max)+'条')
    ###防止爬取速度过快
    time.sleep(0.5)
    count += 1

郑岳峰申论课前热身与整体内容介绍1这节课弹幕最多的是：666666，一共有104条
郑岳峰申论课前热身与整体内容介绍2这节课弹幕最多的是：666666，一共有27条
申论01-1总论&概括题及材料阅读三大主线（上）这节课弹幕最多的是：保护，一共有248条
申论01-2总论&概括题及材料阅读三大主线（上）这节课弹幕最多的是：对策，一共有264条
申论01-3总论&概括题及材料阅读三大主线（上）这节课弹幕最多的是：对策，一共有184条
申论01-4总论&概括题及材料阅读三大主线（上）这节课弹幕最多的是：相关人士的看法，一共有109条
申论01-5总论&概括题及材料阅读三大主线（上)这节课弹幕最多的是：二选一，一共有40条
申论02-1概括题及材料阅读三大主线（下）这节课弹幕最多的是：调查统计，一共有91条
申论02-2概括题及材料阅读三大主线（下）这节课弹幕最多的是：见招拆招，一共有97条
申论02-3概括题及材料阅读三大主线（下）这节课弹幕最多的是：洞穿，一共有230条
申论02-4概括题及材料阅读三大主线（下）这节课弹幕最多的是：秘书，一共有121条
申论02-5概括题及材料阅读三大主线（下）这节课弹幕最多的是：爽，一共有64条
申论02-6《专项补充：确定型概括、开放型概括及总括句、合并、分类问题》这节课弹幕最多的是：自然而然，顺势而为，一共有76条
申论03-1申论文章三种文体的框架结构与理论素养这节课弹幕最多的是：二选一，一共有45条
申论03-2申论文章三种文体的框架结构与理论素养这节课弹幕最多的是：议论文，一共有27条
申论03-3申论文章三种文体的框架结构与理论素养这节课弹幕最多的是：求深不求全，一共有119条
申论03-4申论文章三种文体的框架结构与理论素养这节课弹幕最多的是：中心主题，一共有74条
申论03-5申论文章三种文体的框架结构与理论素养这节课弹幕最多的是：但是，一共有44条
申论03-6申论文章三种文体的框架结构与理论素养这节课弹幕最多的是：材料，一共有29条
申论04-1策论文的理论应用：15联考真题这节课弹幕最多的是：中心主题，一共有152条
申论04-2策论文的理论应用：15联考真题这节课弹幕最多的是：大文章强调有选择性的利用材料，一共有196条
申论04-3策论文的理论应用：15联考真题这节课弹幕最多的是：思想，一共有126条
申论

In [2]:
def day(y, m, d):#计算y年m月d日是星期几

    y0 = y - (14 - m)//12
    x = y0 + y0//4 - y0//100 + y0 //400
    m0 = m + 12*((14 - m)//12) - 2
    d0 = (d + x + 31*m0//12) % 7
    return d0       #注意，周日是0

def isLeapYear(year): #判断year年是否闰年
    isLeapYear = True       
    if year % 4 ==0:       #整除可不是等于0，天
        if year % 100 ==0:
            if year % 400 ==0:
                isLeapYear = True
            else:
                isLeapYear = False
        else:
            isLeapYear = True      
    else:
        isLeapYear = False      #注意是一个等号还是两个等号
    return isLeapYear

def calendar(y, m): #打印y年m月日历
    print('       {}年{}月'.format(y,m))
    print('Su\tM\tTu\tW\tTh\tF\tSa')
    # 请在下面编写代码
    # ********** Begin ********** #
    month_1 = [1,3,5,7,8,10,12]
    month_2 = [4,6,9,11]
    momth_number = 0
    if isLeapYear(y):           #计算这个月有多少天
        if m == 2:
            month_number = 29
        else:
            if m in month_1:
                month_number = 31
            if m in month_2:
                month_number = 30
    else:
        if m == 2:
            month_number = 28
        else:
            if m in month_1:
                month_number = 31
            if m in month_2:
                month_number = 30 
                
    table = day(y, m, 1)       #空格     排列输出
    for j in range (1,month_number + 1):        #注意加一
        if j == 1:
            print("\t" * table,end = '')
        j = str(j)
        print(j + "\t",end = '')
        j = eval(j)
        if (j + day(y, m, 1)) % 7 == 0:
            print("\r")
    print("\r")
 
for (y,m) in [(2020,12), (2017,2), (2016,2)]:
        calendar(y, m)
        print('---------------------------')

       2020年12月
Su	M	Tu	W	Th	F	Sa
		1	2	3	4	5	
6	7	8	9	10	11	12	
13	14	15	16	17	18	19	
20	21	22	23	24	25	26	
27	28	29	30	31	
---------------------------
       2017年2月
Su	M	Tu	W	Th	F	Sa
			1	2	3	4	
5	6	7	8	9	10	11	
12	13	14	15	16	17	18	
19	20	21	22	23	24	25	
26	27	28	
---------------------------
       2016年2月
Su	M	Tu	W	Th	F	Sa
	1	2	3	4	5	6	
7	8	9	10	11	12	13	
14	15	16	17	18	19	20	
21	22	23	24	25	26	27	
28	29	
---------------------------


In [3]:

import requests
import bs4
import multiprocessing
import threading
import time
from multiprocessing import Queue
 
 
exitFlag = 0
start = time.time()
class myThread (threading.Thread):
    def __init__(self, q):
        threading.Thread.__init__(self)
        self.q = q
 
    def run(self):
        while not self.q.empty():
            crawler(self.q)
        return self.q.qsize()
 
 
base_url = ''
headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36",
        "Connection": "keep-alive",
        'Pragma': 'no-cache',
    }
def crawler(q):
    structure, url = q.get(timeout=2)
    try:
        res =requests.get(base_url+url, headers=headers)
        soup = bs4.BeautifulSoup(res.content.decode('gb18030'), 'lxml')
        # Todo:数据处理
    except Exception as e:
        pass
    pass
 
def generate(filename):
    link_list = []
    with open(filename, 'r', encoding='utf8') as f1:
        for line in f1.readlines():
            line = line.split()
            link_list.append((' '.join(line[:-1]), line[-1]))
    return link_list
 
def mp(link_list, num):
    '''
        :link_list:任务列表
        :num:进程数量
    '''
    queueLock = threading.Lock()
    # 进程共享队列
    workQueue = Queue(len(link_list))
    queueLock.acquire()
    # 填充
    for word in link_list:
        workQueue.put(word)
    queueLock.release()
    # 进程队列
    threads = []
    # 创建新线程
 
    for i in range(num):
        thread = myThread(workQueue)
        thread.start()
        threads.append(thread)
 
    # 等待队列清空
    while not workQueue.empty():
        pass
 
    # 通知线程是时候退出
    exitFlag = 1
 
    # 等待所有线程完成
    for t in threads:
        t.join()

print('***********', time.time()-start)

*********** 0.0


In [5]:

import numpy as np
 
 
def main():
    """
    f(x) = max{x1 + x2}
    x1 in range(1023)
    x2 in range(1023)
    """
   
    NUM_DNA = 2
    # 把变量用二进制表示，每个变量用PER_DNA_LENGTH位二进制表示
    PER_DNA_LENGTH = 10
    # 种群中包含个体的数量为POP_SIZE个
    POP_SIZE = 100
    # 初始化一个包含POP_SIZE个个体的种群
    pop = init_population(POP_SIZE, PER_DNA_LENGTH, NUM_DNA)
    generation_num = 1000
    t = 0
    while t < generation_num:
        # 交叉产生新种群
        cross_pop = cross(pop, NUM_DNA, PER_DNA_LENGTH)
        # 种群变异
        mutation_pop = mutation(cross_pop, NUM_DNA, PER_DNA_LENGTH)
        # 计算种群适应度
        fitness_matrix = evaluate_fitness(mutation_pop, PER_DNA_LENGTH)
        # 选择新种群
        new_pop = select(mutation_pop, fitness_matrix, POP_SIZE)
        # 新种群替换老种群
        pop = new_pop
        t+=1
    result = gene_decode(pop, PER_DNA_LENGTH)
    print("x1:",result[0])
    print("x2:",result[1])
 
 
def init_population(pop_num, dna_length, dna_size):
    """
    初始化一个种群
    :param pop_num: 种群数量
    :param dna_length: DNA长度
    :param dna_size: DNA个数
    :return: 二进制种群
    [
     [1 1 0 0 0 0 0 1]
     [0 1 0 1 1 1 0 1]
     [0 0 1 1 1 0 1 1]
    ]
    """
    return np.random.randint(2, size=(pop_num, dna_length * dna_size))
 
 
def F(x, y):
    return x+y
 
 
def evaluate_fitness(pop, per_dna_length):
    """
    计算适应度
    :param pop:
    :param per_dna_length:
    :return:
    """
    x, y = gene_decode(pop, per_dna_length)
    return x+y
 
 
def select(pop, fitness_matrix, pop_size):
    """
    通过适应度选择种群
    :param pop: 种群
    :param fitness_matrix: 适应度举证
    :param pop_size: 种群数量
    :return:
    """
    try:
        idx = np.random.choice(np.arange(pop_size), size=pop_size, replace=True,
                               p=fitness_matrix / (fitness_matrix.sum()))
    except:
        raise Exception
    return pop[idx]
 
 
def gene_decode(pop, per_dna_length):
    """
    把二进制数组还原成数字
    :param pop: 群组
    :param per_dna_length: 每个基因的长度
    :return:
    """
    x = pop[:, :per_dna_length]
    y = pop[:, per_dna_length:]
    return x.dot(2**np.arange(10)[::-1]),y.dot(2**np.arange(10)[::-1])
 
 
def cross(pop, num_dna, per_dna_length, cross_rate=0.5):
    """
    :param pop: 种群
    :param num_dna: DNA个数
    :param per_dna_length: 每个DNA的长度
    :param cross_rate: 交叉概率
    :return:
    """
    new_pop = []
    for i in pop:
        k = i
        if np.random.rand() < cross_rate:
            j = pop[np.random.randint(len(pop))]
            # 随机选择一个交叉点
            cross_points = np.random.randint(low=0, high=num_dna * per_dna_length)
            k[cross_points:] = j[cross_points:]
        new_pop.append(k)
    return new_pop
 
 
def mutation(pop, num_dna, per_dna_length, mutation_rate=0.05):
    """
    变异
    :param pop:
    :param num_dna:
    :param per_dna_length:
    :param mutation_rate:
    :return:
    """
    new_pop = []
    for i in pop:
        if np.random.rand() < mutation_rate:
            # 随机选择一个变异点
            mutation_point = np.random.randint(low=0, high=num_dna * per_dna_length)
            i[mutation_point] ^= 1
        new_pop.append(i)
    return np.array(new_pop)
 
 
if __name__ == '__main__':
    main()

x1: [ 977 1017  985  893  977 1009  977  997 1009 1013  977  985 1013  985
 1013 1009  985  977 1017 1016 1013  985  977  977  977  977  985 1009
  985  985 1017  985 1013  977  977  977  977  977 1013 1009 1009  977
  977 1013 1013  977 1009 1009 1016  977  985  977 1013 1013 1009 1013
  977  497  987  985  985  977  985 1009 1013  977  977  977 1016  977
  985 1021  987  977 1009 1017  981  977 1013  977  985  977 1013  985
  977  889  893 1009 1009  977 1013 1013 1009  977  985 1013 1013  977
  985  977]
x2: [1017  945 1017  752 1017 1009  953 1009  953 1017  952  944 1017  953
 1009 1009 1009 1017  497  761 1017 1008  946  953  944 1017 1008 1009
  946 1008  945 1009 1009  944  953  945  944 1010  945  953  953 1010
  946 1009  953 1010 1010  953  761 1017 1008 1017 1017 1009 1010 1009
  953 1010  945 1008 1017  953  944  953 1017  953 1017 1009  761 1010
 1009  497  945  953 1010  946 1009  952 1017 1017 1008 1009  945 1009
  944  945  752 1010  497  945 1009 1009  953  953 1008  