In [6]:
pip install altair vega_datasets

Note: you may need to restart the kernel to use updated packages.


In [15]:
import altair as alt
import pandas as pd

data = pd.DataFrame({'col-1':
list('CCCDDDEEE'),
                    'col-2':
[2, 7, 4, 1, 2, 6, 8, 4, 7]})
chart = alt.Chart(data)
alt.Chart(data).mark_point()

alt.Chart(...)

In [26]:
import altair as alt
import pandas as pd

data = pd.DataFrame({'col-1':
list('CCCDDDEEE'),
                    'col-2':
[2, 7, 4, 1, 2, 6, 8, 4, 7]})
chart = alt.Chart(data)
alt.Chart(data).mark_point().encode(
    x='col-1',
    y='col-2'
)

alt.Chart(...)

In [27]:
import altair as alt
import pandas as pd

data = pd.DataFrame({'col-1':
list('CCCDDDEEE'),
                    'col-2':
[2, 7, 4, 1, 2, 6, 8, 4, 7]})
chart = alt.Chart(data)
alt.Chart(data).mark_point().encode(
    x='col-1',
    y='col-2'
).interactive()

alt.Chart(...)

In [29]:
from vega_datasets import data

cars = data.cars()

In [30]:
brush = alt.selection_interval()

In [32]:
alt.Chart(cars).mark_point().encode(
    x='Milles_per_Gallon:Q',
    y='Horsepower:Q',
    color='Origin:N'
).add_selection(
    brush
)

alt.Chart(...)

In [33]:
alt.Chart(cars).mark_point().encode(
    x='Milles_per_Gallon:Q',
    y='Horsepower:Q',
    
color=alt.condition(brush, 'Origin:N', alt.value('lightgray'))
).add_selection(
    brush
)

alt.Chart(...)

In [34]:
alt.Chart(cars).mark_bar().encode(
    y='Origin:N',
    color='Origin:N',
    x='count(Origin):Q'
)

alt.Chart(...)

In [42]:
pip install jieba

  Created wheel for jieba: filename=jieba-0.42.1-py3-none-any.whl size=19314481 sha256=e1ac4b88b5d08046c5cef7d570c69fedc67c3f2391e5733202b6361ac14140d6
  Stored in directory: c:\users\linxu\appdata\local\pip\cache\wheels\ca\38\d8\dfdfe73bec1d12026b30cb7ce8da650f3f0ea2cf155ea018ae
Successfully built jieba



In [43]:
import pandas as pd
import jieba

In [49]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('max_colwidth', 100)

In [54]:
tweets = pd.read_csv('C:/Users/linxu/weibo_hashtag/weibo/#进击的巨人最终季#/#进击的巨人最终季#.csv', usecols=['正文'])     

In [56]:
tweets['jieba分词'] = tweets.apply(lambda x: ';'.join(jieba.cut(x['正文'])), axis=1)
tweets

Building prefix dict from the default dictionary ...
Dumping model to file cache C:\Users\linxu\AppData\Local\Temp\jieba.cache
Loading model cost 1.993 seconds.
Prefix dict has been built successfully.


正文  \
0                                 #进击的巨人最终季#能在被全面封禁的状态下再度冲上热搜的也只有我大巨人了吧作为一个第一季出来就开始追的老粉真的泪目三连，巨人必将名垂青史    
1               #进击的巨人最终季# 多少年前的青春啊终于迎来最终季 #第一季第二季第三季第四季# 都不舍得看完全部。。。看完了真的青春也就结束了。。。回不来的就再也回不来了，熟肉平仑🈶️    
2                       以你的心诠释我的爱今日开机，进击的巨人第四季12集有了！！！ 幸福来得太突然了吧嘎嘎嘎 #进击的巨人##进击的巨人最终季# 。想看先 ！！！ ，来看评！！！    
3             看完巨人最终季熟肉觉得真的超出预期了，也逐渐适应了新制作的画风，一直都维持水平，巨人第四季全集就可以封神了#进击的巨人# 看平仑区 #进击的巨人最终季# #进击的巨人 第四季#    
4                                                                         #进击的巨人最终季# 感觉可以从第一季开始重新追一遍了…    
5                                                      吗的 好后悔追了巨人漫画 对剧情不怎么期待 唯一期待就是画风和画面夸张效果#进击的巨人最终季#    
6                                                                   #进击的巨人最终季# 霸权番+神番的一部作品转眼大结局只希望兵长平安    
7                                                                   #进击的巨人最终季#  第一集可真致郁啊 咒术最新两集也么好到哪里去    
8                                                                          #进击的巨人最终季#青春终于要结束了🔚感慨，感激，感动    
9                                                               #进击的巨人最终季#终于来了，得连着一起再看一遍，很怀念高三在教室看的时光。    
10                                                          #进击的巨人最终季# 天呐，跟着海贼王拖了这么久，最新一集的进击的巨人简直是封神之作    
11                                    #进击的巨人最终季#第四季终于来了，这两天把第一部，第二部，第三部重新看了一遍，热血沸腾，一起来看看最终偏，熟肉已经在下面热好了    
12  #进击的巨人最终季#第一季很好看，战争就是这样无情吧。等待着被从飞机投掷而下的“敢死队”，被无智商巨人生物兵器恐吓着的敌军，一边利用着巨人之力、一边鄙视着巨人之族的马莱，想要改善自己同胞待遇的...   
13                                                                     #进击的巨人最终季#好激动啊我的利威尔要回来了啊啊啊啊啊，哭惹    
14  #进击的巨人最终季# 怎么说呢，马趴是用心了的，同期还负责咒术，加上又是巨人这么大的ip，对于漫画党而言要求真的不高， 按照作者的说法大概 136话巨人完结，只希望谏山老贼少发点刀，千万千万千...   
15                                                                          #进击的巨人最终季# 有生之年系列。高中开始看到现在    
16                                               #进击的巨人最终季#啊啊啊啊啊啊啊啊啊啊😭😭😭😭😭看完第一集太震撼了，整个人鸡皮疙瘩都起来了进巨，yyds    
17                                   #鬼灭之刃 无限列车篇##进击的巨人##进击的巨人最终季# 两个一起出来了，终于看完啦，好开心，看剧找她@爱追剧的小粥粥 ，没要💰    
18                                                                     #进击的巨人最终季#虽然第三季还没看完 但是还是好期待第四季！    
19                                    #进击的巨人最终季# 多少年前的青春啊我们终于迎来了最终季，我要一次性看完 #第一季第二季第三季第四季# 一起去看吧熟肉平仑🈶️    
20                                                                          巨人走在了不良人和无限列车的前面#进击的巨人最终季#    
21                                                                 #进击的巨人最终季#第一集就让我明白了，原来人肉冲击还可以这样玩 马莱    
22                                                               #进击的巨人最终季#第一集就这么强的嘛视角对换真的太妙了，真真无正义皆立场    
23                                                            #进击的巨人最终季#周末抽时间把一二三全部重新看了一遍 要不然就感觉没那么激情了    
24                                                                  #进击的巨人最终季# 呜呜我最爱的兵长！一二季我都快忘了，又该重温了    
25                                                                        #进击的巨人最终季#看起来看起来!呜呜呜，居然到了最终季    
26           #进击的巨人最终季#呜呜，终于等到了进击的巨人第四季，七年了，攻守互换，墙内的人终于来到墙外，看见了世界，是时候给一切画上句号了，又重温了第一季第二季第三季，真的是我最爱的动漫了    
27           #进击的巨人最终季# 终于开播了，第一集就被激烈的战争场面给震撼到，不愧是当今最顶级制作水准的动漫。单是配乐就可比肩入围奥斯卡的电影水平。只有惊叹！值得珍惜、细品这最终季的每一集    
28                                                                         大一至现在希望利威尔结局是好的♥️#进击的巨人最终季#    
29                                                                        #进击的巨人最终季#我靠，我爽了我爽了，第一集就有被爽到    
30                                                  #进击的巨人最终季#致两千年后的你，我永远无法忘记这一幕伏笔揭开时那种震撼我妈的懵逼和膝盖软了的感觉    
31                                                     #进击的巨人最终季#好狠，顶风作案，这是多少人的青春啊！最后一季完完整整放完，墙别封太死plz    
32                                                             #进击的巨人最终季# 又上热搜了！可我还不知道哪里可以看呢！啊啊啊啊啊啊啊啊啊    
33                                                              #进击的巨人最终季#哇啊啊啊  终于等到进击的巨人第四季了  爷青回！！！     
34                                                                            #进击的巨人最终季#媲美钢炼的神仙番，它lei了    
35                                                                 #进击的巨人最终季#嗷嗷嗷，明天看起来～兵长我来啦～艾导我来啦～开心🥳    
36                       #进击的巨人最终季#我不管我不管等我考完研我要从第一季重新看一百遍 当初高一那个丑丑的兵长手办还有特意从日本带回来的链子还锁我杂物柜呢我 想看！此时此刻！    
37                                 

In [57]:
pip install snownlp


  Created wheel for snownlp: filename=snownlp-0.12.3-py3-none-any.whl size=37760960 sha256=0deb10fdd3d557ef0138eb6fda2e9d650a3701556e464112c8d23d3dee23a6af
  Stored in directory: c:\users\linxu\appdata\local\pip\cache\wheels\09\14\c5\ea9aee34229caa97c6f6ff78c82c7f2b1a3423c1f37227b6a6
Successfully built snownlp


In [58]:
import pandas as pd
from snownlp import SnowNLP

In [59]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('max_colwidth', 100)

In [61]:
tweets = pd.read_csv('C:/Users/linxu/weibo_hashtag/weibo/#进击的巨人最终季#/#进击的巨人最终季#.csv', usecols=['正文'])  

In [62]:
tweets['snownlp分词'] = tweets.apply(lambda x: ';'.join(SnowNLP(x['正文']).words), axis=1)

In [63]:
tweets['情感分数'] = tweets.apply(lambda x: SnowNLP(x['正文']).sentiments, axis=1)
tweets

正文  \
0                                 #进击的巨人最终季#能在被全面封禁的状态下再度冲上热搜的也只有我大巨人了吧作为一个第一季出来就开始追的老粉真的泪目三连，巨人必将名垂青史    
1               #进击的巨人最终季# 多少年前的青春啊终于迎来最终季 #第一季第二季第三季第四季# 都不舍得看完全部。。。看完了真的青春也就结束了。。。回不来的就再也回不来了，熟肉平仑🈶️    
2                       以你的心诠释我的爱今日开机，进击的巨人第四季12集有了！！！ 幸福来得太突然了吧嘎嘎嘎 #进击的巨人##进击的巨人最终季# 。想看先 ！！！ ，来看评！！！    
3             看完巨人最终季熟肉觉得真的超出预期了，也逐渐适应了新制作的画风，一直都维持水平，巨人第四季全集就可以封神了#进击的巨人# 看平仑区 #进击的巨人最终季# #进击的巨人 第四季#    
4                                                                         #进击的巨人最终季# 感觉可以从第一季开始重新追一遍了…    
5                                                      吗的 好后悔追了巨人漫画 对剧情不怎么期待 唯一期待就是画风和画面夸张效果#进击的巨人最终季#    
6                                                                   #进击的巨人最终季# 霸权番+神番的一部作品转眼大结局只希望兵长平安    
7                                                                   #进击的巨人最终季#  第一集可真致郁啊 咒术最新两集也么好到哪里去    
8                                                                          #进击的巨人最终季#青春终于要结束了🔚感慨，感激，感动    
9                                                               #进击的巨人最终季#终于来了，得连着一起再看一遍，很怀念高三在教室看的时光。    
10                                                          #进击的巨人最终季# 天呐，跟着海贼王拖了这么久，最新一集的进击的巨人简直是封神之作    
11                                    #进击的巨人最终季#第四季终于来了，这两天把第一部，第二部，第三部重新看了一遍，热血沸腾，一起来看看最终偏，熟肉已经在下面热好了    
12  #进击的巨人最终季#第一季很好看，战争就是这样无情吧。等待着被从飞机投掷而下的“敢死队”，被无智商巨人生物兵器恐吓着的敌军，一边利用着巨人之力、一边鄙视着巨人之族的马莱，想要改善自己同胞待遇的...   
13                                                                     #进击的巨人最终季#好激动啊我的利威尔要回来了啊啊啊啊啊，哭惹    
14  #进击的巨人最终季# 怎么说呢，马趴是用心了的，同期还负责咒术，加上又是巨人这么大的ip，对于漫画党而言要求真的不高， 按照作者的说法大概 136话巨人完结，只希望谏山老贼少发点刀，千万千万千...   
15                                                                          #进击的巨人最终季# 有生之年系列。高中开始看到现在    
16                                               #进击的巨人最终季#啊啊啊啊啊啊啊啊啊啊😭😭😭😭😭看完第一集太震撼了，整个人鸡皮疙瘩都起来了进巨，yyds    
17                                   #鬼灭之刃 无限列车篇##进击的巨人##进击的巨人最终季# 两个一起出来了，终于看完啦，好开心，看剧找她@爱追剧的小粥粥 ，没要💰    
18                                                                     #进击的巨人最终季#虽然第三季还没看完 但是还是好期待第四季！    
19                                    #进击的巨人最终季# 多少年前的青春啊我们终于迎来了最终季，我要一次性看完 #第一季第二季第三季第四季# 一起去看吧熟肉平仑🈶️    
20                                                                          巨人走在了不良人和无限列车的前面#进击的巨人最终季#    
21                                                                 #进击的巨人最终季#第一集就让我明白了，原来人肉冲击还可以这样玩 马莱    
22                                                               #进击的巨人最终季#第一集就这么强的嘛视角对换真的太妙了，真真无正义皆立场    
23                                                            #进击的巨人最终季#周末抽时间把一二三全部重新看了一遍 要不然就感觉没那么激情了    
24                                                                  #进击的巨人最终季# 呜呜我最爱的兵长！一二季我都快忘了，又该重温了    
25                                                                        #进击的巨人最终季#看起来看起来!呜呜呜，居然到了最终季    
26           #进击的巨人最终季#呜呜，终于等到了进击的巨人第四季，七年了，攻守互换，墙内的人终于来到墙外，看见了世界，是时候给一切画上句号了，又重温了第一季第二季第三季，真的是我最爱的动漫了    
27           #进击的巨人最终季# 终于开播了，第一集就被激烈的战争场面给震撼到，不愧是当今最顶级制作水准的动漫。单是配乐就可比肩入围奥斯卡的电影水平。只有惊叹！值得珍惜、细品这最终季的每一集    
28                                                                         大一至现在希望利威尔结局是好的♥️#进击的巨人最终季#    
29                                                                        #进击的巨人最终季#我靠，我爽了我爽了，第一集就有被爽到    
30                                                  #进击的巨人最终季#致两千年后的你，我永远无法忘记这一幕伏笔揭开时那种震撼我妈的懵逼和膝盖软了的感觉    
31                                                     #进击的巨人最终季#好狠，顶风作案，这是多少人的青春啊！最后一季完完整整放完，墙别封太死plz    
32                                                             #进击的巨人最终季# 又上热搜了！可我还不知道哪里可以看呢！啊啊啊啊啊啊啊啊啊    
33                                                              #进击的巨人最终季#哇啊啊啊  终于等到进击的巨人第四季了  爷青回！！！     
34                                                                            #进击的巨人最终季#媲美钢炼的神仙番，它lei了    
35                                                                 #进击的巨人最终季#嗷嗷嗷，明天看起来～兵长我来啦～艾导我来啦～开心🥳    
36                       #进击的巨人最终季#我不管我不管等我考完研我要从第一季重新看一百遍 当初高一那个丑丑的兵长手办还有特意从日本带回来的链子还锁我杂物柜呢我 想看！此时此刻！    
37                                 

In [64]:
import numpy

In [65]:
import numpy as np

In [68]:
from numpy import *

In [70]:
a = np.array([1, 4, 5, 8], float)
a

array([1., 4., 5., 8.])

In [74]:
array([1., 4., 5., 8.])
type(a)

numpy.ndarray

In [75]:
a[:2]

array([1., 4.])

In [76]:
a[3]

8.0

In [80]:
a[0] = 5.
a

array([5., 4., 5., 8.])

In [81]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [82]:
a[0,0]

1.0

In [83]:
a[0,1]

2.0

In [84]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a[1,:]

array([4., 5., 6.])

In [85]:
a[:,2]

array([3., 6.])

In [86]:
a[-1:, -2:]

array([[5., 6.]])

In [87]:
a.shape

(2, 3)

In [88]:
a.dtype

dtype('float64')

In [89]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
len(a)

2

In [90]:
a = np.array([[1, 2 ,3], [4, 5, 6]], float)
2 in a

True

In [91]:
0 in a

False

In [92]:
a = np.array(range(10), float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [95]:
array([[0., 1.], [2., 3.], [4., 5.], [6., 7.], [8., 9.]])
a.shape

(10,)

In [96]:
a = np.array([1, 2 ,3], float)
b = a
c = a.copy()
a[0] = 0
a

array([0., 2., 3.])

In [97]:
b

array([0., 2., 3.])

In [98]:
c

array([1., 2., 3.])

In [99]:
a.tolist()

[0.0, 2.0, 3.0]

In [100]:
list(a)

[0.0, 2.0, 3.0]

In [101]:
s = a.tostring()
s

b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [102]:
np.fromstring(s)

<ipython-input-102-6c2008ed54c7>:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring(s)


array([0., 2., 3.])

In [103]:
a = array([1, 2, 3], float)
a

array([1., 2., 3.])

In [104]:
a.fill(0)
a

array([0., 0., 0.])

In [106]:
a = np.array(range(6), float)
a

array([0., 1., 2., 3., 4., 5.])

In [107]:
a.transpose()

array([0., 1., 2., 3., 4., 5.])

In [108]:
import numpy as np

In [111]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [112]:
print( x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [113]:
print (x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [114]:
print( x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [115]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [117]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v, w))

219
219


In [118]:
print(v.dot(v))
print(np.dot(x, v))

181
[29 67]


In [119]:
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [120]:
x = np.array([[1, 2], [3, 4]])

print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


In [121]:
pip install you-get

In [173]:
%%cmd
you-get http://v.youku.com/v_show/id_XMzUzMjUxOTc1Mg==.html?spm=a2hww.20

Microsoft Windows [Version 10.0.19041.685]
(c) Корпорация Майкрософт (Microsoft Corporation), 2020. Все права защищены.

(base) C:\Users\linxu\Downloads>you-get http://v.youku.com/v_show/id_XMzUzMjUxOTc1Mg==.html?spm=a2hww.20
site:                дј�й…· (Youku)
title:               走入机械世界，四大经理人斗智斗勇，铁甲争夺�一触即发
stream:
    - format:        mp4hd2v2
      container:     mp4
      video-profile: и¶…жё…
      size:          77.8 MiB (81610370 bytes)
      m3u8_url:      http://pl-ali.youku.com/playlist/m3u8?vid=XMzUzMjUxOTc1Mg&type=hd2&ups_client_netip=b2da1a80&utid=OqNfGPiqgmkCAbLaGoCz2tN5&ccode=0590&psid=91591528c45f5ec3dccbfd9fc5c420c5475a3&duration=290&expire=18000&drm_type=1&drm_device=10&dyt=1&btf=&rid=20000000528048296B51F9CA80B50A2879BEDD5B02000000&ups_ts=1608037694&onOff=0&encr=0&ups_key=3143470406fc21321b9055c0032f33c1
    # download-with: you-get --format=mp4hd2v2 [URL]



(base) C:\Users\linxu\Downloads>

you-get: Skipping .\\u8d70\u5165\u673a\u68b0\u4e16\u754c\uff0c\u56db\u5927\u7ecf\u7406\u4eba\u6597\u667a\u6597\u52c7\uff0c\u94c1\u7532\u4e89\u593a\u6218\u4e00\u89e6\u5373\u53d1.mp4: file already exists
