显示程序运行时间和显示当前时间日期的方法（time库）

In [1]:
import time
t0 = time.time()
print('显示程序开始的时间：',time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))

t1=time.time()
print('显示程序结束的时间：',time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))
print('用时：%.6fs'%(t1-t0))

显示程序开始的时间： 2020-12-13 20:07:44
显示程序结束的时间： 2020-12-13 20:07:44
用时：0.000997s


In [5]:
import time
t0 = time.time()
print('显示此刻的时间：',time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))

for i in range(0,1000):
    for j in range(0,1000):
        for k in range(0,1000):
            if((i+j)==2997):
                print(i,j,'\n')

t1 = time.time()
print('显示此刻的时间：',time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))
print('用时：%.5fs'%(t1-t0))

显示此刻的时间： 2020-12-13 20:21:11
显示此刻的时间： 2020-12-13 20:22:55
用时：103.19604s


创建数组并进行运算、创建一个国际象棋棋盘

In [7]:
import numpy as np
#1、创建一个数值范围为0~1，间隔为0.01的数组
arr1 = np.arange(0,1,0.01)
print('arange函数创建的数值范围为0~1间隔为0.01的数组arr1为：\n',arr1)
#2、创建由100个服从正太分布的随机数构成的数组
arr2 = np.random.randn(100)
print('生成的随机数组arr1为：\n',arr2)
#3、对创建的两个数组进行四则运算
print('arr1 + arr2: \n',arr1+arr2)
print('arr1 - arr2: \n',arr1-arr2)
print('arr1 * arr2: \n',arr1*arr2)
print('arr1 / arr2: \n',arr1/arr2)
#4、对创建的数组进行简单的统计分析
print('正太分布数数组的累计和为：\n',np.cumsum(arr2))#计算所有元素的累计和
print('正态分布数去重后的值组为：\n',np.unique(arr2))#去除重复值
print('正态分布数组的均值为：',np.mean(arr2))#计算数组均值
print('正态分布数组的标准差为:',np.std(arr2))#计算数组标准差
print('正态分布数组的方差为：',np.var(arr2))#计算数组方差
print('正态分布数组的最小值为:',np.min(arr2))#计算最小值
print('正态分布数组的最大值为：',np.max(arr2))#计算最大值
print('正态分布数组的总和为：',np.sum(arr2))#计算数组总和

arange函数创建的数值范围为0~1间隔为0.01的数组arr1为：
 [0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]
生成的随机数组arr1为：
 [-1.50750722e+00 -1.50058769e+00 -1.18633287e-01  6.72825699e-01
 -4.28332140e-01  3.08396434e-01 -9.72605594e-01 -3.30734677e-01
  6.67726023e-01 -1.31857785e+00 -2.43515968e-01  1.08750218e-01
  4.75239688e-01 -3.12452460e-01 -2.69429867e-01 -2.75947716e-02
  4.13529709e-01  2.25520605e+00  3.54489241e-01  9.65042496e-01
  3.75904832e-01  3.21315386e-01  1.64357891e+00  1.39316303e+00
  5.48018015e-01  6.52636797e-01  8.92598873e-02 

创建一个国际象棋的棋盘

In [9]:
import numpy as np
matr1=np.ones((8,8))
for i in range(8):
    for j in range(8):
        if(i+j)%2==0:
            matr1[i,j]=0
print('国际棋盘对应的矩阵为：\n',matr1)

for i in range(0,8):
    for j in range(0,8):
        if matr1[i,j]==0:
            print("□",end='   ')
        else:
            print("■", end='   ')
    print('\n')

国际棋盘对应的矩阵为：
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   

□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   

□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   

□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   



numpy-基础篇

In [9]:
import numpy as np
array = np.eye(4)
array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
#使用Python列表
a = [1,2,3,4]
b = [4,5,6,7,8]
out = []
for i,j in zip(a,b):
    out.append(i+j)
print(out)

#使用numpy
import numpy as np
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
print(a+b)

array


[5, 7, 9, 11]
[ 5  7  9 11]


array([ 5,  7,  9, 11])

In [14]:
#使用Python自带的数据类型
a = list(range(1000000))
%timeit sum(a)


#使用numpy
import numpy as np
a = list(range(1000000))
a_array = np.array(a)
%timeit np.sum(a_array)



39 ms ± 66.6 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
356 µs ± 5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [22]:
import numpy as np
a = np.array(['a','s','d','f'])
b = np.array([1,2,3,4])
c = np.array([4,5,6,7])
d = np.eye(4)

In [23]:
a[1]

's'

In [24]:
d[1,1]

1.0

In [25]:
a

array(['a', 's', 'd', 'f'], dtype='<U1')

In [26]:
d[:,2]

array([0., 0., 1., 0.])

In [28]:
d[2,3]=5

In [29]:
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 5.],
       [0., 0., 0., 1.]])

In [30]:
b+c

array([ 5,  7,  9, 11])

In [31]:
b-c

array([-3, -3, -3, -3])

In [32]:
b*c

array([ 4, 10, 18, 28])

In [34]:
array

array([ 5,  7,  9, 11])

In [35]:
b/c

array([0.25      , 0.4       , 0.5       , 0.57142857])

In [36]:
b**c

array([    1,    32,   729, 16384], dtype=int32)

In [37]:
a.shape

(4,)

In [38]:
d.shape

(4, 4)

In [39]:
a.ndim

1

In [40]:
d.ndim

2

In [41]:
a.dtype

dtype('<U1')

In [42]:
d.dtype

dtype('float64')

计算均值、方差、标准差 Numpy, Pandas

In [43]:
import numpy as np 
a = [5,6,16,9]
np.mean(a)

9.0

In [44]:
np.average(a)

9.0

In [46]:
np.average(a)

9.0

In [47]:
np.average(a,weights=[1,2,1,1])

8.4

In [49]:
a = [5,6,16,9]
np.var(a)

18.5

In [50]:
np.var(a, ddof =1)

24.666666666666668

In [51]:
b = [[4,5],[6,7]]
b

[[4, 5], [6, 7]]

In [52]:
np.var(b)

1.25

In [53]:
np.var(b,axis=0)

array([1., 1.])

In [54]:
np.var(b,axis=1)

array([0.25, 0.25])

Pandas 计算均值、方差、标准差

In [55]:
import pandas as pd
df = pd.DataFrame(np.array([[85, 68, 90], [82, 63, 88], [84, 90, 78]]), columns=['统计学', '高数', '英语'], index=['张三', '李四', '王五'])
df

统计学  高数  英语
张三   85  68  90
李四   82  63  88
王五   84  90  78

In [56]:
df.mean()

统计学    83.666667
高数     73.666667
英语     85.333333
dtype: float64

In [58]:
df.mean(axis=1)

张三    81.000000
李四    77.666667
王五    84.000000
dtype: float64

In [59]:
df

统计学  高数  英语
张三   85  68  90
李四   82  63  88
王五   84  90  78

In [60]:
df.iloc[0,:].mean()

81.0

In [61]:
df.iloc[:,2].mean()

85.33333333333333

In [62]:
df.var()

统计学      2.333333
高数     206.333333
英语      41.333333
dtype: float64

In [63]:
df.var(axis=1)

张三    133.000000
李四    170.333333
王五     36.000000
dtype: float64

In [64]:
df.std()

统计学     1.527525
高数     14.364308
英语      6.429101
dtype: float64

In [65]:
df.iloc[0,:].std()

11.532562594670797

In [66]:
df.iloc[:,2].std()

6.429100507328636

In [71]:
import numpy as np

n1 = np.array([1, 2, 3]) # 列表
n1


array([1, 2, 3])

In [72]:
n2 = np.array((4,5,6))
n2

array([4, 5, 6])

In [73]:
n3 = np.array(range(7,10))
n3

array([7, 8, 9])

np.arange(start, end, step)

start - 起始，不存在时，默认从0开始
end - 结束，不包括，实质上取到end-1
step - 步长


In [74]:
np.arange(10,13,1)

array([10, 11, 12])

In [76]:
np.arange(3.0) 

array([0., 1., 2.])

In [78]:
np.arange(True)

array([0])

In [79]:
np.arange(4+4j)

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j])

random模块-随机创建

In [81]:
n1 = np.random.randint(5, 15, size=(4, 4))
n1

array([[ 9, 14,  6,  7],
       [13, 12,  7, 13],
       [10,  9, 14, 10],
       [ 5,  6, 11,  6]])

In [2]:
import numpy as np

a = [1, 2, 3]
b = np.array(a, dtype=np.float_)
# 或者
b = np.array(a, dtype=float)

print(b)
print(b.dtype)
print(type(b[0]))


[1. 2. 3.]
float64
<class 'numpy.float64'>


In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array(a, copy=True)
a[0] = 0

print(a)
print(b)


[0 2 3]
[1 2 3]


In [4]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array(a, copy=False)
a[0] = 0

print(a)
print(b)


[0 2 3]
[0 2 3]


In [5]:
import numpy as np

a = [1, 2, 3]
b = np.array(a, ndmin=2)

print(b)


[[1 2 3]]


In [6]:
import numpy as np

a = np.matrix('1 2 7; 3 4 8; 5 6 9')
print(type(a))
print(a)
at = np.array(a, subok=True)
af = np.array(a, subok=False)
print(type(at))
print(type(af))


<class 'numpy.matrix'>
[[1 2 7]
 [3 4 8]
 [5 6 9]]
<class 'numpy.matrix'>
<class 'numpy.ndarray'>


In [1]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)


(2, 3)


In [2]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape = (3, 2)
print(a)


[[1 2]
 [3 4]
 [5 6]]


In [3]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.reshape(3, 2)
print(b)  # a 没变


[[1 2]
 [3 4]
 [5 6]]


In [4]:
import numpy as np

a = np.arange(24)
print(a.ndim)

# 现在调整其大小
b = a.reshape(2, 4, 3)
print(b.ndim)


1
3


In [5]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.flags)


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [6]:
import numpy as np

x = np.sqrt([1+0j, 0+1j])
print(x)
print(x.real)
print(x.real.dtype)


[1.        +0.j         0.70710678+0.70710678j]
[1.         0.70710678]
float64


In [7]:
print(np.inf)
print(np.NINF)
print(np.PZERO)
print(np.NZERO)
print(np.nan)
print(np.e)
print(np.pi)
print(np.euler_gamma)
print(np.newaxis)


inf
-inf
0.0
-0.0
nan
2.718281828459045
3.141592653589793
0.5772156649015329
None


In [8]:
import numpy as np

x = np.empty([3, 2], dtype=int)
print(x)


[[1 2]
 [3 4]
 [5 6]]


In [11]:
import numpy as np

x = np.zeros(5)
print(x)


[0. 0. 0. 0. 0.]


In [12]:
import numpy as np

a = np.full((2, 3), 9)
print(a)


[[9 9 9]
 [9 9 9]]


In [13]:
import numpy as np

a = np.arange(5)
b = np.arange(10, 20, 2)
print(a)
print(b)


[0 1 2 3 4]
[10 12 14 16 18]


In [14]:
import numpy as np

a = np.linspace(0, 5, 3, endpoint=False)
b = np.linspace(0, 5, 4, endpoint=True)

print(a)
print(b)


[0.         1.66666667 3.33333333]
[0.         1.66666667 3.33333333 5.        ]


In [17]:
import numpy as np

a = np.linspace(0, 10, 5, retstep=True)
print(a)


(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)


In [18]:
import numpy as np

a = np.logspace(1, 4, num=4)
print(a)


[   10.   100.  1000. 10000.]


In [19]:
import numpy as np

a = np.geomspace(1, 8, num=4)
print(a)

[1. 2. 4. 8.]


In [20]:
import numpy as np

a = np.asarray([1, 2, 3])
print(a)


[1 2 3]


In [21]:
import numpy as np

a = np.frombuffer(b'Hello World', dtype='S1')
print(a)


[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [22]:
import numpy as np
import array

a = array.array('i', [1, 2, 3, 4])
print(a)

na = np.frombuffer(a, dtype=np.int_)
print(na)

a[0] = 10
print(a)
print(na)


array('i', [1, 2, 3, 4])
[1 2 3 4]
array('i', [10, 2, 3, 4])
[10  2  3  4]


In [23]:
import numpy as np
import array

a = array.array("i", [1, 2, 3, 4])
na = np.frombuffer(a, dtype=int)
print(na)

a.append(5)
print(na)


[1 2 3 4]
[-535882272        653          3          4]


In [24]:
import numpy as np

iterable = (x * x for x in range(5))
a = np.fromiter(iterable, int)
print(a)


[ 0  1  4  9 16]


In [26]:
import numpy as np
a = np.empty_like([[1, 2, 3], [4, 5, 6]])
print(a)


[[-1431655765  1073392298 -1431655765]
 [ 1074440874           0  1075052544]]
