In [13]:
import numpy as np;
import pandas as pd

In [14]:
values=pd.Series(['apple','orange','apple','apple']*2)

In [15]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [16]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [17]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [18]:
values=pd.Series([0,1,0,0]*2)

In [19]:
dim=pd.Series(['apple','orange'])

In [20]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [21]:
dim

0     apple
1    orange
dtype: object

In [22]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [23]:
fruits=['apple','orange','apple','apple']*2

In [24]:
N=len(fruits)

In [26]:
df=pd.DataFrame({'fruits':fruits,'basket_id':np.arange(N),'count':np.random.randint(3,15,size=N),'weight':np.random.uniform(0,4,size=N)}
               ,columns=['basket_id','fruit','count','weight'])

In [27]:
df

basket_id fruit  count    weight
0          0   NaN     12  0.590036
1          1   NaN     10  0.182438
2          2   NaN      9  2.719241
3          3   NaN      7  2.116488
4          4   NaN      3  3.443238
5          5   NaN      4  0.097515
6          6   NaN     10  2.656940
7          7   NaN     12  0.084844

In [28]:
fruit_cat=df['fruit'].astype('category')

In [29]:
fruit_cat

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
Name: fruit, dtype: category
Categories (0, object): []

In [30]:
c=fruit_cat.values

In [31]:
type(c)

pandas.core.arrays.categorical.Categorical

In [33]:
pandas.core.categorical.Categorical

NameError: name 'pandas' is not defined

In [34]:
c.codes

array([-1, -1, -1, -1, -1, -1, -1, -1], dtype=int8)

In [35]:
df['fruit']=df['fruit'].astype('category')

In [36]:
df.fruit

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
Name: fruit, dtype: category
Categories (0, object): []

In [37]:
my_categorues=pd.Categorical(['foo','bar','baz','foo','bar'])

In [39]:
my_categorues

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [40]:
categories=['foo','bar','baz']

In [41]:
codes=[0,1,2,0,0,1]

In [42]:
my_cates_2=pd.Categorical.from_codes(codes,categories)

In [44]:
my_cates_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [45]:
ordered_cat=pd.Categorical.from_codes(codes,categories,ordered=True)

In [46]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [48]:
my_cates_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [49]:
np.random.seed(12345)

In [50]:
draws=np.random.randn(1000)

In [51]:
draws[:5]

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057])

In [52]:
bins=pd.qcut(draws,4)

In [53]:
bins

[(-0.684, -0.0101], (-0.0101, 0.63], (-0.684, -0.0101], (-0.684, -0.0101], (0.63, 3.928], ..., (-0.0101, 0.63], (-0.684, -0.0101], (-2.9499999999999997, -0.684], (-0.0101, 0.63], (0.63, 3.928]]
Length: 1000
Categories (4, interval[float64]): [(-2.9499999999999997, -0.684] < (-0.684, -0.0101] < (-0.0101, 0.63] < (0.63, 3.928]]

In [54]:
bins=pd.qcut(draws,4,labels=['q1','q2','q3','q4'])

In [55]:
bins

['q2', 'q3', 'q2', 'q2', 'q4', ..., 'q3', 'q2', 'q1', 'q3', 'q4']
Length: 1000
Categories (4, object): ['q1' < 'q2' < 'q3' < 'q4']

In [57]:
bins.codes[:]

array([1, 2, 1, 1, 3, 3, 2, 2, 3, 3, 3, 0, 2, 2, 3, 3, 0, 1, 3, 1, 1, 2,
       3, 0, 1, 2, 2, 2, 2, 3, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 1, 0, 0,
       0, 2, 2, 0, 2, 3, 2, 2, 1, 3, 3, 0, 0, 2, 3, 1, 3, 2, 2, 3, 3, 0,
       1, 0, 1, 0, 0, 3, 3, 3, 3, 1, 1, 0, 0, 2, 2, 0, 3, 2, 3, 3, 0, 3,
       1, 3, 2, 3, 1, 3, 2, 3, 2, 0, 2, 2, 0, 1, 1, 0, 1, 1, 3, 3, 1, 3,
       1, 2, 3, 0, 0, 1, 2, 1, 3, 0, 0, 0, 2, 3, 1, 1, 2, 1, 1, 1, 0, 0,
       3, 3, 2, 2, 3, 1, 1, 2, 0, 3, 2, 1, 2, 1, 1, 1, 3, 3, 0, 3, 1, 0,
       2, 0, 1, 3, 3, 1, 1, 1, 0, 3, 0, 3, 1, 3, 3, 3, 3, 1, 3, 0, 0, 1,
       0, 0, 2, 1, 1, 1, 0, 3, 3, 3, 0, 1, 1, 1, 0, 0, 3, 2, 3, 3, 0, 0,
       3, 2, 3, 1, 2, 1, 0, 0, 0, 1, 0, 1, 3, 2, 1, 3, 1, 3, 0, 2, 3, 1,
       1, 2, 0, 0, 2, 3, 3, 2, 1, 2, 0, 0, 0, 3, 1, 0, 0, 2, 2, 2, 0, 1,
       3, 1, 3, 0, 2, 1, 3, 1, 3, 0, 1, 0, 2, 0, 1, 1, 0, 2, 0, 3, 1, 3,
       0, 0, 1, 2, 1, 2, 2, 1, 0, 2, 2, 1, 0, 0, 1, 1, 1, 1, 2, 0, 3, 0,
       0, 3, 0, 2, 1, 2, 0, 2, 2, 1, 3, 3, 1, 3, 3,

In [58]:
bins=pd.Series(bins,name='quartile')

In [61]:
results=(pd.Series(draws)
         .groupby(bins)
         .agg(['count','min','max'])
               .reset_index())

In [62]:
results

quartile  count       min       max
0       q1    250 -2.949343 -0.685484
1       q2    250 -0.683066 -0.010115
2       q3    250 -0.010032  0.628894
3       q4    250  0.634238  3.927528

In [63]:
results['quartile']

0    q1
1    q2
2    q3
3    q4
Name: quartile, dtype: category
Categories (4, object): ['q1' < 'q2' < 'q3' < 'q4']

In [64]:
N=10000000

In [65]:
draws=pd.Series(np.random.randn(N))

In [66]:
labels=pd.Series(['foo','bar','baz','qux'])*(N//4)

In [67]:
categories=labels.astype('category')

In [68]:
labels.memory_usage()

160

In [69]:
categories.memory_usage()

324

In [70]:
%time_=labels.astype('category')

UsageError: Line magic function `%time_=labels.astype('category')` not found.


In [71]:
s=pd.Series(['a','b','c','d'])*2

In [72]:
cat_s=s.astype('category')

In [73]:
cat_s

0    aa
1    bb
2    cc
3    dd
dtype: category
Categories (4, object): ['aa', 'bb', 'cc', 'dd']

In [74]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
dtype: int8

In [75]:
cat_s.cat.categories

Index(['aa', 'bb', 'cc', 'dd'], dtype='object')

In [76]:
actual_categories=['a','b','c','d','e']

In [77]:
cat_s2=cat_s.cat.set_categories(actual_categories)

In [78]:
cat_s2

0    NaN
1    NaN
2    NaN
3    NaN
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [80]:
cat_s.value_counts()

dd    1
cc    1
bb    1
aa    1
dtype: int64

In [81]:
cat_s2.value_counts()

e    0
d    0
c    0
b    0
a    0
dtype: int64

In [82]:
cat_s3=cat_s[cat_s.isin(['a','b'])]

In [83]:
cat_s3

Series([], dtype: category
Categories (4, object): ['aa', 'bb', 'cc', 'dd'])

In [84]:
cat_s3.cat.remove_unused_categories()

Series([], dtype: category
Categories (0, object): [])

In [85]:
cat_s=pd.Series(['a','b','c','d']*2,dtype='category')

In [86]:
pd.get_dummies(cat_s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1

In [93]:
df=pd.DataFrame({'key':['a','b','c']*4,'value':np.arange(12.)})

In [94]:
df

key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [95]:
g=df.groupby('key').value

In [97]:
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [98]:
g.transform(lambda x:x.mean())

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [99]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [100]:
g.transform(lambda x:x*2)

0      0.0
1      2.0
2      4.0
3      6.0
4      8.0
5     10.0
6     12.0
7     14.0
8     16.0
9     18.0
10    20.0
11    22.0
Name: value, dtype: float64

In [108]:
g.transform(lambda x: x.rank(ascending=False))

0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0
Name: value, dtype: float64

In [110]:
def normalize(x):
    return(x-x.mean()/x.std())

In [111]:
g.transform(normalize)

0    -1.161895
1    -0.420094
2     0.321707
3     1.838105
4     2.579906
5     3.321707
6     4.838105
7     5.579906
8     6.321707
9     7.838105
10    8.579906
11    9.321707
Name: value, dtype: float64

In [112]:
g.apply(normalize)

0    -1.161895
1    -0.420094
2     0.321707
3     1.838105
4     2.579906
5     3.321707
6     4.838105
7     5.579906
8     6.321707
9     7.838105
10    8.579906
11    9.321707
Name: value, dtype: float64

In [113]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [114]:
normalized=(df['value']-g.transform('mean'))/g.transform('std')

In [115]:
normalized

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [116]:
N=15

In [117]:
times=pd.date_range('2017-05-20 00:00',freq='1min',periods=N)

In [120]:
df=pd.DataFrame({'time':times,'value':np.arange(N)})

In [121]:
DF

NameError: name 'DF' is not defined

In [122]:
df

time  value
0  2017-05-20 00:00:00      0
1  2017-05-20 00:01:00      1
2  2017-05-20 00:02:00      2
3  2017-05-20 00:03:00      3
4  2017-05-20 00:04:00      4
5  2017-05-20 00:05:00      5
6  2017-05-20 00:06:00      6
7  2017-05-20 00:07:00      7
8  2017-05-20 00:08:00      8
9  2017-05-20 00:09:00      9
10 2017-05-20 00:10:00     10
11 2017-05-20 00:11:00     11
12 2017-05-20 00:12:00     12
13 2017-05-20 00:13:00     13
14 2017-05-20 00:14:00     14

In [124]:
df.set_index('time').resample('5min').count()

value
time                      
2017-05-20 00:00:00      5
2017-05-20 00:05:00      5
2017-05-20 00:10:00      5

In [129]:
df2=pd.DataFrame({'time':times.repeat(3),'key':np.tile(['a','b','c'],N),'value':np.arange(N*3.)})

In [130]:
df2[:7]

time key  value
0 2017-05-20 00:00:00   a    0.0
1 2017-05-20 00:00:00   b    1.0
2 2017-05-20 00:00:00   c    2.0
3 2017-05-20 00:01:00   a    3.0
4 2017-05-20 00:01:00   b    4.0
5 2017-05-20 00:01:00   c    5.0
6 2017-05-20 00:02:00   a    6.0

In [131]:
time_key=pd.TimeGrouper('5min')

AttributeError: module 'pandas' has no attribute 'TimeGrouper'

In [132]:
resampled=(df2.set_index('time')
          .groupby(['key',time_key])
          .sum())

NameError: name 'time_key' is not defined

In [133]:
resampled

NameError: name 'resampled' is not defined

In [134]:
import pandas as pd 

In [135]:
import numpy as np

In [136]:
data=pd.DataFrame({'x0':[1,2,3,4,5],'x1':[0.01,-0.01,0.25,-4.1,0.],'y':[-1.5,0.,3.6,1.3,-2.]})

In [137]:
data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [138]:
data.columns

Index(['x0', 'x1', 'y'], dtype='object')

In [139]:
data.values

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

In [140]:
df2=pd.DataFrame(data.values,columns=['one','two','three'])

In [141]:
df2

one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.0

In [144]:
df3=data.copy()

In [145]:
df3['strings']=['a','b','c','d','e']

In [146]:
df3

x0    x1    y strings
0   1  0.01 -1.5       a
1   2 -0.01  0.0       b
2   3  0.25  3.6       c
3   4 -4.10  1.3       d
4   5  0.00 -2.0       e

df3.values

In [147]:
model_cols=['x0','x1']

In [149]:
data.loc[:,model_cols].values

array([[ 1.  ,  0.01],
       [ 2.  , -0.01],
       [ 3.  ,  0.25],
       [ 4.  , -4.1 ],
       [ 5.  ,  0.  ]])

In [7]:
import pandas as pd
frame=pd.DataFrame({'a':range(7),'b':range(7,0,-1),'c':['one','one','one','two','two','two','two'],'d':[0,1,2,0,1,2,3]})

In [5]:
import numpy as np
arr=np.array([[1.,2.,3.],[4.,5.,6.]])

In [8]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [9]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [10]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [12]:
arr*0.6

array([[0.6, 1.2, 1.8],
       [2.4, 3. , 3.6]])

In [13]:
arr2=np.array([[0.,4.,1.,],[7.,2.,12.]])

In [14]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [17]:
arr=np.arange(10)

In [16]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [18]:
array([0,1,2,3,4,5,6,7,8,9])

NameError: name 'array' is not defined

In [19]:
arr[5]

5

In [20]:
arr[5:8]

array([5, 6, 7])

In [21]:
arr[5:8]

array([5, 6, 7])

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr_slice=arr[5:8]

In [24]:
arr_slice

array([5, 6, 7])

In [25]:
arr_slice[1]

6

In [26]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr_slice[:]

array([5, 6, 7])

In [28]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [29]:
arr2d[2]

array([7, 8, 9])

In [30]:
arr2d[0][2]

3

In [31]:
arr3d=np.array([[1,2,3],[4,5,6],[[7,8,9],[10,11,12]]])

In [32]:
arr3d

array([list([1, 2, 3]), list([4, 5, 6]), list([[7, 8, 9], [10, 11, 12]])],
      dtype=object)

In [33]:
arr3d[0]

[1, 2, 3]

In [34]:
old_values=arr3d[0].copy

In [35]:
arr3d[0]

[1, 2, 3]

In [36]:
arr3d[0]=old_values

In [37]:
arr3d

array([<built-in method copy of list object at 0x000001EE6335D080>,
       list([4, 5, 6]), list([[7, 8, 9], [10, 11, 12]])], dtype=object)

In [42]:
x=arr3d[1]

In [43]:
x

[4, 5, 6]

In [44]:
x[0]

4

In [45]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [48]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [50]:
arr2d[1,:2]

array([4, 5])

In [51]:
arr2d[:2,2]

array([3, 6])

In [52]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [54]:
arr=np.arange(15).reshape((3,5))

In [55]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
arr=np.random.randn(6,3)

In [57]:
arr

array([[-1.27228332,  0.56336447, -1.66533071],
       [ 0.37224561, -0.4531448 ,  1.48174396],
       [-1.28236277,  0.63578389,  0.21071574],
       [ 1.49609908,  0.99601464, -0.62882542],
       [ 0.12018143, -0.02846402,  0.41982193],
       [-0.23090775,  0.20346398,  0.30715407]])

In [1]:
import random
if __name__ =="__main__":    #四位数字字母验证码的生成
    checkcode="" #保存验证码的变量
    for i in range(4):
        index=random.randrange(0,4)  #生成一个0~3中的数
        if index!=i and index +1 !=i:
            checkcode +=chr(random.randint(97,122))  # 生成a~z中的一个小写字母
        elif index +1==i:
            checkcode +=chr(random.randint(65,90) ) # 生成A~Z中的一个大写字母
        else:
            checkcode +=str(random.randint(1,9))  # 数字1-9
    print(checkcode)

o9sp


In [12]:
a=int(input('输入数字1:'))
b=int(input('输入数字2:'))
s=a*b
while a%b!=0:
    a,b=b,(a%b)
    print(a)
    print(b)
else:
    print(b,'is the maximum common divisor最大公约数')
    print(s//b,'is the least common multiple，最小公倍数')

输入数字1: 12
输入数字2: 34


34
12
12
10
10
2
2 is the maximum common divisor最大公约数
204 is the least common multiple，最小公倍数


In [ ]:
# 判断是否为闰年
while True:
    try:
        num=eval(input("请输入一个年份："))
    except:
        print('输入错误年份')
        continue
    if (num %4==0 and num%100 !=0) or num %400==0:
        print(num,"是闰年")
    else:
        print(num,"不是闰年")

请输入一个年份： 2019


2019 不是闰年


请输入一个年份： 1214


1214 不是闰年
输入错误年份


In [2]:
import re
str_test='abcdefgHABC123456中华民族'

#把正则表达式编译成对象,如果经常使用该对象,此种方式可提高一定效率
num_regex = re.compile(r'[0-9]')
zimu_regex = re.compile(r'[a-zA-z]')
hanzi_regex = re.compile(r'[\u4E00-\u9FA5]')

print('输入字符串:',str_test)
#findall获取字符串中所有匹配的字符
num_list = num_regex.findall(str_test)
print('包含的数字:',num_list)
zimu_list = zimu_regex.findall(str_test)
print('包含的字母:',zimu_list)
hanzi_list = hanzi_regex.findall(str_test)
print('包含的汉字:',hanzi_list)

输入字符串: abcdefgHABC123456中华民族
包含的数字: ['1', '2', '3', '4', '5', '6']
包含的字母: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'H', 'A', 'B', 'C']
包含的汉字: ['中', '华', '民', '族']


In [1]:
import random as r

#总次数
total=1000000 #1000,1W,10W,100W
#换与不换的获胜次数
win1=0
win2=0

for i in range(total):
    #模拟选择过程
    man=r.randint(1,3)
    car=r.randint(1,3)
    #结果：一开始为车门，不换+1.
    #       否则则一开始为羊门，换+1.
    if man==car:
        win1+=1
    else:
        win2+=1

print("在{}次实验中：".format(total))
print("若不更改门，获胜概率为{:.3}%.".format((win1/total)*100))
print("若更改门，获胜概率为{:.3}%.".format((win2/total)*100))

在1000000次实验中：
若不更改门，获胜概率为33.4%.
若更改门，获胜概率为66.6%.
