In [1]:
#for 循环

In [2]:
the_count=[1,2,3,4,5]
fruits=['apple','orange','pears','apricots']
change=[1,'pennies',2,'dimes',3,'quarters']

elements=[]

for i in range(0,6):
    print(f"adding {i} to the list.")
    elements.append(i)
    
for i in elements:
    print(f"element was:{i}")

adding 0 to the list.
adding 1 to the list.
adding 2 to the list.
adding 3 to the list.
adding 4 to the list.
adding 5 to the list.
element was:0
element was:1
element was:2
element was:3
element was:4
element was:5


In [ ]:
###错误和异常

In [4]:
import builtins
dir(builtins)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

In [5]:
name="ada lovelace"
print(name.title())

Ada Lovelace


In [6]:
# 大小写处理方法

In [7]:
name="ada loveplace"
print(name.upper())
print(name.lower())

ADA LOVEPLACE
ada loveplace


In [8]:
#合并字符串

In [9]:
first_name="ada"
last_name="loveplace"
full_name=first_name+" "+last_name

print(full_name)
print("hello,"+full_name.title()+"！")

ada loveplace
hello,Ada Loveplace！


In [10]:
# 使用制表符或者换行符来添加空白

In [11]:
print("language:\n\tpython\n\tC\n\tjava")

language:
	python
	C
	java


In [12]:
print("python")

python


In [13]:
print("\tpython")

	python


In [14]:
#删除空白

In [15]:
like='python '
like=like.rstrip()
#永久删除
like

'python'

In [16]:
like=' python '
like.rstrip()

' python'

In [17]:
like=' python '
like.lstrip()
like.strip()

'python'

In [18]:
famous_person="albert einstein"
a_secent='a person who never made a mistake never tried anything new.'
print(famous_person.title()+"once said,"+a_secent)

Albert Einsteinonce said,a person who never made a mistake never tried anything new.


In [19]:
#列表简介

In [20]:
bicycles=['trek','cannondale','redline','specialized']
print(bicycles)

['trek', 'cannondale', 'redline', 'specialized']


In [21]:
#访问列表元素
bicycles=['trek','cannondale','redline','specialized']
print(bicycles[0].title())
print(bicycles[2])
print(bicycles[-1])
#使用列表中的各个值
message="my first bicycle was a "+bicycles[0].title()+"."
print(message)

Trek
redline
specialized
my first bicycle was a Trek.


In [22]:
names=['wangdianni','zhongpeng','liuboyu','liudong']
print(names)

message="hai, my friend "+names[0]+"."
print(message)

['wangdianni', 'zhongpeng', 'liuboyu', 'liudong']
hai, my friend wangdianni.


In [23]:
#修改列表元素
names=['dianni','zp','lili','11']
names[0]='dn'
print(names)

['dn', 'zp', 'lili', '11']


In [24]:
#在列表中添加元素
names=['dianni','lili','zhongpeng','11']
names.append('wangchang')
print(names)

['dianni', 'lili', 'zhongpeng', '11', 'wangchang']


In [25]:
names=[]
names.append('dianni')
names.append('zhongpeng')
print(names)

['dianni', 'zhongpeng']


In [26]:
#在列表中插入元素
names=['dianni','lili','zhongpeng','11']
names.insert(0,'wangchang')
print(names)

['wangchang', 'dianni', 'lili', 'zhongpeng', '11']


In [27]:
#在列表中删除元素
names=['dianni','lili','zhongpeng','11']
del names[0]
print(names)
#使用del语句，你就无法再访问它了

['lili', 'zhongpeng', '11']


In [28]:
#使用方法pop删除元素，删除末尾的值，还可打印
names=['dianni','lili','zhongpeng','11']
popped_names=names.pop()
print(names)
print(popped_names)

['dianni', 'lili', 'zhongpeng']
11


In [30]:
#指出最后的人
names=['dianni','lili','zhongpeng','11']
last_bought=names.pop()
print("the laet people is "+ last_bought.title()+".")

the laet people is 11.


In [31]:
#弹出列表中任何位处的位置
names=['dianni','lili','zhongpeng','11']
last_bought=names.pop(1)
print(names)
#使用del 还是 pop 如果你从列表中删除一个元素，不会再以任何形式用它。del

['dianni', 'zhongpeng', '11']


In [32]:
#根据值删除元素
names=['dianni','lili','zhongpeng','11']
names.remove('lili')
print(names)

['dianni', 'zhongpeng', '11']


In [33]:
#从remove从列表中删除值时，也可接着使用其值
names=['dianni','lili','zhongpeng','11']
stupid='dianni'
names.remove(stupid)
print(names)
print("\nA")

['lili', 'zhongpeng', '11']

A


In [34]:
#组织列表
# 永久性排序
names=['dianni','lili','zhongpeng','eleven']
names.sort()
print(names)

['dianni', 'eleven', 'lili', 'zhongpeng']


In [35]:
names=['dianni','lili','zhongpeng','eleven']
names.sort(reverse=True)
print(names)

['zhongpeng', 'lili', 'eleven', 'dianni']


In [36]:
#临时排序
names=['dianni','lili','zhongpeng','eleven']
print("here is the original lists:")
print(names)

print("\nhere is the sorted list: ")
print(sorted(names))

print("\nhere is the original list again:")
print(names)

here is the original lists:
['dianni', 'lili', 'zhongpeng', 'eleven']

here is the sorted list: 
['dianni', 'eleven', 'lili', 'zhongpeng']

here is the original list again:
['dianni', 'lili', 'zhongpeng', 'eleven']


In [37]:
#倒着打印列表
names=['dianni','lili','zhongpeng','eleven']
names.reverse()
print(names)

['eleven', 'zhongpeng', 'lili', 'dianni']


In [38]:
#确定列表的长度
names=['dianni','lili','zhongpeng','eleven']
len(names)
# PYTHON 计算列表元素从1开始，不会遇到差1错误

4

In [39]:
#使用列表时避免错误引索错误

In [40]:
#操作列表
#遍历整个列表
names=['dianni','lili','zhongpeng','eleven']
for name in names:
    print(name)

dianni
lili
zhongpeng
eleven


In [41]:
names=['dianni','lili','zhongpeng','eleven']
for name in names:
    print(name.title()+" , you are so clever!")

Dianni , you are so clever!
Lili , you are so clever!
Zhongpeng , you are so clever!
Eleven , you are so clever!


In [42]:
#使用for循环的总结性句子要不要缩进
names=['dianni','lili','zhongpeng','eleven']
for name in names:
    print(name.title()+" , you are so clever!")
    print("fighting!"+name.title())

print("\n加油加油，毕业不愁")

Dianni , you are so clever!
fighting!Dianni
Lili , you are so clever!
fighting!Lili
Zhongpeng , you are so clever!
fighting!Zhongpeng
Eleven , you are so clever!
fighting!Eleven

加油加油，毕业不愁


In [43]:
#创建数值列表
#使用rang()函数
for value in range(1,5):
    print(value)
#在达到你指定的第二个数停止

1
2
3
4


In [44]:
#使用range 创建数字列表
numbers=list(range(1,6))
print(numbers)

[1, 2, 3, 4, 5]


In [45]:
#指定步长
even_numbers=list(range(2,11,2))
print(even_numbers)

[2, 4, 6, 8, 10]


In [46]:
squares=[]
for value in range(1,11):
    square=value**2
    squares.append(square)
    
    print(squares)

[1]
[1, 4]
[1, 4, 9]
[1, 4, 9, 16]
[1, 4, 9, 16, 25]
[1, 4, 9, 16, 25, 36]
[1, 4, 9, 16, 25, 36, 49]
[1, 4, 9, 16, 25, 36, 49, 64]
[1, 4, 9, 16, 25, 36, 49, 64, 81]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [47]:
squares=[]
for value in range(1,11):
    squares.append(value**2)
    
    print(squares)

[1]
[1, 4]
[1, 4, 9]
[1, 4, 9, 16]
[1, 4, 9, 16, 25]
[1, 4, 9, 16, 25, 36]
[1, 4, 9, 16, 25, 36, 49]
[1, 4, 9, 16, 25, 36, 49, 64]
[1, 4, 9, 16, 25, 36, 49, 64, 81]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [50]:
#列表解析
#将for循环和创建新元素的代码合并成一行，并自动附加新元素
squares=[value**2 for value in range(1,11)]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [51]:
numbers=[]
for value in range(1,21):
    print(value)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [52]:
numbers=[]
for value in range(1,21,2):
    print(value)
#奇数

1
3
5
7
9
11
13
15
17
19


In [53]:
#3的倍数
numbers=[]
for value in range(3,31,3):
    print(value)

3
6
9
12
15
18
21
24
27
30


In [54]:
#立方
squares=[]
for value in range(1,11):
    squares.append(value*2**3)
    
    print(squares)

[8]
[8, 16]
[8, 16, 24]
[8, 16, 24, 32]
[8, 16, 24, 32, 40]
[8, 16, 24, 32, 40, 48]
[8, 16, 24, 32, 40, 48, 56]
[8, 16, 24, 32, 40, 48, 56, 64]
[8, 16, 24, 32, 40, 48, 56, 64, 72]
[8, 16, 24, 32, 40, 48, 56, 64, 72, 80]


In [55]:
#使用列表的一部分 切片
names=['dianni','lili','zhongpeng','eleven']
print(names[:3])

['dianni', 'lili', 'zhongpeng']


In [56]:
#遍历切片
names=['dianni','lili','zhongpeng','eleven']

print("they are my friends:")
for name in names[1:4]:
    print(name.title())

they are my friends:
Lili
Zhongpeng
Eleven


In [57]:
#复制列表
names=['dianni','lili','zhongpeng','eleven']
team_names=names[:]

print("the team members are: ")
print(team_names)

the team members are: 
['dianni', 'lili', 'zhongpeng', 'eleven']


In [58]:
my_foods=['pizza','apple','water']
friend_foods=my_foods[:]
my_foods.append('ice cream')
friend_foods.append('cola')

print("my favorite foods are:")
print(my_foods)

print("\nmy friend favorite foods are:")
print(friend_foods)

my favorite foods are:
['pizza', 'apple', 'water', 'ice cream']

my friend favorite foods are:
['pizza', 'apple', 'water', 'cola']


In [59]:
#元组——不可变的列表
#定义元组
dimensions=(200,50)
print(dimensions[0])
print(dimensions[1])
#试图修改元组的行为是被禁止的

200
50


In [61]:
#遍历元组中的所有值
dimensions=(100,50)
for dimension in dimensions:
    print(dimension)

100
50


In [62]:
#修改元组变量 重新定义整个元组
dimensions=(200,50)
print("original dimensions:")
for dimension in dimensions:
    print(dimension)
    
dimensions=(400,100)
print("\nmodified dimensions:")
for dimension in dimensions:
    print(dimension)
#如果要存储的一组值在程序的整个生命周期内不变，可使用元组

original dimensions:
200
50

modified dimensions:
400
100


In [63]:
def Chung:
    print('JINTIANDUOCHIDIAN')

SyntaxError: invalid syntax (<ipython-input-63-3fb2fd93882f>, line 1)

In [64]:
active=True
sites=[]
while active:
    site=input("如果你可以去世界的任何一个地方，你想去哪里？")
    sites.append(site)
    over=input("是否结束？Yes/No")
    if over=="Yes":
        active=False
print(sites)

如果你可以去世界的任何一个地方，你想去哪里？ japan
是否结束？Yes/No yes
如果你可以去世界的任何一个地方，你想去哪里？ japan 
是否结束？Yes/No no
如果你可以去世界的任何一个地方，你想去哪里？ yes 
是否结束？Yes/No yes
如果你可以去世界的任何一个地方，你想去哪里？ YES
是否结束？Yes/No Yes


['japan', 'japan ', 'yes ', 'YES']


In [65]:
def name(first_name,last_name,middle_name=''):
    if middle_name:
        full_name=first_name+' '+middle_name+' '+last_name
    else:
        full_name=first_name+' '+last_name
    return full_name.title()
musician=name('jimi','hendrix')
print(musician)
musician=name('john','lee','hooker')
print(musician)

Jimi Hendrix
John Hooker Lee


In [66]:
def name(first_name,last_name,middle_name):
    if middle_name:
        full_name=first_name+' '+middle_name+' '+last_name
    else:
        full_name=first_name+' '+last_name
    return full_name.title()
while True:
    print("\n请告诉我你的名字")
    print("输入q结束")
    print("如果没有中间名字，请输入空格")
    f_name=input("First_name:")
    l_name=input("Last_name:")
    m_name=input("Middle_name:")
    if f_name=='q':
        break
    if l_name=='q':
        break
    if m_name=='q':
        break
    musician=name(f_name,l_name,m_name)
    print(musician)


请告诉我你的名字
输入q结束
如果没有中间名字，请输入空格


First_name: winter
Last_name: leo
Middle_name: o


Winter O Leo

请告诉我你的名字
输入q结束
如果没有中间名字，请输入空格


First_name:  
Last_name:  
Middle_name:  


     

请告诉我你的名字
输入q结束
如果没有中间名字，请输入空格


First_name: 
Last_name: 
Middle_name: 


 

请告诉我你的名字
输入q结束
如果没有中间名字，请输入空格


First_name: 
Last_name: q
Middle_name: 


In [67]:
import time
t0 = time.time()
print('显示程序开始的时间：',time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))

t1=time.time()
print('显示程序结束的时间：',time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))
print('用时：%.6fs'%(t1-t0))

显示程序开始的时间： 2020-12-16 23:57:58
显示程序结束的时间： 2020-12-16 23:57:58
用时：0.000000s


In [68]:
import numpy as np
#1、创建一个数值范围为0~1，间隔为0.01的数组
arr1 = np.arange(0,1,0.01)
print('arange函数创建的数值范围为0~1间隔为0.01的数组arr1为：\n',arr1)
#2、创建由100个服从正太分布的随机数构成的数组
arr2 = np.random.randn(100)
print('生成的随机数组arr1为：\n',arr2)
#3、对创建的两个数组进行四则运算
print('arr1 + arr2: \n',arr1+arr2)
print('arr1 - arr2: \n',arr1-arr2)
print('arr1 * arr2: \n',arr1*arr2)
print('arr1 / arr2: \n',arr1/arr2)
#4、对创建的数组进行简单的统计分析
print('正太分布数数组的累计和为：\n',np.cumsum(arr2))#计算所有元素的累计和
print('正态分布数去重后的值组为：\n',np.unique(arr2))#去除重复值
print('正态分布数组的均值为：',np.mean(arr2))#计算数组均值
print('正态分布数组的标准差为:',np.std(arr2))#计算数组标准差
print('正态分布数组的方差为：',np.var(arr2))#计算数组方差
print('正态分布数组的最小值为:',np.min(arr2))#计算最小值
print('正态分布数组的最大值为：',np.max(arr2))#计算最大值
print('正态分布数组的总和为：',np.sum(arr2))#计算数组总和

arange函数创建的数值范围为0~1间隔为0.01的数组arr1为：
 [0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]
生成的随机数组arr1为：
 [-0.14402412  1.49115021 -1.00499915 -0.67760131  0.09675588  0.0065615
  0.42213701 -1.56951484 -1.80574794  0.28876047  0.85371738  0.67891216
  2.5215546   0.14281919  0.32490141 -1.34351555  0.30534578  0.5932597
 -0.71594519 -2.14279133 -0.28016807  1.92299437  0.36759223 -0.2594509
 -0.62091659  0.39764034  0.00479573  0.76442457 -0.93397441 -0.06879156
  0.26926445 -1.0839305  -0.18205519 -1.29541504  0.16879471  0.91766757
 -0.

In [69]:
import numpy as np
matr1=np.ones((8,8))
for i in range(8):
    for j in range(8):
        if(i+j)%2==0:
            matr1[i,j]=0
print('国际棋盘对应的矩阵为：\n',matr1)

for i in range(0,8):
    for j in range(0,8):
        if matr1[i,j]==0:
            print("□",end='   ')
        else:
            print("■", end='   ')
    print('\n')

国际棋盘对应的矩阵为：
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   

□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   

□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   

□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   



In [70]:
import pandas as pd
df = pd.DataFrame(np.array([[85, 68, 90], [82, 63, 88], [84, 90, 78]]), columns=['统计学', '高数', '英语'], index=['张三', '李四', '王五'])
df

统计学  高数  英语
张三   85  68  90
李四   82  63  88
王五   84  90  78

In [71]:
import numpy as np

a = [1, 2, 3]
b = np.array(a, dtype=np.float_)
# 或者
b = np.array(a, dtype=float)

print(b)
print(b.dtype)
print(type(b[0]))

[1. 2. 3.]
float64
<class 'numpy.float64'>


In [72]:
import numpy as np
import array

a = array.array('i', [1, 2, 3, 4])
print(a)

na = np.frombuffer(a, dtype=np.int_)
print(na)

a[0] = 10
print(a)
print(na)

array('i', [1, 2, 3, 4])
[1 2 3 4]
array('i', [10, 2, 3, 4])
[10  2  3  4]


In [74]:
# GRADED FUNCTION: initialize_parameters

def initialize_parameters(n_x, n_h, n_y):
    """
    Argument:
    n_x -- size of the input layer
    n_h -- size of the hidden layer
    n_y -- size of the output layer
    
    Returns:
    parameters -- python dictionary containing your parameters:
                    W1 -- weight matrix of shape (n_h, n_x)
                    b1 -- bias vector of shape (n_h, 1)
                    W2 -- weight matrix of shape (n_y, n_h)
                    b2 -- bias vector of shape (n_y, 1)
    """
    
    np.random.seed(1)
    
    ### START CODE HERE ### (≈ 4 lines of code)
    W1 = np.random.randn(n_h, n_x)*0.01
    b1 = np.zeros((n_h, 1))
    W2 = np.random.randn(n_y, n_h)*0.01
    b2 = np.zeros((n_y, 1))
    ### END CODE HERE ###
    
    assert(W1.shape == (n_h, n_x))
    assert(b1.shape == (n_h, 1))
    assert(W2.shape == (n_y, n_h))
    assert(b2.shape == (n_y, 1))
    
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [75]:
parameters = initialize_parameters(2,2,1)
print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))

W1 = [[ 0.01624345 -0.00611756]
 [-0.00528172 -0.01072969]]
b1 = [[0.]
 [0.]]
W2 = [[ 0.00865408 -0.02301539]]
b2 = [[0.]]


In [76]:
# GRADED FUNCTION: initialize_parameters_deep

def initialize_parameters_deep(layer_dims):
    """
    Arguments:
    layer_dims -- python array (list) containing the dimensions of each layer in our network
    
    Returns:
    parameters -- python dictionary containing your parameters "W1", "b1", ..., "WL", "bL":
                    Wl -- weight matrix of shape (layer_dims[l], layer_dims[l-1])
                    bl -- bias vector of shape (layer_dims[l], 1)
    """
    
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)            # number of layers in the network

    for l in range(1, L):
        ### START CODE HERE ### (≈ 2 lines of code)
        parameters['W' + str(l)] = np.random.randn(layer_dims[l],layer_dims[l-1])*0.01
        parameters['b' + str(l)] = np.zeros((layer_dims[l],1))
        ### END CODE HERE ###
        
        assert(parameters['W' + str(l)].shape == (layer_dims[l], layer_dims[l-1]))
        assert(parameters['b' + str(l)].shape == (layer_dims[l], 1))

        
    return parameters

In [77]:
parameters = initialize_parameters_deep([5,4,3])
print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))

W1 = [[ 0.01788628  0.0043651   0.00096497 -0.01863493 -0.00277388]
 [-0.00354759 -0.00082741 -0.00627001 -0.00043818 -0.00477218]
 [-0.01313865  0.00884622  0.00881318  0.01709573  0.00050034]
 [-0.00404677 -0.0054536  -0.01546477  0.00982367 -0.01101068]]
b1 = [[0.]
 [0.]
 [0.]
 [0.]]
W2 = [[-0.01185047 -0.0020565   0.01486148  0.00236716]
 [-0.01023785 -0.00712993  0.00625245 -0.00160513]
 [-0.00768836 -0.00230031  0.00745056  0.01976111]]
b2 = [[0.]
 [0.]
 [0.]]


In [78]:
# GRADED FUNCTION: linear_forward

def linear_forward(A, W, b):
    """
    Implement the linear part of a layer's forward propagation.

    Arguments:
    A -- activations from previous layer (or input data): (size of previous layer, number of examples)
    W -- weights matrix: numpy array of shape (size of current layer, size of previous layer)
    b -- bias vector, numpy array of shape (size of the current layer, 1)

    Returns:
    Z -- the input of the activation function, also called pre-activation parameter 
    cache -- a python dictionary containing "A", "W" and "b" ; stored for computing the backward pass efficiently
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    Z = np.dot(W,A)+b
    ### END CODE HERE ###
    
    assert(Z.shape == (W.shape[0], A.shape[1]))
    cache = (A, W, b)
    
    return Z, cache

In [81]:
A, W, b = linear_forward_test_case()
Z, linear_cache = linear_forward(A, W, b)
print("Z = + str(Z))

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (<ipython-input-81-77d286e6afd4>, line 3)