# You- get 

In [5]:
$ pip3 install you-get  # 要在powershell中先安装好，在jupyter中调用

SyntaxError: invalid syntax (<ipython-input-5-476e0408b103>, line 1)

In [8]:
%%cmd
you-get https://www.bilibili.com/video/BV1FV411d7u7

Microsoft Windows [版本 10.0.18363.1256]
(c) 2019 Microsoft Corporation。保留所有权利。

D:\交大研究生课程\Python\04>you-get https://www.bilibili.com/video/BV1FV411d7u7
site:                Bilibili
title:               bilibili鐚�缁欐柊涓�浠ｇ殑婕旇�层�婂悗娴�銆� (P1. bilibili鐚�缁欐柊涓�浠ｇ殑婕旇�层�婂悗娴�銆�)
stream:
    - format:        flv
      container:     flv
      quality:       楂樻竻 1080P
      size:          50.0 MiB (52415560 bytes)
    # download-with: you-get --format=flv [URL]




D:\交大研究生课程\Python\04>

you-get: This is a multipart video. (use --playlist to download all parts.)
you-get: Skipping .\bilibili献给新一代的演讲《后浪》 (P1. bilibili献给新一代的演讲《后浪》).flv: file already exists


In [9]:
%%cmd
you-get https://www.bilibili.com/video/BV1FV411d7u7

Microsoft Windows [版本 10.0.18363.1256]
(c) 2019 Microsoft Corporation。保留所有权利。

D:\交大研究生课程\Python\04>you-get https://www.bilibili.com/video/BV1FV411d7u7
site:                Bilibili
title:               bilibili鐚�缁欐柊涓�浠ｇ殑婕旇�层�婂悗娴�銆� (P1. bilibili鐚�缁欐柊涓�浠ｇ殑婕旇�层�婂悗娴�銆�)
stream:
    - format:        flv
      container:     flv
      quality:       楂樻竻 1080P
      size:          50.0 MiB (52415560 bytes)
    # download-with: you-get --format=flv [URL]




D:\交大研究生课程\Python\04>

you-get: This is a multipart video. (use --playlist to download all parts.)
you-get: Skipping .\bilibili献给新一代的演讲《后浪》 (P1. bilibili献给新一代的演讲《后浪》).flv: file already exists


# Altair 

In [12]:
import altair as alt
from vega_datasets import data

source = alt.topo_feature(data.world_110m.url, 'countries')

base = alt.Chart(source).mark_geoshape(
    fill='#666666',
    stroke='white'
).properties(
    width=300,
    height=180
)

projections = ['equirectangular', 'mercator', 'orthographic', 'gnomonic']
charts = [base.project(proj).properties(title=proj)
          for proj in projections]

alt.concat(*charts, columns=2)

alt.ConcatChart(...)

In [13]:
import altair as alt
from vega_datasets import data

source = alt.topo_feature(data.world_110m.url, 'countries')

base = alt.Chart(source).mark_geoshape(
    fill='#666666',
    stroke='white'
).properties(
    width=300,
    height=180
)

projections = ['equirectangular', 'mercator', 'orthographic', 'gnomonic']
charts = [base.project(proj).properties(title=proj)
          for proj in projections]

alt.concat(*charts, columns=2)

alt.ConcatChart(...)

In [14]:
import altair as alt
from vega_datasets import data

source = data.cars()

alt.Chart(source).mark_circle(size=60).encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
    tooltip=['Name', 'Origin', 'Horsepower', 'Miles_per_Gallon']
).interactive()

alt.Chart(...)

# pyecharts  

In [18]:
from pyecharts.globals import CurrentConfig, NotebookType
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB

from pyecharts.charts import Bar
from pyecharts import options as opts
from pyecharts.globals import ThemeType

bar = (
    Bar(init_opts=opts.InitOpts(theme=ThemeType.LIGHT))
    .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
    .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
    .add_yaxis("商家B", [15, 6, 45, 20, 35, 66])
    .set_global_opts(title_opts=opts.TitleOpts(title="主标题", subtitle="副标题"))
)
bar.load_javascript()
bar.render_notebook()

# Face Recognition

In [16]:
import face_recognition  
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
import numpy as np

ModuleNotFoundError: No module named 'face_recognition'

In [22]:
import pandas as pd
import jieba

In [24]:

pd.set_option('display.max_columns', None) #显示所有列
pd.set_option('display.max_rows', None) #显示所有行
pd.set_option('max_colwidth', 100) # 设置value的显示长度为100，默认为50
    
tweets = pd.read_csv('D:\交大研究生课程\Python\04\04\weibo_hashtag\weibo\#进击的巨人最终季#.csv', usecols=['正文'])
tweets['jieba分词'] = tweets.apply(lambda x: ';'.join(jieba.cut(x['正文'])), axis=1)
tweets

FileNotFoundError: [Errno 2] File D:\交大研究生课程\Python\weibo_hashtag\weibo\#进击的巨人最终季#.csv does not exist: 'D:\\交大研究生课程\\Python\x04\x04\\weibo_hashtag\\weibo\\#进击的巨人最终季#.csv'

In [1]:
from pyecharts.globals import CurrentConfig, NotebookType
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB

from pyecharts.charts import Bar
from pyecharts import options as opts
from pyecharts.globals import ThemeType

bar = (
    Bar(init_opts=opts.InitOpts(theme=ThemeType.LIGHT))
    .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
    .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
    .add_yaxis("商家B", [15, 6, 45, 20, 35, 66])
    .set_global_opts(title_opts=opts.TitleOpts(title="主标题", subtitle="副标题"))
)
bar.load_javascript()
bar.render_notebook()

In [3]:
import pandas as pd
import jieba

pd.set_option('display.max_columns', None)

pd.set_option('display.max_rows', None)

pd.set_option('max_colwidth', 100)
    
tweets = pd.read_csv("D:\交大研究生课程\Python\04\04\weibo_hashtag\weibo\#进击的巨人最终季#.csv", usecols=['正文'])
tweets['jieba分词'] = tweets.apply(lambda x: ';'.join(jieba.cut(x['正文'])), axis=1)
tweets

FileNotFoundError: [Errno 2] File D:\交大研究生课程\Python\weibo_hashtag\weibo\#进击的巨人最终季#.csv does not exist: 'D:\\交大研究生课程\\Python\x04\x04\\weibo_hashtag\\weibo\\#进击的巨人最终季#.csv'

# SnowNLP 

In [4]:
import pandas as pd 
from snownpl import SnowNLP # snownlp 打错了

ModuleNotFoundError: No module named 'snownpl'

In [6]:
import pandas as pd 
from snownlp import SnowNLP 

In [7]:
pd.set_option('display.max_columns', None)# 显示所有列
pd.set_option('display.max_rows', None)# 显示所有行
pd.set_option('max_colwidth', 100) # 设置value的显示长度为100，默认为50
    
tweets = pd.read_csv('weibo_hashtag/weibo/#进击的巨人最终季#/#进击的巨人最终季#.csv', usecols=['正文'])
tweets['snownlp分词'] = tweets.apply(lambda x: ';'.join(SnowNLP(x['正文']).words), axis=1)
tweets['情感分数'] = tweets.apply(lambda x: SnowNLP(x['正文']).sentiments, axis=1)
tweets

FileNotFoundError: [Errno 2] File weibo_hashtag/weibo/#进击的巨人最终季#/#进击的巨人最终季#.csv does not exist: 'weibo_hashtag/weibo/#进击的巨人最终季#/#进击的巨人最终季#.csv'

# word_cloud

In [9]:
import jieba 
from wordcloud import WordCloud
import matplotlib.pyplot as plt 
import numpy as np 
from PIL import Image 

#读取Text文本
data = open ("文档.txt","r",encoding = "utf-8").read()
#将文本以词语分方式分割，分割后赋值给word
#ut_all = True 是全模式  cut_all = False 是精确模式  默认是精确模式 
cutData = jieba.cut(data,cut_all=False)
# 以空格分开词语
word = "".jion(cutData)

#背景图
mask = np.array(Image.open("masking.png"))

OSError: [Errno 22] Invalid argument: 'D:\\交大研究生课程\\Python\x04\\词云.txt'

In [ ]:
plt.imshow(wc,interpolation="bilinear") # 显示图片
plt.axis("off")
plt.show()

###  我太难过了，做的这是啥呀

In [ ]:
wc.to_file("cloud_img.png") # 保存图片

In [10]:
name=input("Please enter your name:")
print("This is my name.")

Please enter your name:小黑
This is my name.


In [12]:
name=input("Please enter your name")
print("hello,"+name+"!")

Please enter your namexiaohei
hello,xiaohei!


In [13]:
#多行
message="这是一个注册表"
message+="\n请告诉我你的名字"
name= input(message)
print("Hello,"+name+"!")

这是一个注册表
请告诉我你的名字xioahei
Hello,xioahei!


In [14]:
age=input("How old are you?")
age=int(age)
print(age)

How old are you?18
18


In [15]:
age=input("How old are you?")
print(age)


How old are you?18
18


In [16]:
age=input("How old are you?")
age=int(age)
print(age)
if age>18:
    print("you are so young!")
else:
    print("you are so cute!")
    

How old are you?20
20
you are so young!


In [17]:
age=input("你多大了")
age=int(age)
print(age)
if age>18:
    print("you are so young!")
else:
    print("you are so cute!")

你多大了20
20
you are so young!


In [18]:
number=input("你最喜欢的数字")
number=int(number)

你最喜欢的数字9


In [19]:
number=input("你最喜欢的数字")

你最喜欢的数字9


In [20]:
number=input("你最喜欢的数字")
number=int(number)
if number%2==0:
    print("这是一个偶数")
else:
    print("这是一个奇数")

你最喜欢的数字9
这是一个奇数


In [22]:
number=input("你最喜欢的数字")
number=int(number)
if number%2==0:
    print("这是一个偶数")
else:
    print("这是一个奇数")

你最喜欢的数字10
这是一个偶数


In [26]:
person=input("你有几个兄弟姐妹")
person=int(person)
if person > 1:
    print("你好幸福呀，有人陪你玩耍哦")
else:
    print("你会不会孤单呀")

你有几个兄弟姐妹2
你好幸福呀，有人陪你玩耍哦


In [27]:
person=input("你有几个兄弟姐妹")
person=int(person)
if person > 1:
    print("你好幸福呀，有人陪你玩耍哦")
else:
    print("你会不会孤单呀")

你有几个兄弟姐妹0
你会不会孤单呀


In [28]:
current_number=1
while current_number<=5:
    print(current_number)
    current_number+=1

1
2
3
4
5


In [29]:
message=""
while message!="quit":
    message=input("请输入？")
    if message !="quite":
        print(message)

请输入？go on 
go on 
请输入？no
no
请输入？quit
quit


In [33]:
message=[]
active=True
while active:
    message = input("请输入配料表？")
    if message=="quit":
        active=False
    else:
        message.append(message)
print("配料表："+str(message))

请输入配料表？quit
配料表：quit


In [37]:
age=""
while age!="":
    age=input("\n请输入你的年龄")
    if age！="":
        age=int(age)
        if age<3:
            price=0
        elif age<12:
            price=10
    else:
        break
print(price)

SyntaxError: invalid character in identifier (<ipython-input-37-c585dd61b68b>, line 4)

In [38]:
sandwich_orders=['vegetable','chicken','fish','beef']
finished_sandwiches=[]
while sandwich_orders:
    current_sandwich=sandwich_orders.pop()
    print("\nI made your "+current_sandwich+" sandwich!")
    finished_sandwiches.append(current_sandwich)
print("\n做好的三明治："+str(finished_sandwiches))


I made your beef sandwich!

I made your fish sandwich!

I made your chicken sandwich!

I made your vegetable sandwich!

做好的三明治：['beef', 'fish', 'chicken', 'vegetable']


In [39]:
num1 = input('输入第一个数字：')
num2 = input('输入第二个数字：')
sum = float(num1) + float(num2)
print('数字 {0} 和 {1} 相加结果为： {2}'.format(num1, num2, sum))

输入第一个数字：3
输入第二个数字：4
数字 3 和 4 相加结果为： 7.0


In [40]:
num = float(input('请输入一个数字： '))
num_sqrt = num ** 0.5
num1 = num**2
print(num1)
print(' %0.3f 的平方根为 %0.3f'%(num ,num_sqrt))

请输入一个数字： 3
9.0
 3.000 的平方根为 1.732


In [41]:
import random
 
print(random.randint(0,9))

5


In [42]:
x = input('输入 x 值: ')
y = input('输入 y 值: ')
temp = x
x = y
y = temp
 
print('交换后 x 的值为: {}'.format(x))
print('交换后 y 的值为: {}'.format(y))

输入 x 值: 5
输入 y 值: 7
交换后 x 的值为: 7
交换后 y 的值为: 5


In [43]:
x = int(input('输入 X 值：'))
y = int(input('输入 Y 值：'))
x = x ^ y
y = x ^ y
x = x ^ y
print('交换后的 X 值为：',x)
print('交换后的 Y 值为：',y)

输入 X 值：4
输入 Y 值：6
交换后的 X 值为： 6
交换后的 Y 值为： 4


In [44]:
num = float(input("输入一个数字: "))
if num > 0:
   print("正数")
elif num == 0:
   print("零")
else:
   print("负数")

输入一个数字: 9
正数


In [45]:
while True:
    try:
        num=float(input('请输入一个数字：'))
        if num==0:
            print('输入的数字是零')
        elif num>0:
            print('输入的数字是正数')
        else:
            print('输入的数字是负数')
        break
    except ValueError:
        print('输入无效，需要输入一个数字')

请输入一个数字：5
输入的数字是正数


In [46]:
while True:
    try:
        num=float(input('请输入一个数字：'))
        if num==0:
            print('输入的数字是零')
        elif num>0:
            print('输入的数字是正数')
        else:
            print('输入的数字是负数')
        break
    except ValueError:
        print('输入无效，需要输入一个数字')

请输入一个数字："你好"
输入无效，需要输入一个数字
请输入一个数字：0
输入的数字是零


In [47]:
num = int(input("输入一个数字: "))
if (num % 2) == 0:
   print("{0} 是偶数".format(num))
else:
   print("{0} 是奇数".format(num))

输入一个数字: 9
9 是奇数


In [48]:
year = int(input("请输入一个年份："))
if (year % 4) == 0 and (year % 100) != 0 or (year % 400) == 0:
    print("{0}是闰年".format(year))
else:
    print("{0}不是闰年".format(year))

请输入一个年份：1996
1996是闰年


In [49]:
print(max(1, 2))
print(max('a', 'b'))

print(max([1,2]))
print(max((1,2)))

print("80, 100, 1000 最大值为: ", max(80, 100, 1000))
print("-20, 100, 400最大值为: ", max(-20, 100, 400))
print("-80, -20, -10最大值为: ", max(-80, -20, -10))
print("0, 100, -400最大值为:", max(0, 100, -400))

2
b
2
2
80, 100, 1000 最大值为:  1000
-20, 100, 400最大值为:  400
-80, -20, -10最大值为:  -10
0, 100, -400最大值为: 100


In [50]:
message=""
while message!='quit':
    message=input("请输入？")
    print(message)
    

请输入？4
4
请输入？o
o
请输入？吹过你的风也吹着我
吹过你的风也吹着我
请输入？quit
quit


In [52]:
age=""
while age!="*":
    age=input("\n请输入你的年龄")
    age=int(age)
    if age<3 and age>0:
        price=0
    elif age<12 and age>=3:
        price=10
    else:
        price=15
print(price)


请输入你的年龄2


KeyboardInterrupt: Interrupted by user

In [53]:
pets=['dog','cat','dog','cat','goldfish','rabbit']
print(pets)
while 'dog' in pets:
    pets.remove('dog')
print(pets)

['dog', 'cat', 'dog', 'cat', 'goldfish', 'rabbit']
['cat', 'cat', 'goldfish', 'rabbit']


In [54]:
age=""
while age!="*":
    age=input("\n请输入你的年龄")
    age=int(age)
    if age<3 and age>0:
        price=0
    elif age<12 and age>=3:
        price=10
    else:
        price=15
print(price)


请输入你的年龄56

请输入你的年龄32

请输入你的年龄15


KeyboardInterrupt: Interrupted by user

In [55]:
active=True
sites=[]
while active:
    site=input("如果你可以去世界的任何一个地方，你想去哪里？")
    sites.append(site)
    over=input("是否结束？Yes/No")
    if over=="Yes":
        active=False
print(sites)

如果你可以去世界的任何一个地方，你想去哪里？拉普兰德
是否结束？Yes/NoNO
如果你可以去世界的任何一个地方，你想去哪里？法国
是否结束？Yes/NoNo
如果你可以去世界的任何一个地方，你想去哪里？犹太
是否结束？Yes/NoYes
['拉普兰德', '法国', '犹太']


In [56]:
def describe_city(city='reykjavik',country='iceland'):
    print(city.title()+" is in "+country.title())
describe_city()
describe_city('beijing','china')
describe_city(city='洛杉矶',country='美国')

Reykjavik is in Iceland
Beijing is in China
洛杉矶 is in 美国


In [57]:
def name(first_name,last_name,middle_name=''):
    if middle_name:
        full_name=first_name+' '+middle_name+' '+last_name
    else:
        full_name=first_name+' '+last_name
    return full_name.title()
musician=name('jimi','hendrix')
print(musician)
musician=name('john','lee','hooker')
print(musician)

Jimi Hendrix
John Hooker Lee


In [58]:
def name(first_name,last_name,middle_name):
    if middle_name:
        full_name=first_name+' '+middle_name+' '+last_name
    else:
        full_name=first_name+' '+last_name
    return full_name.title()
while True:
    print("\n请告诉我你的名字")
    print("输入q结束")
    print("如果没有中间名字，请输入空格")
    f_name=input("First_name:")
    l_name=input("Last_name:")
    m_name=input("Middle_name:")
    if f_name=='q':
        break
    if l_name=='q':
        break
    if m_name=='q':
        break
    musician=name(f_name,l_name,m_name)
    print(musician)


请告诉我你的名字
输入q结束
如果没有中间名字，请输入空格
First_name:hei
Last_name:xiaoyan
Middle_name:meiyou
Hei Meiyou Xiaoyan

请告诉我你的名字
输入q结束
如果没有中间名字，请输入空格
First_name:chen
Last_name:yanju
Middle_name: 
Chen   Yanju

请告诉我你的名字
输入q结束
如果没有中间名字，请输入空格
First_name:q
Last_name:q
Middle_name:q


In [59]:
import time
t0 = time.time()
print('显示程序开始的时间：',time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))

t1=time.time()
print('显示程序结束的时间：',time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))
print('用时：%.6fs'%(t1-t0))

显示程序开始的时间： 2020-12-15 18:32:19
显示程序结束的时间： 2020-12-15 18:32:19
用时：0.000996s


In [61]:
import time
t0 = time.time()
print('显示此刻的时间：',time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))

for i in range(0,1000):
    for j in range(0,1000):
        for k in range(0,1000):
            if((i+j)==2997):
                print(i,j,'\n')

t1 = time.time()
print('显示此刻的时间：',time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))
print('用时：%.5fs'%(t1-t0))

显示此刻的时间： 2020-12-15 18:33:00


KeyboardInterrupt: 

In [62]:
import numpy as np
a = np.array(['a','s','d','f'])
b = np.array([1,2,3,4])
c = np.array([4,5,6,7])
d = np.eye(4)

In [63]:
a

array(['a', 's', 'd', 'f'], dtype='<U1')

In [64]:
b

array([1, 2, 3, 4])

In [65]:
c

array([4, 5, 6, 7])

In [66]:
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
a+c

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> dtype('<U11')

In [68]:
b+d

array([[2., 2., 3., 4.],
       [1., 3., 3., 4.],
       [1., 2., 4., 4.],
       [1., 2., 3., 5.]])

In [69]:
a+d

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')

In [70]:
d


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [71]:
b-c

array([-3, -3, -3, -3])

In [72]:
b-d

array([[0., 2., 3., 4.],
       [1., 1., 3., 4.],
       [1., 2., 2., 4.],
       [1., 2., 3., 3.]])

In [73]:
b*c

array([ 4, 10, 18, 28])

In [74]:
b/c

array([0.25      , 0.4       , 0.5       , 0.57142857])

In [75]:
b**c

array([    1,    32,   729, 16384], dtype=int32)

In [76]:
a.shape

(4,)

In [77]:
d.shape

(4, 4)

In [78]:

a.ndim

1

In [79]:

d.ndim

2

In [80]:

a.dtype

dtype('<U1')

In [81]:
d.dtype

dtype('float64')

In [82]:
import numpy as np 
a = [5,6,16,9]
np.mean(a)

9.0

In [83]:
np.average(a)

9.0

In [84]:
np.average(a)


9.0

In [85]:
np.average(a,weights=[1,2,1,1])

8.4

In [86]:
a = [5,6,16,9]
np.var(a)

18.5

In [87]:
np.var(a, ddof =1)

24.666666666666668

In [88]:
b = [[4,5],[6,7]]
b

[[4, 5], [6, 7]]

In [89]:

np.var(b)

1.25

In [90]:

np.var(b,axis=0)

array([1., 1.])

In [91]:
import pandas as pd
df = pd.DataFrame(np.array([[85, 68, 90], [82, 63, 88], [84, 90, 78]]), columns=['统计学', '高数', '英语'], index=['张三', '李四', '王五'])
df

统计学  高数  英语
张三   85  68  90
李四   82  63  88
王五   84  90  78

In [92]:
df.mean()

统计学    83.666667
高数     73.666667
英语     85.333333
dtype: float64

In [93]:
df.mean(axis=1)

张三    81.000000
李四    77.666667
王五    84.000000
dtype: float64

In [94]:
df


统计学  高数  英语
张三   85  68  90
李四   82  63  88
王五   84  90  78

In [95]:
df.iloc[0,:].mean()

81.0

In [96]:
df.iloc[:,2].mean()

85.33333333333333

### 1.String 字符串

In [1]:
var1="hello world"
var2="runoob"
print(type(var1))
print(len(var1))
print("var1[0]:",var1[0])
print("var2[1:5]:",var2[1:5])

<class 'str'>
11
var1[0]: h
var2[1:5]: unoo


In [2]:
var1="Hello World"
print("已更新字符串：",var1[:6]+"runoob!")

已更新字符串： Hello runoob!


In [3]:
'Hello ' * 5
'H' in 'Hello'

True

In [4]:
name = 'Lucy'
print(f'I am {name}')
print(r'I\'m OK')

I am Lucy
I\'m OK


In [5]:
name=""
print("this is your name")

this is your name


In [6]:
sentence="hello world"
print(sentence.capitalize())
print(sentence.upper())
print(sentence.title())

Hello world
HELLO WORLD
Hello World


In [8]:
var="www.runoob.com"
sub="o"
print("var.count("o"):",var.count(sub))
sub="run"
print("var.count("run",0,10):",var.count(sub,0,10))

SyntaxError: invalid syntax (<ipython-input-8-9cd78524156e>, line 3)

In [9]:
var='Runoob example....wow!!!'
suffix='!!'
print (var.endswith(suffix))
print (var.endswith(suffix, len(var) - 1))
suffix='Run'
print (var.endswith(suffix))
print (var.endswith(suffix, 0, 3))

True
False
False
True


In [10]:
import re
re.match(r'\d{3}\-\d{3,8}$', '010-12345')

<re.Match object; span=(0, 9), match='010-12345'>

In [11]:
print(re.match(r'^\d{3}\-\d{3,8}$', '010 12345'))

None


In [12]:
'a b   c'.split(' ')

['a', 'b', '', '', 'c']

In [13]:
re.split(r'\s+', 'a b   c')

['a', 'b', 'c']

In [14]:
re.split(r'[\s\,]+', 'a,b, c  d')

['a', 'b', 'c', 'd']

In [15]:
re.split(r'[\s\,\;]+', 'a,b;; c  d')

['a', 'b', 'c', 'd']

In [16]:
m = re.match(r'^(\d{3})-(\d{3,8})$', '010-12345')
print(m)
print(m.group(0))
print(m.group(1))
print(m.group(2))

<re.Match object; span=(0, 9), match='010-12345'>
010-12345
010
12345


In [17]:
t = '19:05:30'
m = re.match(r'^(0[0-9]|1[0-9]|2[0-3]|[0-9])\:(0[0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9]|[0-9])\:(0[0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9]|[0-9])$', t)
m.groups()

('19', '05', '30')

In [18]:
colors = ['red', 'green', 'blue', 'yellow', 'white', 'black']
print(type(colors))
colors

<class 'list'>


['red', 'green', 'blue', 'yellow', 'white', 'black']

In [19]:
print(colors[0])
print(colors[1])
print(colors[2])
print(colors[-1])
print(colors[-2])
print(colors[-3])

red
green
blue
black
white
yellow


In [20]:
numbers = [0 ,10, 20, 30, 40, 50, 60, 70, 80, 90]
numbers

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

In [21]:
print(numbers[2:4])
print(numbers[3:])
print(numbers[:3])
print(numbers[-4:-2])
print(numbers[0:8:2])
print(numbers[-2:-10:-1])
print(numbers[-2::-1])
print(numbers[:-10:-1])
print(numbers[::-1])

[20, 30]
[30, 40, 50, 60, 70, 80, 90]
[0, 10, 20]
[60, 70]
[0, 20, 40, 60]
[80, 70, 60, 50, 40, 30, 20, 10]
[80, 70, 60, 50, 40, 30, 20, 10, 0]
[90, 80, 70, 60, 50, 40, 30, 20, 10]
[90, 80, 70, 60, 50, 40, 30, 20, 10, 0]


In [22]:
colors = ['red', 'green', 'blue', 'yellow', 'white', 'black']
colors[2] = 'pink'
colors

['red', 'green', 'pink', 'yellow', 'white', 'black']

In [23]:
colors = ['red', 'green', 'blue', 'yellow', 'white', 'black']
del colors[2]
colors.remove('red')
colors

['green', 'yellow', 'white', 'black']

In [24]:
colors = ['red', 'green', 'blue', 'yellow', 'white', 'black']
colors.append('pink')
colors.insert(2, 'brown')
colors

['red', 'green', 'brown', 'blue', 'yellow', 'white', 'black', 'pink']

In [25]:
colors = ['red', 'green', 'blue', 'yellow', 'white', 'black', 'red']
print(colors.count('red'))
print(colors.index('green'))

2
1


In [26]:
squares = []
squares += [1, 4, 9, 16, 25]
squares += [36, 49, 64]
squares

[1, 4, 9, 16, 25, 36, 49, 64]

In [27]:
squares.extend([81, 100])
squares

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [28]:
['Hello', 'World'] * 5

['Hello',
 'World',
 'Hello',
 'World',
 'Hello',
 'World',
 'Hello',
 'World',
 'Hello',
 'World']

In [29]:
print(type(range(5)))
list(range(5))

<class 'range'>


[0, 1, 2, 3, 4]

In [30]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [31]:
args = [*range(5), 'Hello', 'World']
print(args)
print(*args, sep='_')

[0, 1, 2, 3, 4, 'Hello', 'World']
0_1_2_3_4_Hello_World


In [32]:
tup1 = ('Google', 'Runoob', 1997, 2000)
print(type(tup1))
tup2 = (1, 2, 3, 4, 5)
tup3 = "a", "b", "c", "d"   #  不需要括号也可以
tup4 = (1,)
tup5 = 1,
print(tup1)
print(tup2)
print(tup3)
print(tup4)
print(tup5)

<class 'tuple'>
('Google', 'Runoob', 1997, 2000)
(1, 2, 3, 4, 5)
('a', 'b', 'c', 'd')
(1,)
(1,)


In [33]:
tup1[0]

'Google'

In [34]:
tup1[1] = 'Baidu'

TypeError: 'tuple' object does not support item assignment

In [35]:
tup1[1] = 'Baidu'

TypeError: 'tuple' object does not support item assignment