In [1]:
active=True
sites=[]
while active:
    site=input("如果你可以去世界的任何一个地方，你想去哪里？")
    sites.append(site)
    over=input("是否结束？Yes/No")
    if over=="Yes":
        active=False
print(sites)

如果你可以去世界的任何一个地方，你想去哪里？秋叶原
是否结束？Yes/Nono
如果你可以去世界的任何一个地方，你想去哪里？墨尔本
是否结束？Yes/Nono
如果你可以去世界的任何一个地方，你想去哪里？爱丽舍乐园
是否结束？Yes/Noyes
如果你可以去世界的任何一个地方，你想去哪里？无
是否结束？Yes/NoYes
['秋叶原', '墨尔本', '爱丽舍乐园', '无']


In [2]:
def describe_city(city='reykjavik',country='iceland'):
    print(city.title()+" is in "+country.title())
describe_city()
describe_city('beijing','china')
describe_city(city='洛杉矶',country='美国')

Reykjavik is in Iceland
Beijing is in China
洛杉矶 is in 美国


In [3]:
def name(first_name,last_name,middle_name=''):
    if middle_name:
        full_name=first_name+' '+middle_name+' '+last_name
    else:
        full_name=first_name+' '+last_name
    return full_name.title()
musician=name('jimi','hendrix')
print(musician)
musician=name('john','lee','hooker')
print(musician)

Jimi Hendrix
John Hooker Lee


In [4]:
def name(first_name,last_name,middle_name):
    if middle_name:
        full_name=first_name+' '+middle_name+' '+last_name
    else:
        full_name=first_name+' '+last_name
    return full_name.title()
while True:
    print("\n请告诉我你的名字")
    print("输入q结束")
    print("如果没有中间名字，请输入空格")
    f_name=input("First_name:")
    l_name=input("Last_name:")
    m_name=input("Middle_name:")
    if f_name=='q':
        break
    if l_name=='q':
        break
    if m_name=='q':
        break
    musician=name(f_name,l_name,m_name)
    print(musician)


请告诉我你的名字
输入q结束
如果没有中间名字，请输入空格
First_name:胡
Last_name:家豪
Middle_name: 
胡   家豪

请告诉我你的名字
输入q结束
如果没有中间名字，请输入空格
First_name:q
Last_name:q
Middle_name:q


In [5]:
import time
t0 = time.time()
print('显示程序开始的时间：',time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))

t1=time.time()
print('显示程序结束的时间：',time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))
print('用时：%.6fs'%(t1-t0))

显示程序开始的时间： 2020-12-16 17:16:42
显示程序结束的时间： 2020-12-16 17:16:42
用时：0.000000s


In [6]:

import numpy as np
#1、创建一个数值范围为0~1，间隔为0.01的数组
arr1 = np.arange(0,1,0.01)
print('arange函数创建的数值范围为0~1间隔为0.01的数组arr1为：\n',arr1)
#2、创建由100个服从正太分布的随机数构成的数组
arr2 = np.random.randn(100)
print('生成的随机数组arr1为：\n',arr2)
#3、对创建的两个数组进行四则运算
print('arr1 + arr2: \n',arr1+arr2)
print('arr1 - arr2: \n',arr1-arr2)
print('arr1 * arr2: \n',arr1*arr2)
print('arr1 / arr2: \n',arr1/arr2)
#4、对创建的数组进行简单的统计分析
print('正太分布数数组的累计和为：\n',np.cumsum(arr2))#计算所有元素的累计和
print('正态分布数去重后的值组为：\n',np.unique(arr2))#去除重复值
print('正态分布数组的均值为：',np.mean(arr2))#计算数组均值
print('正态分布数组的标准差为:',np.std(arr2))#计算数组标准差
print('正态分布数组的方差为：',np.var(arr2))#计算数组方差
print('正态分布数组的最小值为:',np.min(arr2))#计算最小值
print('正态分布数组的最大值为：',np.max(arr2))#计算最大值
print('正态分布数组的总和为：',np.sum(arr2))#计算数组总和

arange函数创建的数值范围为0~1间隔为0.01的数组arr1为：
 [0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]
生成的随机数组arr1为：
 [ 0.4969269   1.9492873   0.34736767  0.51380952 -0.62708533  0.89676748
 -0.70786648  0.48972612  1.02962928 -0.32377712 -1.07736981  1.53204353
 -1.0930714   0.02985682  0.69689734  0.9394363   0.0975046   0.28070935
  2.41728648 -0.28828935  0.09373254 -0.37230105 -0.62081139  0.67027813
 -1.64462025 -1.83174704 -0.34357389  0.6034478   0.80739297 -0.33374228
  0.63154974  0.66843772  1.2264798  -0.67614458 -0.12825675 -1.97050832
 

In [7]:
import numpy as np
matr1=np.ones((8,8))
for i in range(8):
    for j in range(8):
        if(i+j)%2==0:
            matr1[i,j]=0
print('国际棋盘对应的矩阵为：\n',matr1)

for i in range(0,8):
    for j in range(0,8):
        if matr1[i,j]==0:
            print("□",end='   ')
        else:
            print("■", end='   ')
    print('\n')

国际棋盘对应的矩阵为：
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   

□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   

□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   

□   ■   □   ■   □   ■   □   ■   

■   □   ■   □   ■   □   ■   □   



In [8]:
import pandas as pd
df = pd.DataFrame(np.array([[85, 68, 90], [82, 63, 88], [84, 90, 78]]), columns=['统计学', '高数', '英语'], index=['张三', '李四', '王五'])
df

统计学  高数  英语
张三   85  68  90
李四   82  63  88
王五   84  90  78

In [9]:
import numpy as np

a = [1, 2, 3]
b = np.array(a, dtype=np.float_)
# 或者
b = np.array(a, dtype=float)

print(b)
print(b.dtype)
print(type(b[0]))

[1. 2. 3.]
float64
<class 'numpy.float64'>


In [10]:
import numpy as np
import array

a = array.array('i', [1, 2, 3, 4])
print(a)

na = np.frombuffer(a, dtype=np.int_)
print(na)

a[0] = 10
print(a)
print(na)

array('i', [1, 2, 3, 4])
[1 2 3 4]
array('i', [10, 2, 3, 4])
[10  2  3  4]


In [11]:
# from __future__ import pyecharts

from pyecharts.globals import CurrentConfig, NotebookType
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB
CurrentConfig.ONLINE_HOST

# import matplotlib
# matplotlib.use('TkAgg')
# import matplotlib.pyplot as plt

from pyecharts.charts import Bar
from pyecharts import options as opts
# 内置主题类型可查看 pyecharts.globals.ThemeType
from pyecharts.globals import ThemeType
# print('ok')
bar = (
    Bar(init_opts=opts.InitOpts(theme=ThemeType.LIGHT))
    .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
    .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
    .add_yaxis("商家B", [15, 6, 45, 20, 35, 66])
    .set_global_opts(title_opts=opts.TitleOpts(title="主标题", subtitle="副标题"))
)
bar

ModuleNotFoundError: No module named 'pyecharts'

In [12]:
# import sys
# print(sys.executable)

import face_recognition
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
import numpy as np

image = face_recognition.load_image_file("faces.jpeg")
face_locations = face_recognition.face_locations(image)

im=np.array(Image.open('faces.jpeg'), dtype=np.uint8)

fig, ax = plt.subplots(1, figsize=(8, 8))
ax.imshow(im)

for face_loc in face_locations:
    rect = patches.Rectangle((face_loc[1], face_loc[0]), face_loc[3] - face_loc[1], face_loc[2] - face_loc[0], linewidth=2,edgecolor='r',facecolor='none')
    ax.add_patch(rect)
plt.show()

ModuleNotFoundError: No module named 'face_recognition'

In [13]:
import pandas as pd
import jieba

# 显示所有列
pd.set_option('display.max_columns', None)
# 显示所有行
pd.set_option('display.max_rows', None)
# 设置value的显示长度为100，默认为50
pd.set_option('max_colwidth', 100)
    
tweets = pd.read_csv('weibo_hashtag/weibo/#进击的巨人最终季#/#进击的巨人最终季#.csv', usecols=['正文'])
tweets['jieba分词'] = tweets.apply(lambda x: ';'.join(jieba.cut(x['正文'])), axis=1)
tweets
Building prefix dict from the default dictionary ...
Dumping model to file cache C:\Users\Ludy_Lab\AppData\Local\Temp\jieba.cache
Loading model cost 0.635 seconds.
Prefix dict has been built successfully.

SyntaxError: invalid syntax (<ipython-input-13-8ab38027a748>, line 14)

In [14]:
import numpy as np
import h5py
import matplotlib.pyplot as plt
from testCases_v2 import *
from dnn_utils_v2 import sigmoid, sigmoid_backward, relu, relu_backward

%matplotlib inline
plt.rcParams['figure.figsize'] = (5.0, 4.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

%load_ext autoreload
%autoreload 2

np.random.seed(1)

ModuleNotFoundError: No module named 'testCases_v2'

In [15]:
# GRADED FUNCTION: initialize_parameters

def initialize_parameters(n_x, n_h, n_y):
    """
    Argument:
    n_x -- size of the input layer
    n_h -- size of the hidden layer
    n_y -- size of the output layer
    
    Returns:
    parameters -- python dictionary containing your parameters:
                    W1 -- weight matrix of shape (n_h, n_x)
                    b1 -- bias vector of shape (n_h, 1)
                    W2 -- weight matrix of shape (n_y, n_h)
                    b2 -- bias vector of shape (n_y, 1)
    """
    
    np.random.seed(1)
    
    ### START CODE HERE ### (≈ 4 lines of code)
    W1 = np.random.randn(n_h, n_x)*0.01
    b1 = np.zeros((n_h, 1))
    W2 = np.random.randn(n_y, n_h)*0.01
    b2 = np.zeros((n_y, 1))
    ### END CODE HERE ###
    
    assert(W1.shape == (n_h, n_x))
    assert(b1.shape == (n_h, 1))
    assert(W2.shape == (n_y, n_h))
    assert(b2.shape == (n_y, 1))
    
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [16]:
parameters = initialize_parameters(2,2,1)
print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))

W1 = [[ 0.01624345 -0.00611756]
 [-0.00528172 -0.01072969]]
b1 = [[0.]
 [0.]]
W2 = [[ 0.00865408 -0.02301539]]
b2 = [[0.]]


In [17]:
# GRADED FUNCTION: initialize_parameters_deep

def initialize_parameters_deep(layer_dims):
    """
    Arguments:
    layer_dims -- python array (list) containing the dimensions of each layer in our network
    
    Returns:
    parameters -- python dictionary containing your parameters "W1", "b1", ..., "WL", "bL":
                    Wl -- weight matrix of shape (layer_dims[l], layer_dims[l-1])
                    bl -- bias vector of shape (layer_dims[l], 1)
    """
    
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)            # number of layers in the network

    for l in range(1, L):
        ### START CODE HERE ### (≈ 2 lines of code)
        parameters['W' + str(l)] = np.random.randn(layer_dims[l],layer_dims[l-1])*0.01
        parameters['b' + str(l)] = np.zeros((layer_dims[l],1))
        ### END CODE HERE ###
        
        assert(parameters['W' + str(l)].shape == (layer_dims[l], layer_dims[l-1]))
        assert(parameters['b' + str(l)].shape == (layer_dims[l], 1))

        
    return parameters

In [18]:
parameters = initialize_parameters_deep([5,4,3])
print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))

W1 = [[ 0.01788628  0.0043651   0.00096497 -0.01863493 -0.00277388]
 [-0.00354759 -0.00082741 -0.00627001 -0.00043818 -0.00477218]
 [-0.01313865  0.00884622  0.00881318  0.01709573  0.00050034]
 [-0.00404677 -0.0054536  -0.01546477  0.00982367 -0.01101068]]
b1 = [[0.]
 [0.]
 [0.]
 [0.]]
W2 = [[-0.01185047 -0.0020565   0.01486148  0.00236716]
 [-0.01023785 -0.00712993  0.00625245 -0.00160513]
 [-0.00768836 -0.00230031  0.00745056  0.01976111]]
b2 = [[0.]
 [0.]
 [0.]]


In [19]:
# GRADED FUNCTION: linear_forward

def linear_forward(A, W, b):
    """
    Implement the linear part of a layer's forward propagation.

    Arguments:
    A -- activations from previous layer (or input data): (size of previous layer, number of examples)
    W -- weights matrix: numpy array of shape (size of current layer, size of previous layer)
    b -- bias vector, numpy array of shape (size of the current layer, 1)

    Returns:
    Z -- the input of the activation function, also called pre-activation parameter 
    cache -- a python dictionary containing "A", "W" and "b" ; stored for computing the backward pass efficiently
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    Z = np.dot(W,A)+b
    ### END CODE HERE ###
    
    assert(Z.shape == (W.shape[0], A.shape[1]))
    cache = (A, W, b)
    
    return Z, cache

In [20]:
A, W, b = linear_forward_test_case()

Z, linear_cache = linear_forward(A, W, b)
print("Z = " + str(Z))

NameError: name 'linear_forward_test_case' is not defined

In [21]:
# GRADED FUNCTION: linear_activation_forward

def linear_activation_forward(A_prev, W, b, activation):
    """
    Implement the forward propagation for the LINEAR->ACTIVATION layer

    Arguments:
    A_prev -- activations from previous layer (or input data): (size of previous layer, number of examples)
    W -- weights matrix: numpy array of shape (size of current layer, size of previous layer)
    b -- bias vector, numpy array of shape (size of the current layer, 1)
    activation -- the activation to be used in this layer, stored as a text string: "sigmoid" or "relu"

    Returns:
    A -- the output of the activation function, also called the post-activation value 
    cache -- a python dictionary containing "linear_cache" and "activation_cache";
             stored for computing the backward pass efficiently
    """
    
    if activation == "sigmoid":
        # Inputs: "A_prev, W, b". Outputs: "A, activation_cache".
        ### START CODE HERE ### (≈ 2 lines of code)
        Z, linear_cache = linear_forward(A_prev, W, b)
        A, activation_cache = sigmoid(Z)
        ### END CODE HERE ###
    
    elif activation == "relu":
        # Inputs: "A_prev, W, b". Outputs: "A, activation_cache".
        ### START CODE HERE ### (≈ 2 lines of code)
        Z, linear_cache = linear_forward(A_prev, W, b)
        A, activation_cache = relu(Z)
        ### END CODE HERE ###
    
    assert (A.shape == (W.shape[0], A_prev.shape[1]))
    cache = (linear_cache, activation_cache)

    return A, cache

In [22]:
A_prev, W, b = linear_activation_forward_test_case()

A, linear_activation_cache = linear_activation_forward(A_prev, W, b, activation = "sigmoid")
print("With sigmoid: A = " + str(A))

A, linear_activation_cache = linear_activation_forward(A_prev, W, b, activation = "relu")
print("With ReLU: A = " + str(A))

NameError: name 'linear_activation_forward_test_case' is not defined

In [23]:
# GRADED FUNCTION: L_model_forward

def L_model_forward(X, parameters):
    """
    Implement forward propagation for the [LINEAR->RELU]*(L-1)->LINEAR->SIGMOID computation
    
    Arguments:
    X -- data, numpy array of shape (input size, number of examples)
    parameters -- output of initialize_parameters_deep()
    
    Returns:
    AL -- last post-activation value
    caches -- list of caches containing:
                every cache of linear_relu_forward() (there are L-1 of them, indexed from 0 to L-2)
                the cache of linear_sigmoid_forward() (there is one, indexed L-1)
    """

    caches = []
    A = X
    L = len(parameters) // 2                  # number of layers in the neural network
    
    # Implement [LINEAR -> RELU]*(L-1). Add "cache" to the "caches" list.
    for l in range(1, L):
        A_prev = A 
        ### START CODE HERE ### (≈ 2 lines of code)
        A, cache = linear_activation_forward(A_prev, parameters['W' + str(l)], parameters['b' + str(l)], activation = "relu")

        ### END CODE HERE ###
    
    # Implement LINEAR -> SIGMOID. Add "cache" to the "caches" list.
    ### START CODE HERE ### (≈ 2 lines of code)
    AL, cache = linear_activation_forward(A, parameters['W' + str(L)], parameters['b' + str(L)], activation = "sigmoid")

    ### END CODE HERE ###
    
    assert(AL.shape == (1,X.shape[1]))
            
    return AL, caches

In [24]:
class Document:
    def __init__(self):
        self.characters = []
        self.cursor = Cursor(self)
        self.filename = ""

    def insert(self, character):
        if not hasattr(character, "character"):
            character = Character(character)
        self.characters.insert(self.cursor.position, character)
        self.cursor.forward()

    def delete(self):
        del self.characters[self.cursor.position]

    def save(self):
        f = open(self.filename, "w")
        f.write("".join(self.characters))
        f.close()

    @property
    def string(self):
        return "".join((str(c) for c in self.characters))

    # def forward(self):
    #     self.cursor += 1
    #
    # def back(self):
    #     self.cursor -= 1


class Cursor:
    def __init__(self, document):
        self.document = document
        self.position = 0

    def forward(self):
        self.position += 1

    def back(self):
        self.position -= 1

    def home(self):
        while self.document.characters[self.position - 1].character != "\n":
            self.position -= 1
            if self.position == 0:
                break

    def end(self):
        while self.position < len(self.document.characters) and self.document.characters[self.position].character != "\n":
            self.position += 1


class Character:
    def __init__(self, character, bold=False, italic=False, underline=False):
        assert len(character) == 1
        self.character = character
        self.bold = bold
        self.italic = italic
        self.underline = underline

    def __str__(self):
        bold = "*" if self.bold else ""
        italic = "/" if self.italic else ""
        underline = "_" if self.underline else ""
        return bold + italic + underline + self.character


if __name__ == '__main__':
    doc = Document()
    doc.filename = "test_document"
    doc.insert("h")
    doc.insert("e")
    doc.insert(Character("l", bold=True))
    doc.insert("l")
    doc.insert("o")
    doc.insert("\n")
    doc.insert("w")
    doc.insert("o")
    doc.insert("r")
    doc.insert("l")
    doc.insert("d")
    print(doc.string)
    # doc.back()
    # doc.delete()
    # doc.insert("p")
    # print("".join(doc.characters))
    doc.cursor.home()
    doc.insert("*")
    print(doc.string)

he*llo
world
he*llo
*world


In [25]:

class InvalidWithdrawal(Exception):
    def __init__(self, balance, amount):
        super().__init__("account doesn't have ${}.".format(amount))
        self.amount = amount
        self.balance = balance

    def overage(self):
        return self.amount - self.balance


try:
    raise InvalidWithdrawal(25, 50)
except InvalidWithdrawal as e:
    print("you are over {}".format(e.overage()))

you are over 25


In [26]:
class washer(object):
    #定义类属性
    company="Le Xi"
    #1.11定义静态方法
    @staticmethod
    def spins_ml(spins):
        #1.13静态方法只能访问类属性不能访问实例属性
        print("company:",washer.company)
        return spins*0.4
    
    #1.21定义类方法
    @classmethod
    def get_washer(cls,water,scour):
        #1.23类方法只能访问类属性不能访问实例属性
        print("company:",washer.company)
        return cls(water,cls.spins_ml(scour))
   
    def __init__(self,water=10,scour=2):
        self._water=water
        self.scour=scour
        self.year=2010
 
    @property
    def water(self):
        return self._water
    @property
    def total_year(self):
        return 2015-self.year
       
   
    @water.setter
    def water(self,water):
        self._water = water
           
         
    def set_water(self,water):
        self.water=water
    def set_scour(self,scour):
        self.scour=scour
           
    def add_water(self):
        print("add water",self.water)
    def add_scour(self):
        print("add scour",self.scour)
    def start_wash(self):
   
        self.add_water()
        self.add_scour()
        print("start wash ...")
# if __name__ == '__main__':
#     #1.12访问静态方法
#     print(washer.spins_ml(8))
#     w=washer(100,washer.spins_ml(8))
#     w.start_wash()
    #1.22访问类方法
#     w = washer.get_washer(100, 9)
#     w.start_wash()
#     
#2.类的继承和方法重载
class washerDry(washer):
    def dry(self):
        print("dry clothes...")
    #重载父类方法
    def start_wash(self):
        print("......")
        #使用super一定要指定其父类继承自object
        super(washerDry,self).start_wash()
        print("......")
        
if __name__ == '__main__':
    w = washerDry()
    w.start_wash()
    w.dry()

......
add water 10
add scour 2
start wash ...
......
dry clothes...
