In [84]:
list1 = ['Google', 'Runoob', 1997, 2000]
list2 = [1, 2, 3, 4, 5 ]
list3 = ["a", "b", "c", "d"]
list4 = ['red', 'green', 'blue', 'yellow', 'white', 'black']

In [85]:
type(list1)

list

In [86]:
list2

[1, 2, 3, 4, 5]

In [87]:
range(list3)

TypeError: 'list' object cannot be interpreted as an integer

In [ ]:
list3[0]

In [ ]:
list3[5]

In [ ]:
list3{3}

In [ ]:
list3[0,2]

# list[a:b]返回下表a到b-1
# list[a] == list[-b]
## a-(-b)= length

In [ ]:
list3[0:2]

In [ ]:
list3[1:2]

In [ ]:
list3[:4]

In [ ]:
list3[:]

In [ ]:
list3

In [ ]:
type(list[:])

In [ ]:
list1[-1]

In [88]:
list1

['Google', 'Runoob', 1997, 2000]

In [89]:
list1[3]

2000

In [90]:
list4[0:-1]

['red', 'green', 'blue', 'yellow', 'white']

In [91]:
list2+list3

[1, 2, 3, 4, 5, 'a', 'b', 'c', 'd']

In [92]:
(list2+list3)[-1]

'd'

## a、b<0, 返回a到b-1性质依然不变

In [93]:
(list2+list3)[-4:-1]

['a', 'b', 'c']

In [94]:
(list2+list3)[-4:-4]

[]

In [95]:
(list2+list3)[-1:0]

[]

In [96]:
list4

['red', 'green', 'blue', 'yellow', 'white', 'black']

In [97]:
del list4[0:3]

In [98]:
list4

['yellow', 'white', 'black']

In [99]:
list4*4

['yellow',
 'white',
 'black',
 'yellow',
 'white',
 'black',
 'yellow',
 'white',
 'black',
 'yellow',
 'white',
 'black']

In [100]:
list4*2

['yellow', 'white', 'black', 'yellow', 'white', 'black']

In [101]:
list4+= list4*2

In [102]:
list4

['yellow',
 'white',
 'black',
 'yellow',
 'white',
 'black',
 'yellow',
 'white',
 'black']

In [103]:
list5=[list1,[list2,list3[3]],list2]

In [104]:
list5

[['Google', 'Runoob', 1997, 2000], [[1, 2, 3, 4, 5], 'd'], [1, 2, 3, 4, 5]]

In [105]:
list5[1][0]

[1, 2, 3, 4, 5]

In [106]:
list5[1][0][2]

3

In [107]:
len(list5)

3

In [108]:
len(list5[1])

2

In [109]:
list5.count(2)

0

In [110]:
list5[1][0].count(2)

1

In [111]:
list5.index(5)

ValueError: 5 is not in list

In [ ]:
list5[:]

In [ ]:
list5[:].index(2)

In [ ]:
list5.sort

In [ ]:
list5

In [ ]:
import numpy as np

In [ ]:
np.array(list5)

In [ ]:
np

In [ ]:
np.array(list5).dtype

### [[: two-dim

In [59]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
np.ones((2,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [61]:
np.zeros((1,2),(2,3))

TypeError: Cannot interpret '2' as a data type

In [74]:
np.zeros((2,1,1,1,2))

array([[[[[0., 0.]]]],



       [[[[0., 0.]]]]])

In [76]:
np.zeros((2,2,1))

array([[[0.],
        [0.]],

       [[0.],
        [0.]]])

In [78]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [80]:
arr1=np.eye(5)
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [81]:
type(arr1)

numpy.ndarray

In [82]:
del arr1

In [83]:
arr1

NameError: name 'arr1' is not defined

In [120]:
arr=np.empty((2,4,1))
#arr[[4,3,0,6]]
arr

array([[[0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.]]])

In [121]:
arr.dim()

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

In [124]:
pip install pygame

Note: you may need to restart the kernel to use updated packages.


In [132]:
import pygame
import random
import pygame

SCREEN=pygame.Rect(0,0,480,700)
FPS=60
CREAT_ENEMY_EVENT=pygame.USEREVENT
HERO_FIRE=pygame.USEREVENT+1
class GameSprite(pygame.sprite.Sprite):
    """飞机大战精灵组"""
    def __init__(self,image_name,speed=1):
        super().__init__()
        self.image=pygame.image.load(image_name)
        self.rect=self.image.get_rect()
        self.speed=speed
    def update(self):
        self.rect.y+=self.speed
class Background(GameSprite):
    def __init__(self,is_alt=False):
        super().__init__("team.png")
        if is_alt:
            self.rect.y=-self.rect.height
    def update(self):
        super().update()
        if self.rect.y>SCREEN.height:
            self.rect.y=-self.rect.height
class Enemy(GameSprite):
    """敌机精灵"""
    def __init__(self):
        #创建敌机精灵
        super().__init__("team.png")
        #随机敌机速度
        self.speed=random.randint(1,3)
        #随机位置
        self.bottom=0
        max_a=SCREEN.width-self.rect.width
        self.rect.x=random.randint(0,max_a)
    def update(self):
        super().update()
        if self.rect.y>=SCREEN.height:
            #print("删除")
            #kill方法可以将精灵从所有精灵组中移除
            self.kill()
    def __del__(self):
        #print("删除%s" %self.rect)
        pass
class Hero(GameSprite):
    def __init__(self):
        super().__init__("team.png",0)
        self.rect.centerx=SCREEN.centerx
        self.rect.bottom=SCREEN.bottom-120
        self.bullet_group=pygame.sprite.Group()
    def update(self):
        self.rect.x+=self.speed
        if self.rect.x<0:
            self.rect.x=0
        elif self.rect.right>SCREEN.right:
            self.rect.right=SCREEN.right
    def fire(self):
        #创建精灵对象
        for i in (0,1,2):
            bullet=Bullet()
            #定义位置
            bullet.rect.bottom=self.rect.y-i*20
            bullet.rect.centerx=self.rect.centerx
            #追加进精灵组
            self.bullet_group.add(bullet)
class Bullet(GameSprite):
    def __init__(self):
        super().__init__("team.png",speed=-2)
    def update(self):
        super().update()
        if self.rect.bottom<0:
            self.kill()
    def __del__(self):
        print("删除")
class PlaneGame(object):
    def __init__(self):
        #游戏窗口
        self.screen=pygame.display.set_mode(SCREEN.size)
        self.clock=pygame.time.Clock()
        self.__creat_sprites()
        pygame.time.set_timer(CREAT_ENEMY_EVENT,1000)
        pygame.time.set_timer(HERO_FIRE,500)

    def __creat_sprites(self):
        bg1=Background()
        bg2=Background(True)
        self.bg_group=pygame.sprite.Group(bg1,bg2)
        self.enemy_group=pygame.sprite.Group()
        self.hero=Hero()
        self.hero_group=pygame.sprite.Group(self.hero)

    def start_game(self):
        while True:
            self.clock.tick(FPS)
            self.__event_handler()
            self.__check_collide()
            self.__update_sprites()
            pygame.display.update()

    def __event_handler(self):
        for event in pygame.event.get():
            if event.type==pygame.QUIT:
                PlaneGame.__game_over(self)
            elif event.type==CREAT_ENEMY_EVENT:
                enemy=Enemy()
                self.enemy_group.add(enemy)
            elif event.type==HERO_FIRE:
                self.hero.fire()
            # elif event.type==pygame.KEYDOWN and event.key==pygame.K_RIGHT:
            #     print("向右移动")
            # elif event.type==pygame.KEYDOWN and event.key==pygame.K_LEFT:
            #     print("向左移动")
        key_event=pygame.key.get_pressed()
        if key_event[pygame.K_RIGHT]:
            self.hero.speed=2
        elif key_event[pygame.K_LEFT]:
            self.hero.speed=-2
        else:
            self.hero.speed=0
    def __check_collide(self):
        pygame.sprite.groupcollide(self.enemy_group,self.hero.bullet_group,True,True)
        en=pygame.sprite.spritecollide(self.hero,self.enemy_group,True)
        if len(en)>0:
            self.hero.kill()
            PlaneGame.__game_over()
    def __update_sprites(self):
        self.bg_group.update()
        self.bg_group.draw(self.screen)
        self.enemy_group.update()
        self.enemy_group.draw(self.screen)
        self.hero_group.update()
        self.hero_group.draw(self.screen)
        self.hero.bullet_group.update()
        self.hero.bullet_group.draw(self.screen)
    def __game_over(self):
        print("退出游戏")
        pygame.quit()
        exit()






In [135]:
def formatTime(longtime):
    import time
    return time.strftime("%Y-%m-%d %H:%M:%S",time.localtime(longtime))

In [136]:
formatTime(19971020)

'1970-08-20 11:30:20'

In [137]:
for n in range(100,1000):
    i = n // 100
    j = n // 10 % 10
    k = n % 10
    if n == i*i*i + j*j*j + k*k*k: 
        print(n)

153
370
371
407


In [143]:
for n in range(100,1000):
    i = n / 100
    j = n / 10 % 10
    k = n % 10
    if n == i ** 3 + j ** 3 + k ** 3:
        print(n)

In [144]:
MAXIMUM = lambda x,y :  (x > y) * x + (x < y) * y
MINIMUM = lambda x,y :  (x > y) * y + (x < y) * x
 


In [145]:
if __name__ == '__main__':
    a = 10
    b = 20
    print ('The largar one is %d' % MAXIMUM(a,b))
    print ('The lower one is %d' % MINIMUM(a,b))

The largar one is 20
The lower one is 10


In [148]:
class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
print (bcolors.WARNING + "警告的颜色字体" + bcolors.ENDC)

警告的颜色字体


In [150]:
year = int(input('year:\n'))
month = int(input('month:\n'))
day = int(input('day:\n'))
 
months = (0,31,59,90,120,151,181,212,243,273,304,334)
if 0 < month <= 12:
    sum = months[month - 1]
else:
    print ('data error')
sum += day
leap = 0
if (year % 400 == 0) or ((year % 4 == 0) and (year % 100 != 0)):
    leap = 1
if (leap == 1) and (month > 2):
    sum += 1
print ('it is the %dth day.' % sum)

year:
100
month:
1
day:
23
it is the 23th day.


In [152]:
class A:
    pass
class B(A):
    pass
    
print(issubclass(B,A))    # 返回 True

True
