In [1]:
list = ['Google', 'Runoob', "Zhihu", "Taobao", "Wiki"]
print(list[-1])
print(list[:-1])

Wiki
['Google', 'Runoob', 'Zhihu', 'Taobao']


In [2]:
print(list[:])

['Google', 'Runoob', 'Zhihu', 'Taobao', 'Wiki']


In [3]:
list.append("Alibaba")
print(list)

['Google', 'Runoob', 'Zhihu', 'Taobao', 'Wiki', 'Alibaba']


In [4]:
print(type(list))
list = "".join(list)
print(list)
print(type(list))

<class 'list'>
GoogleRunoobZhihuTaobaoWikiAlibaba
<class 'str'>


In [5]:
list = ['Google', 'Runoob', "Zhihu", "Taobao", "Wiki"]
list = "\n".join(list)
print(list)

Google
Runoob
Zhihu
Taobao
Wiki


In [6]:
print(type(""))
print(type(" "))

<class 'str'>
<class 'str'>


In [11]:
import re
print(re.match('/d', '123uuasf').group())


AttributeError: 'NoneType' object has no attribute 'group'

In [17]:
    import re
    obj = re.match('\d+', '123uuasf')
    if obj: 
        print(obj.group())

123


In [20]:
import re 
print(re.find('\d', '123uuasf'))

AttributeError: module 're' has no attribute 'find'

In [23]:
import re 
print(re.findall('\d+', '第3627章 天赐神名')[0])

3627


In [24]:
import time
for i in range(1, 10):
    print(i)
    time.sleep(1)

1
2
3
4
5
6
7
8
9


In [1]:
print("Hello \r world!")

 world!


In [4]:
print("Hello \r\nworld!")
print("Hello\nworld!")

Hello 
world!
Hello
world!


In [1]:
num = 10 
def change_num(num):
    num += 100
    print(num)
change_num(num)
print(num)

print("======================================")

str_ = "abc"
def change_str(str_):
    str_ = "def"
    print(str_)
change_str(str_)
print(str_)

110
10
def
abc


In [2]:
int[] a = {1, 2, 3}

SyntaxError: invalid syntax (<ipython-input-2-22d22314fc7c>, line 1)

In [1]:
from numpy import*
eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
import numpy
a = numpy.array([1,2,3])
print(a)
b = numpy.array([[1,2],[3,4]])
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [8]:
a = numpy.array([1,2,3,4,5], ndmin=5)
print(a)

[[[[[1 2 3 4 5]]]]]


In [10]:
a = numpy.array([1,2,3], dtype = complex )
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [1]:
import re 
print(re.findall('第\d+章', '第3627章 天赐神名')[0])

第3627章


In [6]:
list = ['35713933', '36240746', '36307449', '36471479', '36583260', '36661263', '2670261', '2670269', '2781512', '2781514', '2781519', '2807109', '2807111', '2807113', '2807114', '2807115', '2807116', '2807117']
for i in range(0, 12):
    print(list[i])
    del list[i]
print(list)

35713933
36307449
36583260
2670261
2781512
2781519
2807111
2807114
2807116


IndexError: list index out of range

In [35]:
import requests
from lxml import etree
url = 'https://www.youshuba.cc/ks/txtt333/8337/2670264.txt'
headers = {
    "User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0"
}
chapter_content = requests.get(url=url, headers=headers).text
# print(chapter_content)
tree = etree.HTML(chapter_content)
# print(tree)
chapter = tree.xpath('body//text()')
# print(chapter)

print(chapter)

["var cctxt='\t\t\xa0\xa0\xa0\xa0“走了顺困顶枯枵赶紧回学校去了！”陈九小心夺回顾功带困揣起照片顺困顶枯枵快步夺回顾功带困赶紧返校而去。", '\xa0\xa0\xa0\xa0“砰！”夺回顾功带困一声顺困顶枯枵急步夺回顾功带困回到了宿舍中顺困顶枯枵他一头就扎入了卫生间中顺困顶枯枵也不知道去干些什么了。', '\xa0\xa0\xa0\xa0时间消逝顺困顶枯枵过了许久顺困顶枯枵陈九还顶置中夺粗功地没茵右脚楞夺出来顺困顶枯枵不过一位同学顺困顶枯枵却顶置中夺粗功地抱着肚子火速夺回顾功带困回归了顺困顶枯枵他一进来就撞向了卫生间顺困顶枯枵可惜一下子没茵右脚楞夺撞开顺困顶枯枵随即重敲起来。', '\xa0\xa0\xa0\xa0“砰砰……”强烈夺回顾功带困声音顺困顶枯枵却顶置中夺粗功地并没茵右脚楞夺惊动陈九顺困顶枯枵这一点极度夺回顾功带困不正常。', '\xa0\xa0\xa0\xa0“陈九顺困顶枯枵陈九顺困顶枯枵顶置中夺粗功地你在里面吗顺困顶枯枵快开门顺困顶枯枵老子吃坏肚子了顺困顶枯枵要拉屎……”一个强壮夺回顾功带困人影顺困顶枯枵夹着屁屁顺困顶枯枵很顶置中夺粗功地着急夺回顾功带困。', '\xa0\xa0\xa0\xa0“妈夺回顾功带困顺困顶枯枵搞什么东西顺困顶枯枵你这穷酸东西也敢霸占老子夺回顾功带困厕所？”强壮夺回顾功带困青年着急上火顺困顶枯枵本就看不起陈九夺回顾功带困他顺困顶枯枵当场一脚向门锁踹去。', '\xa0\xa0\xa0\xa0“轰……”一声顺困顶枯枵木门应声而开顺困顶枯枵青年迫不急待夺回顾功带困走入了其中顺困顶枯枵不过看到里面夺回顾功带困场景时顺困顶枯枵他却顶置中夺粗功地当即傻了眼。', '\xa0\xa0\xa0\xa0陈九顺困顶枯枵软倒在地上顺困顶枯枵一动不动顺困顶枯枵毫无声息顺困顶枯枵脸色煞白顺困顶枯枵超级吓人！', '\xa0\xa0\xa0\xa0壮着大胆夺回顾功带困顺困顶枯枵青年来到了陈九夺回顾功带困鼻息间一试顺困顶枯枵顿时大骇顺困顶枯枵慌乱一般夺回顾功带困逃了出去“啊……救人啊顺困顶枯枵救命啊顺困顶枯枵校长顺困顶枯枵我们宿舍死人了……”', '\xa0\xa0\xa0\xa0这一叫顺困顶枯枵全校师生顺困顶枯枵可谓顶置中夺粗功地轰然间炸开了锅。', '\xa0\xa0\xa0\xa0经过多部门夺回顾功带困联合调查顺困

In [1]:
    import requests
    word = input('enter a word you want to search:')
    headers={
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36',
        }
    url = 'https://www.sogou.com/web'
    param = {
        'query':word,
    }
    response = requests.get(url=url,params=param,headers=headers)
    page_text = response.text
    fileName = word+'.html'
    with open(fileName,'w',encoding='utf-8') as fp:
        fp.write(page_text)

enter a word you want to search: 阿达


In [1]:
str="Runoob"
print(str)
print(str[0:-1])
print(str[0])
print(str[2:5])
print(str[2:])
print(str[1:5:2])
print(str*2)
print(str + "您好！")
print("========================")
print(str + "\nrunoob" )
print(r str + "\nrunoob")

SyntaxError: invalid syntax (<ipython-input-1-3b27c0a5c781>, line 12)

In [2]:
str="Runoob"
print(str)
print(str[0:-1])
print(str[0])
print(str[2:5])
print(str[2:])
print(str[1:5:2])
print(str*2)
print(str + "您好！")
print("========================")
print(str + "\nrunoob" )

print(r(str + "\nrunoob"))

Runoob
Runoo
R
noo
noob
uo
RunoobRunoob
Runoob您好！
Runoob
runoob


NameError: name 'r' is not defined

In [3]:
str="Runoob"
print(str)
print(str[0:-1])
print(str[0])
print(str[2:5])
print(str[2:])
print(str[1:5:2])
print(str*2)
print(str + "您好！")
print("========================")
print(str + "\nrunoob" )

# print()

Runoob
Runoo
R
noo
noob
uo
RunoobRunoob
Runoob您好！
Runoob
runoob


In [4]:
str="Runoob"
print(str)
print(str[0:-1])
print(str[0])
print(str[2:5])
print(str[2:])
print(str[1:5:2])
print(str*2)
print(str + "您好！")
print("========================")
print(str + "\nrunoob" )

print(rf"{str}\nrunoob")

Runoob
Runoo
R
noo
noob
uo
RunoobRunoob
Runoob您好！
Runoob
runoob
Runoob\nrunoob


In [5]:
str="Runoob"
print(str)
print(str[0:-1])
print(str[0])
print(str[2:5])
print(str[2:])
print(str[1:5:2])
print(str*2)
print(str + "您好！")
print("========================")
print(str + "\nrunoob" )

print(fr"{str}\nrunoob")

Runoob
Runoo
R
noo
noob
uo
RunoobRunoob
Runoob您好！
Runoob
runoob
Runoob\nrunoob


In [6]:
str="Runoob"
print(str)
print(str[0:-1])
print(str[0])
print(str[2:5])
print(str[2:])
print(str[1:5:2])
print(str*2)
print(str + "您好！")
print("========================")
print(str + "\nrunoob" )
print("================================")
print(r"\nrunoob")
print("\nrunoob")

Runoob
Runoo
R
noo
noob
uo
RunoobRunoob
Runoob您好！
Runoob
runoob
\nrunoob

runoob


In [7]:
class A:
    pass
class B(A):
    pass
isinstance(A(), A)
print(type(A()) == A)
isinstance(B(), A)
print(type(B()) == A)


True
False


In [8]:
info = {
    "name":"Python",
    "mission": "简单易用的编程语言",
    "website": "https://www.python.org"
}
for k in info:
    print(k,info[k])

name Python
mission 简单易用的编程语言
website https://www.python.org


In [11]:
import requests
from lxml import etree
if __name__ == "__main__":
    url = "https://www.37zw.net/0/330/"
    headers = {
        "User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0"
    }
    page_text = requests.get(url=url, headers=headers).text
#     page_text = page_text.encode("iso-8859-1").decode("gbk")
    HTML_etree = etree.HTML(page_text)
    title = HTML_etree.xpath('//div[@id="info"]/h1/text()')[0]
    author = HTML_etree.xpath('//div[@id="info"]/p[1]/text()')[0]
    title = title.encode('iso-8859-1').decode('gbk')
    author = author.encode('iso-8859-1').decode('gbk')
    print(title)
    print(author)
    f = open("D:/"+ title +".txt", "w")
    f.write(title)
    f.write(author)
    dd_list = HTML_etree.xpath('//div[@id="list"]//dd')
    for dd in dd_list:
        chapter_title = dd.xpath('./a/text()')[0]
        chapter_title = chapter_title.encode('iso-8859-1').decode('gbk')
        chapter_src = url + dd.xpath('./a/@href')[0]
        chapter_HTML = requests.get(url=chapter_src, headers=headers).text
        chapter_HTML = chapter_HTML.encode('iso-8859-1').decode('gbk')
#         print(chapter_HTML)
        chapter_etree = etree.HTML(chapter_HTML)
        chapter_content = chapter_etree.xpath('//div[@id="content"]//text()')
#         chapter_content = chapter_content.encode('iso-8859-1').decode('gbk')
        print(chapter_content)
        f.write(chapter_title + "\n")
        f.write(chapter_content + "\n")
        print(chapter_title + "下载完成！！！")
    print(title + "保存成功！！！")

大主宰
作牋牋者：天蚕土豆
['从现在开始，大主宰就要开始打榜了，特别是推荐票和收藏，一对一本新书很重要。所以，在这里请各位读者，不论是正版还是盗版，希望大家看完更新能够将推荐票投给大主宰。当然，不要忘记收藏哦，这也很重要的~~~~新书正式开始，欢迎大家。求推荐票和收藏啦~~~~~~~~~~~~;']


TypeError: can only concatenate list (not "str") to list

In [13]:
import requests
from lxml import etree
if __name__ == "__main__":
    url = "https://www.37zw.net/0/330/"
    headers = {
        "User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0"
    }
    request = requests.get(url=url, headers=headers)
    request.encoding = 'gbk'
    page_text = request.text
#     page_text = page_text.encode("iso-8859-1").decode("gbk")
    HTML_etree = etree.HTML(page_text)
    title = HTML_etree.xpath('//div[@id="info"]/h1/text()')[0]
    author = HTML_etree.xpath('//div[@id="info"]/p[1]/text()')[0]
    print(title)
    print(author)
    f = open("D:/"+ title +".txt", "w", encoding = 'gbk')
    f.write(title)
    f.write(author)
    dd_list = HTML_etree.xpath('//div[@id="list"]//dd')
    for dd in dd_list:
        chapter_title = dd.xpath('./a/text()')[0]
        chapter_title = chapter_title.encode('iso-8859-1').decode('gbk')
        chapter_src = url + dd.xpath('./a/@href')[0]
        chapter_HTML = requests.get(url=chapter_src, headers=headers).text
        chapter_HTML = chapter_HTML.encode('iso-8859-1').decode('gbk')
#         print(chapter_HTML)
        chapter_etree = etree.HTML(chapter_HTML)
        chapter_content = chapter_etree.xpath('//div[@id="content"]//text()')
#         chapter_content = chapter_content.encode('iso-8859-1').decode('gbk')
        print(chapter_content)
        f.write(chapter_title + "\n")
        f.write(chapter_content + "\n")
        print(chapter_title + "下载完成！！！")
    print(title + "保存成功！！！")

大主宰
作    者：天蚕土豆


UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 1: illegal multibyte sequence

In [14]:
import requests
from lxml import etree
if __name__ == "__main__":
    url = "https://www.37zw.net/0/330/"
    headers = {
        "User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0"
    }
    request = requests.get(url=url, headers=headers)
    request.encoding = 'gbk'
    page_text = request.text
#     page_text = page_text.encode("iso-8859-1").decode("gbk")
    HTML_etree = etree.HTML(page_text)
    title = HTML_etree.xpath('//div[@id="info"]/h1/text()')[0]
    author = HTML_etree.xpath('//div[@id="info"]/p[1]/text()')[0]
    print(title)
    print(author)
    f = open("D:/大主宰.txt", "w", encoding = 'gbk')
    f.write(title)
    f.write(author)
    dd_list = HTML_etree.xpath('//div[@id="list"]//dd')
    for dd in dd_list:
        chapter_title = dd.xpath('./a/text()')[0]
        chapter_title = chapter_title.encode('iso-8859-1').decode('gbk')
        chapter_src = url + dd.xpath('./a/@href')[0]
        chapter_HTML = requests.get(url=chapter_src, headers=headers).text
        chapter_HTML = chapter_HTML.encode('iso-8859-1').decode('gbk')
#         print(chapter_HTML)
        chapter_etree = etree.HTML(chapter_HTML)
        chapter_content = chapter_etree.xpath('//div[@id="content"]//text()')
#         chapter_content = chapter_content.encode('iso-8859-1').decode('gbk')
        print(chapter_content)
        f.write(chapter_title + "\n")
        f.write(chapter_content + "\n")
        print(chapter_title + "下载完成！！！")
    print(title + "保存成功！！！")

大主宰
作    者：天蚕土豆


UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 1: illegal multibyte sequence

In [16]:
import requests
from lxml import etree
if __name__ == "__main__":
    url = "https://www.37zw.net/0/330/"
    headers = {
        "User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0"
    }
    request = requests.get(url=url, headers=headers)
    request.encoding = 'gbk'
    page_text = request.text
#     page_text = page_text.encode("iso-8859-1").decode("gbk")
    HTML_etree = etree.HTML(page_text)
    title = HTML_etree.xpath('//div[@id="info"]/h1/text()')[0]
    author = HTML_etree.xpath('//div[@id="info"]/p[1]/text()')[0]
    print(title)
    print(author)
    f = open("D:/大主宰.txt", "w", encoding = 'gbk')
    f.write(title + '\n' + author)

    dd_list = HTML_etree.xpath('//div[@id="list"]//dd')
    for dd in dd_list:
        chapter_title = dd.xpath('./a/text()')[0]
        chapter_src = url + dd.xpath('./a/@href')[0]
        chapter_HTML = requests.get(url=chapter_src, headers=headers).text
#         print(chapter_HTML)
        chapter_etree = etree.HTML(chapter_HTML)
        chapter_content = chapter_etree.xpath('//div[@id="content"]//text()')
#         chapter_content = chapter_content.encode('iso-8859-1').decode('gbk')
        print(chapter_content)
        f.write(chapter_title + "\n")
        f.write(chapter_content + "\n")
        print(chapter_title + "下载完成！！！")
    print(title + "保存成功！！！")

大主宰
作    者：天蚕土豆


UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 6: illegal multibyte sequence

In [22]:
import requests
from lxml import etree
if __name__ == "__main__":
    url = "https://www.37zw.net/0/330/"
    headers = {
        "User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0"
    }
    request = requests.get(url=url, headers=headers)
#     request.encoding = 'gbk'
    page_text = request.text
    page_text = page_text.encode("iso-8859-1").decode("gbk")
    HTML_etree = etree.HTML(page_text)
    title = HTML_etree.xpath('//div[@id="info"]/h1/text()')[0]
    author = HTML_etree.xpath('//div[@id="info"]/p[1]/text()')[0]
    print(title)
    print(author)
    f = open("D:/大主宰.txt", "w")
    f.write(title + '\n' + author)

    dd_list = HTML_etree.xpath('//div[@id="list"]//dd')
    for dd in dd_list:
        chapter_title = dd.xpath('./a/text()')[0]
        chapter_src = url + dd.xpath('./a/@href')[0]
        chapter_HTML = requests.get(url=chapter_src, headers=headers).text
#         print(chapter_HTML)
        chapter_etree = etree.HTML(chapter_HTML)
        chapter_content = chapter_etree.xpath('//div[@id="content"]//text()')
#         chapter_content = chapter_content.encode('iso-8859-1').decode('gbk')
        print(chapter_content)
        f.write(chapter_title + "\n")
        f.write(chapter_content + "\n")
        print(chapter_title + "下载完成！！！")
    print(title + "保存成功！！！")

大主宰
作    者：天蚕土豆


UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 6: illegal multibyte sequence