In [1]:
import json

print(json.dumps({"name": "ccc", "age": 63}))
print(json.dumps(["apple"]))
print(json.dumps(("apple")))
print(json.dumps("hello"))
print(json.dumps(42))
print(json.dumps(31.76))
print(json.dumps(True))
print(json.dumps(False))
print(json.dumps(None))

{"name": "ccc", "age": 63}
["apple"]
"apple"
"hello"
42
31.76
true
false
null


当 Python 转换为 JSON 时，Python 对象会被转换为 JSON（JavaScript）等效项：

In [9]:
import json

x = {
  "name": "sss",
  "age": 3,
  "married": True,
  "divorced": False,
  "children": ("aaa","ccc","zzz"),
  "pets": None,
  "cars": [
    {"model": "bbb", "mpg": 38.2},
    {"model": "ssf", "mpg": 26.9}
  ]
}

print(json.dumps(x))
print(json.dumps(x, indent=4))

{"name": "sss", "age": 3, "married": true, "divorced": false, "children": ["aaa", "ccc", "zzz"], "pets": null, "cars": [{"model": "bbb", "mpg": 38.2}, {"model": "ssf", "mpg": 26.9}]}
{
    "name": "sss",
    "age": 3,
    "married": true,
    "divorced": false,
    "children": [
        "aaa",
        "ccc",
        "zzz"
    ],
    "pets": null,
    "cars": [
        {
            "model": "bbb",
            "mpg": 38.2
        },
        {
            "model": "ssf",
            "mpg": 26.9
        }
    ]
}



Try Except

In [12]:
try:
  print(zzz)
except:
  print("未知错误")

未知错误


In [13]:
try:
  print(y)
except NameError:
  print("y未定义")
except:
  print("未知错误")

y未定义


In [14]:
try:
  print(ggg)
except:
  print("未知错误")
finally:
  print("测试完成")

未知错误
测试完成


raise引发异常


In [20]:
x = -1

if x < 0:
  raise Exception("x不是正整数")
else:
    print(x)

Exception: x不是正整数

命令行输入

In [21]:
print("年龄:")
x = input()
print("Hello ", x)

年龄:


 3


Hello  3


字符串格式化

In [24]:
price = 52
txt = "The price is {} dollars"
print(txt.format(price))
txt1= "The price is {:.2f} dollars"
print(txt1.format(price))

The price is 52 dollars
The price is 52.00 dollars


In [28]:
shuliang = 3
shangpin = "袜子"
jiage = 52
myorder = "我要买{} 个{} 总共{:.2f} 元。"
print(myorder.format(shuliang, shangpin, jiage))

我要买3 个袜子 总共52.00 元。


In [31]:
age = 6
name = "qwe"
txt = "His name is {1}. {1} is {0} years old."
print(txt.format(age, name))

myorder = "I have a {carname}, it is a {model}."
print(myorder.format(carname = "Porsche", model = "911"))

His name is qwe. qwe is 6 years old.
I have a Porsche, it is a 911.


In [35]:
f = open("test.txt", "r",encoding="utf-8")

print(f.read())
f.close()

这是个测试文件
这是第二行
这是第三行
这是第四行



In [40]:
import numpy as np 

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [41]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim) 
print(b.ndim) 
print(c.ndim) 
print(d.ndim)

0
1
2
3


In [42]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])
print(arr[2] + arr[3])

2
7


In [44]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]


In [45]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [46]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [47]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [48]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 61

print(arr) 
print(x)

[61  2  3  4  5]
[1 2 3 4 5]


In [49]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 61

print(arr) 
print(x)

[61  2  3  4  5]
[61  2  3  4  5]


In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [51]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [52]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [53]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [54]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [55]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [56]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [57]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [58]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [59]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [60]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)
newarr1 = np.array_split(arr, 4)

print(newarr)
print(newarr1)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [61]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 3)

print(x)

(array([2], dtype=int64),)


In [62]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [65]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, 7)
x1 = np.searchsorted(arr, [2, 4, 6])

print(x)
print(x1)

3
[1 2 3]
