In [1]:
print('hello world')

hello world


In [2]:
a=1
b=2
a+b

3

In [3]:
x=3
print(x*3)

9


In [4]:
a=3
b=4
c=a*b
d=c/a
print(c,d)


12 4.0


In [5]:
import numpy as np
a=np.arange(1,10)
b=np.arange(0,9)
print(np.multiply(a,b))
print(np.dot(a,b))
print(a)
print(a.T)
print(np.sum([[0,1,2],[2,1,3]],axis=1))
print(np.sum([[0,1,2],[2,1,3]],axis=1,keepdims=True))


[ 0  2  6 12 20 30 42 56 72]
240
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[3 6]
[[3]
 [6]]


a=2
b=3
c=a>b
print(c)

In [6]:
a=np.arange(1,9).reshape(1,8)
b=np.arange(0,8).reshape(1,8)
print(a,type(a))
print(a[:,1])
# print(a.T)
# print(b)
# print(b.T)
# print(np.multiply(a,b.T))
# # np.sum(np.multiply(a.T,b))
# # print(np.multiply(a,b.T)-np.multiply(a.T,b))
# print(np.dot(a,b.T))
# print(np.sum(np.dot(a,b.T)))


[[1 2 3 4 5 6 7 8]] <class 'numpy.ndarray'>
[2]


In [7]:
a=np.arange(1,9).reshape(2,4)
b=np.arange(0,8).reshape(2,4)
print(a)
# print(np.multiply(a,b.T)-np.multiply(a.T,b))
# print(np.multiply(a,b.T)-np.multiply(a.T,b)-a)
# print(np.sum(np.multiply(a,b.T)-np.multiply(a.T,b)-a))
print(np.sum(a,axis=1))
print(np.sum(a,axis=1,keepdims=True))
c=np.sum(a,axis=1)
print(c,type(c))
print(c.T)  
d=[10,26]
print(type(d))

[[1 2 3 4]
 [5 6 7 8]]
[10 26]
[[10]
 [26]]
[10 26] <class 'numpy.ndarray'>
[10 26]
<class 'list'>


In [8]:
import numpy as np
a=np.array([[1,2,3],[3,4,5],[5,6,7]])
b=np.mat([1,2,3])
print(a,b,b.T,a.shape,len(a),type(a))
print(a.T)
m,n=a.shape
print(m,n)
print(a[1],a[1][2],a[0],a[:,1])
a[[0,1],:]=a[[2,0],:]
print(a)
print(np.linalg.matrix_rank(np.mat(a)))

[[1 2 3]
 [3 4 5]
 [5 6 7]] [[1 2 3]] [[1]
 [2]
 [3]] (3, 3) 3 <class 'numpy.ndarray'>
[[1 3 5]
 [2 4 6]
 [3 5 7]]
3 3
[3 4 5] 5 [1 2 3] [2 4 6]
[[5 6 7]
 [1 2 3]
 [5 6 7]]
2


In [9]:
a=('N'or'n')
b='n'
a==b

False

In [10]:
for i in range(0,9):
    print(i)

0
1
2
3
4
5
6
7
8


## Type()

In [11]:
a=10
b=10.0
c="hello world"
d=True
print(type(a),type(b),type(c),type(d))

<class 'int'> <class 'float'> <class 'str'> <class 'bool'>


In [12]:
e=()  #元组
f=[]  #列表
g={}  #字典
print(type(e))
print(type(f))
print(type(g))


<class 'tuple'>
<class 'list'>
<class 'dict'>


## 变量名区分大小写

In [13]:
d=1
D=2
print(d,D)

1 2


## 算术运算符 可以直接print

# + - * / %求余 **指数 //保留整数除法 

In [14]:
a=7
b=3
c=10
print(a+b*c)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)

37
4
21
2.3333333333333335
2
1
343


## 比较运算 可以print
==等于 !=不等 > >= < <= output Ture(1)orFalse(0)

In [15]:
a,b=10,5
print(a==b)
print(a>=b)
print(a<=b)
print(a!=b)

False
True
False
True


## 逻辑运算 优先级 () -> not -> and -> or 
and or not  

In [16]:
a,b,c,d=23,19,10,5
print(a+b>c and c<d)
print(a+b>c or c<d)
print(not a)
print(not a>b)
print(not a<b)

False
True
False
False
True


## 赋值运算符 不能直接print 
= ， += ，-= ， *= ， /= ， 从左往右

In [17]:
a,b,c=10,29,3
a+=c
b**=c
print(a+c)
print(a,b)


16
13 24389


## 占位符 %（多个） %单个。等效 {参数索引，不填默认顺序} 加上.format（）
%c 单个字符 %s字符串 %i %d有符号十进制 %u无符号十进制 %o八进制 %x十六进制 %e %E索引
%f 浮点实数 

In [18]:
name='周孟航'
number=3210101211
classpro='S0005'
print('我的名字是%s，学号是%d,来自%s'%(name,number,classpro)) #占位符
print('我的名字是{}，学号是{},来自{}'.format(name,number,classpro)) 
print('我的名字是{1}，学号是{0}，来自{2}'.format(number,name,classpro))
#format 不需要指定数据类型


我的名字是周孟航，学号是3210101211,来自S0005
我的名字是周孟航，学号是3210101211,来自S0005
我的名字是周孟航，学号是3210101211，来自S0005


## 输入input 都是str类型 转换类型 name=int(input())转整形

In [19]:
name=input("请输入你的姓名")
number=input("请输入你的学号")
classpro=input('请输入你的班级')
print('姓名：{}'.format(name))
print('学号：{}'.format(number))
print('班级：{}'.format(classpro))


请输入你的姓名 周孟航
请输入你的学号 3120101211
请输入你的班级 S0005


姓名：周孟航
学号：3120101211
班级：S0005


## 循环语句
选择流程                                             循环流程                                         
  1.单分支                                           while 条件表达式:                                                                        
     if 条件表达：                                      。。。。。。。                                           
        。。。。。。。                               for x ##设的参数  in 可迭代的集合对象: ## x依次赋值集合内的每一个值                                                       
  2.双分支                                           break ##退出当前的for或者while循环 continue 进行新的循环                                                               
     if 条件表达：                                   range() ## 生成数列                                                                      
        。。。。。。。                                                                                                          
     else：                                                                                                          
        。。。。。。。                                                                                                          
  3.多分支                                                                                                          
     if 条件表达：                                                                                                          
        。。。。。。。                                                                                                          
     elif 条件表达：                                                                                                          
        。。。。。。。                                                                                                          
     elif 条件表达：                                                                                                          
        。。。。。。。                                                                                                          
     。。。                                                                                                          
     else：                                                                                                          
条件表达式：比较运算（< > == !=）/逻辑运算符（not and or）/复合运算                                                                                                          

In [20]:
name=input("请输姓名")
number=input("请输入学号")
classpro=input('请输班级')
score=int(input('请输入分数'))
print('姓名：{}'.format(name))
print('学号：{}'.format(number))
print('班级：{}'.format(classpro))
if score<60:
    print('等级：不合格')
elif (score>=60) and (score<75):
    print('等级：合格')
elif (score>=75) and (score<85):
    print('等级：良好')
else:
    print('等级：优秀')
    


请输姓名 ZMH
请输入学号 3120101211
请输班级 5
请输入分数 100


姓名：ZMH
学号：3120101211
班级：5
等级：优秀


## 猜拳

In [21]:
import random #产生随机数的模块
person=int(input('请出拳：[石头：0，剪刀：1，布：2]'))
computer=random.randint(0,2)
#if person==0 and computer==1:
#    print('you win')
#elif person==1 and computer==2:
#    print('you win')
#elif person==2 and computer==0:
#    print('you win')
if person==0 and computer==1 or person==1 and computer==2 or person==2 and computer==0:
    print('you win')
elif person==computer:
    print('equal')
else:
    print('you lose')

请出拳：[石头：0，剪刀：1，布：2] 5


you lose


## 猜数字

In [22]:
number=8
guessnumber=-1
while guessnumber!=number:
    guessnumber=int(input('请输入数字'))
    if guessnumber>number:
        print('猜大了')
        continue
    elif guessnumber<number:
        print('猜小了')
        continue
    else:
        break
print('猜对了')

请输入数字 8


猜对了


In [23]:
row=1
while row<=9:
    col=1
    while col<=row:
        print('%d*%d=%d'%(row,col,row*col),end=' ')
        col+=1
    print( )
    row+=1
    

1*1=1 
2*1=2 2*2=4 
3*1=3 3*2=6 3*3=9 
4*1=4 4*2=8 4*3=12 4*4=16 
5*1=5 5*2=10 5*3=15 5*4=20 5*5=25 
6*1=6 6*2=12 6*3=18 6*4=24 6*5=30 6*6=36 
7*1=7 7*2=14 7*3=21 7*4=28 7*5=35 7*6=42 7*7=49 
8*1=8 8*2=16 8*3=24 8*4=32 8*5=40 8*6=48 8*7=56 8*8=64 
9*1=9 9*2=18 9*3=27 9*4=36 9*5=45 9*6=54 9*7=63 9*8=72 9*9=81 


In [24]:
row=9
while row>=1:
    col=1
    while col<=row:
        print('%d*%d=%d'%(col,row,row*col),end=' ')
        col+=1
    print()
    row-=1

1*9=9 2*9=18 3*9=27 4*9=36 5*9=45 6*9=54 7*9=63 8*9=72 9*9=81 
1*8=8 2*8=16 3*8=24 4*8=32 5*8=40 6*8=48 7*8=56 8*8=64 
1*7=7 2*7=14 3*7=21 4*7=28 5*7=35 6*7=42 7*7=49 
1*6=6 2*6=12 3*6=18 4*6=24 5*6=30 6*6=36 
1*5=5 2*5=10 3*5=15 4*5=20 5*5=25 
1*4=4 2*4=8 3*4=12 4*4=16 
1*3=3 2*3=6 3*3=9 
1*2=2 2*2=4 
1*1=1 


In [25]:
row=1
while row<=5:
    j=1
    while j<=5-row:
        print(' ',end='')
        j+=1
    k=1
    while k<=2*row-1:
        print('*',end='')
        k+=1
    row+=1
    print()

    *
   ***
  *****
 *******
*********


## 猜年龄
#### 退出循环 break 或者 使判断条件不成立
#### 多层嵌套循环时
#### 1while a:
####     2while b:
####          if :
####             break 退出2while 继续进行 1while循环
####          else:
####             改变a的条件
####             break       从而可以退出2while和1while 

In [26]:
target_age=int(input('请输入目标年龄：'))
i=0
while i<=2:
    guess_age=int(input('请输入猜测年龄'))
    if guess_age==target_age:
        print('真聪明！猜对了！')
        break
    else:
        
        if guess_age<target_age:
            print('不好意思，猜小了。')
            i+=1
        else:
            print('不好意思，猜大了。')
            i+=1
        while i==3:
            choice=input('是否愿意继续游戏，请输入Y/y or N/n:')
            if choice!='Y' and choice!='N' and choice!='y' and choice!='n':
                print('输入错误请重新输入')
                continue
            else:
                if choice=='Y' or choice=='y':
                    i=0
                    break
                elif choice=='N' or choice=='n':
                    print('游戏结束')
                    i=3
                    break
        continue
        



请输入目标年龄： 45
请输入猜测年龄 56


不好意思，猜大了。


请输入猜测年龄 49


不好意思，猜大了。


请输入猜测年龄 45


真聪明！猜对了！


## 字符串操作
#### 0 为左边第一个  -1 为右边第一个 + 向右 - 向左 id(a) 可以查看a的内存地址
#### 切片：截取字符串中的一部分内容 [起始下标:截至下标:步长][start:end:step]

### str.capitalize():str首字母变大写； .endswith/startswith(x):是否x结束/开始； .find(x):检查x是否在字符串中在哪，返回下标值，没有返回-1，约等于.index(),区别在找不到报错;str.strip():去除str中的空格 str.lstrip()左删除空格 str.rstrip()右；.lower()变小写；,upper()变大写；

In [27]:
test='pytho n '
test[0]
for i in test:
    print(i,end='')
a=test.capitalize()
print(a)
print(test.strip())
print(test.find('t'))
print(id(a))
print(test[0:-3],test[::-1],test[::],type(test),test.startswith('p'))

pytho n Pytho n 
pytho n
2
1761133465840
pytho  n ohtyp pytho n  <class 'str'> True


## list:支持增删改查，数据可以变化，内存地址不变，数据项可以是任何类型的数据，[]
### .append(一次只能添加一个数据或者列表) count extend(不能添加数字) index(位置，'数据') insert .pop(移除指定位置元素)类似于del list[]; remove(删除指定元素) reverse sort ;del list[::]删除下标元素或者范围元素；

In [28]:
li=[1,23,'hello',(1,3,2)]
print(type(li),len(li),li[0])
print(li.index(23),li[:3],li[::-1],3*li)
li.append('zmh')
li.append(12)
li.extend('eeeeee')
li.extend([ ])
print(li)
b=list(range(10))
print(b,type(b))
li.remove(1)
del b[0]
del b[2:4]
print(li,b)
print(b.index(7),len(b),b[3])


<class 'list'> 4 1
1 [1, 23, 'hello'] [(1, 3, 2), 'hello', 23, 1] [1, 23, 'hello', (1, 3, 2), 1, 23, 'hello', (1, 3, 2), 1, 23, 'hello', (1, 3, 2)]
[1, 23, 'hello', (1, 3, 2), 'zmh', 12, 'e', 'e', 'e', 'e', 'e', 'e']
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>
[23, 'hello', (1, 3, 2), 'zmh', 12, 'e', 'e', 'e', 'e', 'e', 'e'] [1, 2, 5, 6, 7, 8, 9]
4 7 6


## tuple元组（） 只有一个元素时 要加， 只能查找 不能修改！可以对元组中的list进行修改 tuple(A)强制转换A为tuple tuple.count(x)查找x出现的次数

In [29]:
tuple1=('asdf',123,[132,'hello','01'])
list1=[1,2,3]
tuple2=(123,23,list1)
print(tuple2)
list1[0]=2
tuple2=(123,23,list1)
print(list1,tuple2,type(tuple2))
print(tuple2.count(123))
tuple3=(1,)
tuple4=(1)
print(type(tuple3),type(4))
# print(tuple1)
print(tuple1[1:2],len(tuple1),tuple1[-1],tuple1[::-1])
# print(tuple1[0::2],tuple1[::-2])
# print(id(turple1))

(123, 23, [1, 2, 3])
[2, 2, 3] (123, 23, [2, 2, 3]) <class 'tuple'>
1
<class 'tuple'> <class 'int'>
(123,) 3 [132, 'hello', '01'] ([132, 'hello', '01'], 123, 'asdf')


## 字典dictionary dict[键]=键值 无序 无下标{键值集合} 内置的高级数据类型 键是不可变的类型[元组、字符串] 值可以是任意类型 键是唯一的 相同后面会覆盖前面 dict[]通过键可以得到键的值.keys()获取键 .values()获取值 .items()获取键值对
## for key,value in dict.items(): 逐条获取键值对  dict.update({'键':'键值}) 添加或更新键值对  sorted(dict.items(),key=lambda d:d[0/1])； del dict[键]=dict.pop(键)删除指定键 ；

In [30]:
dict1={'pro':'machanical','year':2020}
dict1['name']='zmh'
dict1['age']=22
dict1['class']=5
# print(len(dict1),dict1)
print(dict1['name'])
# dict1['name']='wzw'
# print(dict1['name'])
print(dict1)
for i in dict1:
    print(i)
for i in dict1.keys():
    print(i)
# print(dict1.keys(),dict1.values(),dict1.items())
# for key,value in dict1.items():
#     print('{}={}'.format(key,value))
# print(dict1)
# print(dict1.update({'pro':'mechanical'}))
print(sorted(dict1.items(),key=lambda d:d[0]))



zmh
{'pro': 'machanical', 'year': 2020, 'name': 'zmh', 'age': 22, 'class': 5}
pro
year
name
age
class
pro
year
name
age
class
[('age', 22), ('class', 5), ('name', 'zmh'), ('pro', 'machanical'), ('year', 2020)]


In [31]:
import sys
sys.executable

'D:\\acondana3\\envs\\pytorch10\\python.exe'

In [32]:
print(sys.argv) ##命令参数
for i in sys.argv:
    print(i)

['D:\\acondana3\\envs\\pytorch10\\lib\\site-packages\\ipykernel_launcher.py', '-f', 'C:\\Users\\saba\\AppData\\Roaming\\jupyter\\runtime\\kernel-23251e80-54f0-4e64-b4a9-714a28d9d230.json']
D:\acondana3\envs\pytorch10\lib\site-packages\ipykernel_launcher.py
-f
C:\Users\saba\AppData\Roaming\jupyter\runtime\kernel-23251e80-54f0-4e64-b4a9-714a28d9d230.json


## 可变关键字  
(*args) 函数传入元组数据 (**kwargs) 传入字典数据 

In [33]:
def num_sum(*args): ## *args 表示传一段元组数据给函数,只能是元组
    result=0
    print(*args,args,type(args))
    for item in args:
        result+=item
        pass
    return result
rs=num_sum(1.,12,45)
print(rs)
    

1.0 12 45 (1.0, 12, 45) <class 'tuple'>
58.0


In [34]:
def process_func(con):
    new_list=[]
    print(len(con),con[1],con)
    
    for i in range(len(con)):
        if i%2==0:
            new_list.append(con[i])
            pass
    return new_list
rs=process_func([12.,32.,4.,51.,56.,2.])
print(rs)
rs1=process_func(tuple(range(10,30)))
print(rs1)
print(type(range(10,12)))

6 32.0 [12.0, 32.0, 4.0, 51.0, 56.0, 2.0]
[12.0, 4.0, 56.0]
20 11 (10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29)
[10, 12, 14, 16, 18, 20, 22, 24, 26, 28]
<class 'range'>


In [35]:
def dict_func(**kwargs): #用**kwargs 读取传入的字典参数 key=values的形式 kwargs=dict
    list_new=[]
    print(kwargs,*kwargs,kwargs.keys(),kwargs.values())
    for i in kwargs.values():
        if len(i)>2:
            i=i[0:2]
            list_new.append(i)
        else:
            list_new.append(i)
    return list_new
rs=dict_func(name='zmh',Class='s0005',age='22',pro='mechanical')
print(rs)

{'name': 'zmh', 'Class': 's0005', 'age': '22', 'pro': 'mechanical'} name Class age pro dict_keys(['name', 'Class', 'age', 'pro']) dict_values(['zmh', 's0005', '22', 'mechanical'])
['zm', 's0', '22', 'me']


In [36]:
def dic_func1(dict): ## 用dict 读取 （）内 dict1的数据 dict=dict1
    list_new=[]
    print(dict,dict.keys(),dict.values())
    for i in dict.values():
        if len(i)>2:
            i=i[:2]
            list_new.append(i)
        else:
            list_new.append(i)
            pass
        pass
    return list_new
m=lambda dict:dic_func1(dict)  ## 可以用lambda 参数，参数：参数的运算结果 来表示匿名函数
dict1={'name': 'zmh', 'Class': 's0005', 'age': '22', 'pro': 'mechanical'}
rs=m(dict1)
print(rs)        

{'name': 'zmh', 'Class': 's0005', 'age': '22', 'pro': 'mechanical'} dict_keys(['name', 'Class', 'age', 'pro']) dict_values(['zmh', 's0005', '22', 'mechanical'])
['zm', 's0', '22', 'me']


## Guassian elimination

In [37]:
import numpy as np
def swap(A,b,m,n,E,k,count): ##做列主元交换
    max_k=0
    for i in range(k,m):    ##找出列最大主元
        if max_k<=abs(A[i][k]):
            max_k=abs(A[i][k])
            max_num=i
    count+=1
    A[[k,max_num],:]=A[[max_num,k],:]##交换
    b[k],b[max_num]=b[max_num],b[k]
    E[[k,max_num],:]=E[[max_num,k],:]
    
def gaussian(A,b,m,n,E,X):
    count=0
    c=np.c_[A,b]
    if np.linalg.matrix_rank(A)==np.linalg.matrix_rank(c) and np.linalg.matrix_rank(A)==n:##判断有唯一解
        for k in range(n): ##按列消元
            swap(A,b,m,n,E,k,count)               
            for i in range(k+1,m):##每列的消元过程
                if A[i][k]!=0:    ## 如果元素为0，则不需要消元
                    count+=1
                    num_1=A[i][k]/A[k][k]
                    A[i]-=num_1*A[k]
                    b[i]-=num_1*b[k]
                    E[i]-=num_1*E[k]
                else:
                    continue
        print('将矩阵进行LU分解，L={},U={}'.format(E,A))   ##输出上三角矩阵 LU分解 L=E,U=A

        for j in range(0,m):##主对角线变为1
            count+=1
            num_2=A[j][j]
            A[j]/=num_2
            b[j]/=num_2
            E[j]/=num_2
#         print(np.c_[A,b])
#         print(E)
        while k>=1:
            for z in range(0,k):##输出单位阵 
                count+=1
                num_3=A[z][k]
                A[z]-=num_3*A[k]
                b[z]-=num_3*b[k]
                E[z]-=num_3*E[k]
            k-=1
#         back(A,b,k)
        print('化为单位阵{},行变换矩阵为{}'.format(np.c_[A,b],E))
        print('此方程的解X={}'.format(b))
        print('计算次数为%d'%(count))
            
    elif np.linalg.matrix_rank(A)==np.linalg.matrix_rank(c) and np.linalg.matrix_rank(A)<n:
        print('此方程有无数个解')
    else:
        print('此方程无解')
        
A=np.array([[1,2,0,],[0,1,2],[1,2,1]])    #  A=np.array([[1.,2.,0.,],[0.,1.,2.],[1.,2.,1.]])##注意不同类型的数据不能进行运算 float和int A.astype(int/float) 可以改变array/matrix/mat的数据类型
A=A.astype(np.float)  ## 把A的数据转换为浮点型
b = np.mat([1.,2.,3.]).T
m,n=A.shape
E=np.eye(m)
X=np.zeros(shape=(m,1))
print(E,A)
# E=np.eye(n)
gaussian(A,b,m,n,E,X)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [[1. 2. 0.]
 [0. 1. 2.]
 [1. 2. 1.]]
将矩阵进行LU分解，L=[[ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 1.  0. -1.]],U=[[ 1.  2.  1.]
 [ 0.  1.  2.]
 [ 0.  0. -1.]]
化为单位阵[[ 1.  0.  0. -1.]
 [ 0.  1.  0.  2.]
 [-0. -0.  1. -0.]],行变换矩阵为[[-3. -2.  4.]
 [ 2.  1. -2.]
 [-1. -0.  1.]]
此方程的解X=[[-1.]
 [ 2.]
 [-0.]]
计算次数为7


In [38]:
import numpy as np
m=6
a=np.zeros(shape=(m,1))
a=a.astype(np.str)
for i in range(m):
    a[i]='x'
print(a)


[['x']
 ['x']
 ['x']
 ['x']
 ['x']
 ['x']]


In [39]:
for i in range(5):
    print(i)

0
1
2
3
4


In [40]:
#coding=utf-8 ## 测试tensorflow2.0是否安装成功


import tensorflow as tf
tf.compat.v1.disable_eager_execution()

import numpy as np

hello=tf.constant('hello,tf')

sess=tf.compat.v1.Session()

print (sess.run(hello))

ModuleNotFoundError: No module named 'tensorflow'

 ## 判断 匿名函数 m=lambda x,y,z:参数运算输出  定义+调用 m=(lambda x,y,z:输出)（a，b，c）abc为输入参数

In [41]:
age=19
print('可以参军了' if age>=18 else '未成年不可以参军 ')
functest=lambda x,y:x if x>=y else y ##取较大值
print(functest(19,18))
m=(lambda x,y:x if x>=y else y)(19,18)
print(m)

可以参军了
19
19


## 递归函数 调用自身函数 必须要有一个结束标志 求阶乘 迭代 树形结构的遍历
## 容易内存栈溢出


In [42]:
m=1
for i in range(1,10):
    m*=i
print(m)

362880


## 阶乘

In [44]:
def factorial(n):
    if n==1:
        return 1
    else:
        return n*factorial(n-1)
    pass
B=int(input())
a=factorial(B)
print(a)

 5


120


In [45]:
## 树形结构遍历
import os ##引入文件操作模块
def findfile(file_path):
    listrs=os.listdir(file_path)  ##得到file_path路径下的所有文件/夹 
    for fileitem in listrs:
        full_path=os.path.join(file_path,fileitem) # 遍历获取 file_path路径下的所有文件文件夹的完整路径
        if os.path.isdir(full_path): ## 判断得到的full_path是不是dir文件夹
            findfile(full_path)
            pass
        else:
            print(fileitem)
            pass
        pass
findfile('C:\\Users\\saba\\Desktop\\deeplearning_papers')

attention-guided CNN.pdf
batch renomalization CNN.pdf
coarse-to-findCNN.pdf
Deep Learning onImage Denoising An Overview.pdf
deeplearning_papers.zip
enhancedCNN.pdf
LISRCNN.pdf
Multi-object evolutionary design og deep convolutional neural networks for image classification.pdf
surrogate-assisted evolutionary deep learning ysing an end-to-end random forest-based performance predict.pdf


## 错误处理 Exception 可以捕获所有异常类型 import builtins ;dir(builtins)所有错误类型 

In [ ]:
try:
        ## 可能出现的代码块
except:
    ##出错后执行的代码块
else:
    ## 没有出错的代码块
finally:
    ## 不管有无错误都执行的代码块

In [ ]:
try:  ## catch different type error code
    list1=[1,23,45,2]
    print(list1[10])
    print(b)##catch code that may go worng
    print(1/0)
    pass
# except IndexError as msg:
#     print(msg)
#     pass
# except NameError as msg:  ##possible error
#     #process error code
#     print(msg)
#     pass
except Exception as result:
#     print(result)

print(1+2)

In [ ]:
import Exceptions
print(dir(Exceptions))

In [ ]:
a=(1,23,4)
print(type(a))
a=list(a)
print(type(a))
a=tuple(a)
print(type(a))
a=str(a)
print(type(a))

## I/O操作 文件操作 默认编码gbk 中文编码 mode-'w' 每次写入会覆盖原文件 'a'追加数据 'w''a'写入时 是str类型 'wb''ab'写入时是bytes 需要加.encode("utf-8")

In [ ]:
a=open('sample1.txt','a')  ##打开文件 mode w
a.write('i write somthing\n')
a.write('i')
a.close()

## 读取 f.read(n)读n个字符 f.readlines(m)逐行读取读前m行 f.readline()读一行

In [ ]:
f=open('sample1.txt','rb')
#print(f.read()) ##光标移动到末尾
# print(f.read(12)) ## 光标以后读12个字符
# print(f.readlines(2))
# print(f.readlines(1))
data=f.read()
print(data)
print(data.decode('gbk'))  ##带b的时候都要编码或者解码读出 写str.encode('utf-8')编码为bytes写入 读用gbk将bytes解码读出
f.close()

## 用with自动关闭对象  with open('file','mode',encoding='utf-8')  as f: ##f为变量名

In [ ]:
with open('sample1.txt','w',encoding='gb18030',errors='ignore') as f:
    data=f.read()
    print(data)

## matplotlib

In [ ]:
import matplotlib.pyplot as plt 
import numpy as np
X=np.linspace(-np.pi,np.pi,256,endpoint=True) ##X为一个数组 np.linspace(start,stop,等间隔取点数，endpoint=Ture##取最后一个点默认Ture,retstep=Ture#输出步长)
C,S=np.cos(X),np.sin(X)
plt.plot(X,C)
plt.plot(X,S)