In [6]:
# Python基础知识小练习
# 用python输出9*9乘法口诀表
for i in range(1,10):
    for j in range(1,i+1):
        print("%d*%d=%d\t" %(i, j, i*j),end=' ')
    print(' ')

# python中面向对象编程
# 面向对象的继承
class person:
    def __init__(self,name):
        print("person类构造方法被调用！")
        self.name=name
class student(person):
    def __init__(self,sno,name):
        print("student类构造方法被调用！")
        super().__init__(name)
        self.sno=sno
class postgraduate(student):
    def __init__(self,sno,name,tutor):
        print("postgraduate类构造方法被调用！")
        super().__init__(sno,name)
        self.tutor=tutor
if __name__=='__main__':
    pg=postgraduate("00201010","小明","XXX")
    print("该生的学号是%s,姓名是%s,指导教师是%s"%(pg.sno,pg.name,pg.tutor))



1*1=1	  
2*1=2	 2*2=4	  
3*1=3	 3*2=6	 3*3=9	  
4*1=4	 4*2=8	 4*3=12	 4*4=16	  
5*1=5	 5*2=10	 5*3=15	 5*4=20	 5*5=25	  
6*1=6	 6*2=12	 6*3=18	 6*4=24	 6*5=30	 6*6=36	  
7*1=7	 7*2=14	 7*3=21	 7*4=28	 7*5=35	 7*6=42	 7*7=49	  
8*1=8	 8*2=16	 8*3=24	 8*4=32	 8*5=40	 8*6=48	 8*7=56	 8*8=64	  
9*1=9	 9*2=18	 9*3=27	 9*4=36	 9*5=45	 9*6=54	 9*7=63	 9*8=72	 9*9=81	  
postgraduate类构造方法被调用！
student类构造方法被调用！
person类构造方法被调用！
该生的学号是00201010,姓名是小明,指导教师是XXX


In [10]:
#python中循环的用法

n = eval(input("please input a number(n>=2):"))

sum1 = 0
sum2 = 0

for i in range(5,2*n,4):
    sum1+=1/i
for j in range(3,2*n,4):
    sum2-=1/j

sum =1+ sum1+sum2
print("%.2F" %sum)




please input a number(n>=2):5
0.83


In [15]:
#用python实现基于Givens、Householder的QR分解

import numpy as np

def givens_rotation(A):          #创建函数
    """Givens变换"""
    (m, n) = np.shape(A)
    Q = np.identity(m)       #获得单位矩阵
    R = np.copy(A)
    (rows, cols) = np.tril_indices(m, -1, n)     
    for (row, col) in zip(rows, cols):
        if R[row, col] != 0:  # R[row, col]=0则c=1,s=0,R、Q不变
            m_ = np.hypot(R[col, col], R[row, col])  # d
            n = R[col, col]/m_
            s = -R[row, col]/m_
            G = np.identity(m)
            G[[col, row], [col, row]] = n
            G[row, col] = s
            G[col, row] = -s
            R = np.dot(G, R)  # R=G(n-1,n)*...*G(2n)*...*G(23,1n)*...*G(12)*A
            Q = np.dot(Q, G.T)  # Q=G(n-1,n).T*...*G(2n).T*...*G(23,1n).T*...*G(12).T
    return (Q, R)

def householder_reflection(A):
    """Householder变换"""
    (r, c) = np.shape(A)
    Q = np.identity(r)
    R = np.copy(A)
    for cnt in range(r - 1):
        x = R[cnt:, cnt]
        e = np.zeros_like(x)
        e[0] = np.linalg.norm(x)
        u = x - e
        v = u / np.linalg.norm(u)
        Q_cnt = np.identity(r)
        Q_cnt[cnt:, cnt:] -= 2.0 * np.outer(v, v)
        R = np.dot(Q_cnt, R)  # R=H(n-1)*...*H(2)*H(1)*A
        Q = np.dot(Q, Q_cnt)  # Q=H(n-1)*...*H(2)*H(1)  H为自逆矩阵
    return (Q, R)

np.set_printoptions(precision=3, suppress=True)
A = np.array([[3,5,5],[0,3,4],[4,0,5]],dtype=float)

(Q, R) = givens_rotation(A)
print('Q=',Q,'\n')
print('R=',R,'\n')
print('A=',np.dot(Q,R),'\n')

(Q, R) = householder_reflection(A)
print('Q=',Q,'\n')
print('R=',R,'\n')
print('A=',np.dot(Q,R),'\n')


Q= [[ 0.6   0.64 -0.48]
 [ 0.    0.6   0.8 ]
 [ 0.8  -0.48  0.36]] 

R= [[ 5.   3.   7. ]
 [ 0.   5.   3.2]
 [-0.   0.   2.6]] 

A= [[ 3.  5.  5.]
 [-0.  3.  4.]
 [ 4.  0.  5.]] 

Q= [[ 0.6   0.64 -0.48]
 [ 0.    0.6   0.8 ]
 [ 0.8  -0.48  0.36]] 

R= [[ 5.   3.   7. ]
 [ 0.   5.   3.2]
 [-0.  -0.   2.6]] 

A= [[ 3.  5.  5.]
 [-0.  3.  4.]
 [ 4.  0.  5.]] 



In [16]:
import math
doc = open("龙贝格积分法的输出结果.txt",'w+')

def func1(x):
     return 1 / (1+x)

def func2(x):
    return (math.log(1+x)) / (1+x**2)

def func3(x):
    if x != 0:
        fx3 = (math.log(1 + x)) / x
    else:
        fx3 = 1/(1+x)
    return fx3

def func4(x):
    if x == 0:
        fx4 = math.cos(x)
    else:
        a = (math.pi)/2
        fx4 = (math.sin(a*x))/(a*x)
    return fx4

def Romberg(a,b,n):
    for t in [func1,func2,func3,func4]:
        T_list = []
        S_list = []
        C_list = []
        R_list = []
        y = (t(a) +t(b))/2
        T = (b-a)*y
        T_list.append(T)
        for i in range(1, n):
            s = 0
            for j in range(1, 2**(i-1)+1):
                r = t(a + (2*j-1)*(b-a) / 2**i)
                s += r
            T = T_list[i-1]/2 + ((b-a)*s) / (2**i)
            T_list.append(T)
        for i in range(1,n-1):
            S = T_list[i] + (T_list[i] - T_list[i-1]) / (4**1 - 1)
            S_list.append(S)
        for i in range(1,n-2):
            C = S_list[i] + (S_list[i] - S_list[i-1]) / (4**2 - 1)
            C_list.append(C)
        R = C_list[n-4] + (C_list[n-4] - C_list[n-5]) / (4 ** 3 - 1)
        print("函数的积分结果为：%.7f" % R)
        print("函数的积分结果为：%.7f" % R,file = doc)
        #  上面是直接输出最终的结果，下面可以输出k=0，1，2，，，的R值
        for i in range(1, n-3):
            R = C_list[i] + (C_list[i] - C_list[i-1]) / (4**3 - 1)
            R_list.append(R)
        print("k=0,1,2,,,时的各个值为：" , R_list)
        print("k=0,1,2,,,时的各个值为：", R_list,file = doc)

if __name__ == '__main__':
    # a = 0，b = 1，n = 8
    Romberg(0,1,8)
    doc.close()

函数的积分结果为：0.6931472
k=0,1,2,,,时的各个值为： [0.6931474776448322, 0.6931471830719328, 0.6931471805734178, 0.6931471805600036]
函数的积分结果为：0.2721983
k=0,1,2,,,时的各个值为： [0.2721967191703742, 0.27219826583515017, 0.2721982613008791, 0.2721982612879932]
函数的积分结果为：0.8224670
k=0,1,2,,,时的各个值为： [0.8224670779105941, 0.8224670337626349, 0.8224670334258359, 0.8224670334241205]
函数的积分结果为：0.8726543
k=0,1,2,,,时的各个值为： [0.8726543000808641, 0.8726542994629038, 0.8726542994606117, 0.8726542994606028]


In [19]:
#用python编写一个简单的爬虫

import requests
from bs4 import BeautifulSoup

link = "https://so.gushiwen.org/mingju/juv_2d8bb03f1e19.aspx"
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'
           'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36'}

r = requests.get(link, headers = headers)

soup = BeautifulSoup(r.text,"lxml")
content = soup.find("div",class_="contson", id="contson4a96c8287eb5").span.text.strip()
print(content)


#爬取豆瓣评分TOP250电影名称
import requests
from bs4 import BeautifulSoup

doc = open("豆瓣TOP250电影.txt","w+")    #创建一个文件，后期将输出结果写入文件

def get_movies():
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36',
               'Host': 'movie.douban.com'
               }     #打开浏览器的检查功能（F12）,获取requests headers,伪装成浏览器访问
    movie_list = []
    for i in range (10):
        link = 'https://movie.douban.com/top250?start=' +str(i*25)
        r = requests.get(link,headers=headers,timeout = 20)
        print(str(i+1),"页码响应状态：", r.status_code)
        soup = BeautifulSoup(r.text, "lxml")
        div_list = soup.find_all('div', class_='hd')
        for each in div_list:
            movie = each.a.span.text.strip()
            movie_list.append(movie)
    return movie_list

if __name__ == '__main__':
    movies = get_movies()
    print(movies)
    print(movies, file=doc)

    doc.close()

山有木兮木有枝，心悦君兮君不知。
1 页码响应状态： 200
2 页码响应状态： 200
3 页码响应状态： 200
4 页码响应状态： 200
5 页码响应状态： 200
6 页码响应状态： 200
7 页码响应状态： 200
8 页码响应状态： 200
9 页码响应状态： 200
10 页码响应状态： 200
['肖申克的救赎', '霸王别姬', '阿甘正传', '这个杀手不太冷', '泰坦尼克号', '美丽人生', '千与千寻', '辛德勒的名单', '盗梦空间', '忠犬八公的故事', '星际穿越', '海上钢琴师', '楚门的世界', '三傻大闹宝莱坞', '机器人总动员', '放牛班的春天', '大话西游之大圣娶亲', '熔炉', '疯狂动物城', '无间道', '教父', '龙猫', '当幸福来敲门', '怦然心动', '触不可及', '控方证人', '蝙蝠侠：黑暗骑士', '活着', '末代皇帝', '寻梦环游记', '乱世佳人', '何以为家', '指环王3：王者无敌', '摔跤吧！爸爸', '飞屋环游记', '少年派的奇幻漂流', '哈利·波特与魔法石', '素媛', '十二怒汉', '哈尔的移动城堡', '鬼子来了', '天空之城', '大话西游之月光宝盒', '我不是药神', '闻香识女人', '罗马假日', '天堂电影院', '辩护人', '搏击俱乐部', '猫鼠游戏', '大闹天宫', '教父2', '狮子王', '指环王2：双塔奇兵', '死亡诗社', '钢琴家', '黑客帝国', '指环王1：魔戒再现', '窃听风暴', '饮食男女', '美丽心灵', '两杆大烟枪', '让子弹飞', '绿皮书', '本杰明·巴顿奇事', '飞越疯人院', '看不见的客人', '海蒂和爷爷', '西西里的美丽传说', '拯救大兵瑞恩', '小鞋子', '穿条纹睡衣的男孩', '情书', '音乐之声', '海豚湾', '美国往事', '致命魔术', '沉默的羔羊', '低俗小说', '禁闭岛', '蝴蝶效应', '七宗罪', '心灵捕手', '布达佩斯大饭店', '春光乍泄', '被嫌弃的松子的一生', '摩登时代', '阿凡达', '哈利·波特与死亡圣器(下)', '喜剧之王', '剪刀手爱德华', '致命ID', '勇敢的心', '加勒比海盗', 

In [20]:
# 异常处理
import sys
def fibonacci(n):
    a,b,counter = 0,1,0
    while True:
        if counter>n:
            return
        yield a
        a,b = b,a+b
        counter += 1
f = fibonacci(10)

while True:
    try:
        print (next(f), end=" ")
    except StopIteration:
        sys.exit()

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



0 1 1 2 3 5 8 13 21 34 55 Traceback (most recent call last):
  File "<ipython-input-20-09ddd0a0c3c1>", line 15, in <module>
    print (next(f), end=" ")
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-09ddd0a0c3c1>", line 17, in <module>
    sys.exit()
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\lib\site-packages\IPython\core\ultratb.py", line 1170, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "D:\python\lib\site-packages\IPython\core\ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "D:\python\lib\site-packages\IPython\core\ultratb.py", line 350, in _fixed_getinnerframes
    records

TypeError: object of type 'NoneType' has no len()