In [12]:
name='abcdef'
name[2:5]

'cde'

In [14]:
# passing values

# CTRL + Enter = Run

a = 10
b = 11
c = "Hello"



In [15]:

# To Print
print(a)
print(b)
c

10
11


'Hello'

In [16]:

# Packages / libraries

import os #provides functions for interacting with the operating system
import numpy as np

# pip install numpy - in the terminal

In [18]:
# Creating an array
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [20]:

# checking the type of a
type(a)

numpy.ndarray

In [21]:
# checking the number of elements per dimension
a.shape

(4,)

In [23]:
# Selecting / indexing elements from the array
a[0]
a[-1]
a[3]
a[0]
a[-1]
a[3]

4

In [24]:
# Indexing elements that don't exist (out of bounds)
a[4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [25]:
# Creating error check to avoid stoping the script
try:
    a[4]
except IndexError as e:
    print(e)

index 4 is out of bounds for axis 0 with size 4


In [26]:

# changing the elements of the array

a[0] = 300
a

array([300,   2,   3,   4])

In [27]:
# creating a 2 D array

a = np.array([[1,2,3], [1,2,3]])
a
#a.shape

array([[1, 2, 3],
       [1, 2, 3]])

In [28]:

# creating a 3x3 Matrix
a = np.array([[1,2,3], [1,2,3], [1,2,3]])
a
#a.shape

# To flatten the matrix 
b = np.hstack(a)

print(a)
b

[[1 2 3]
 [1 2 3]
 [1 2 3]]


array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [31]:
# 2x2 with zero values

np.zeros((5,2))
np.zeros((5,11))
np.zeros((5012,12))
np.zeros((125,22))
np.zeros((531,115))
np.zeros((51250,23))
np.zeros((355,62))
np.zeros((25,131))
np.zeros((550,32))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [35]:
# NxN with 1 values

a = np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
a.shape

(5, 5)

In [39]:

# generate random numbers

a = np.random.random((5,5))*1000
a

array([[828.34854462, 706.18797055, 358.39806559,  62.99112411,
        736.62125094],
       [970.67592491, 889.59631131, 456.17260711, 259.07083908,
        502.84043792],
       [242.95489612, 492.02391774, 344.71453475, 430.69080975,
        715.26346061],
       [839.34818739,  41.14772885, 521.1249305 , 131.28601457,
        620.5031429 ],
       [ 96.17034151, 825.83120472, 287.85002176,  90.70692565,
        462.63852926]])

In [41]:
a.shape

(5, 5)

In [42]:

a_list = [1,2,3,4]
a_list

[1, 2, 3, 4]

In [43]:

#a_list.shape
# b_list.shape # will give us an error

a = np.array(a_list)

#shape
a.shape
a

#specifying the type
a = np.array(a_list, dtype = float)
a

array([1., 2., 3., 4.])

In [44]:
# Appending an array

a = np.array([])

for i in range(100):
    a = np.append(a,i)

a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [45]:
a = np.random.random((3,5)) * 100
a = a.round()
a

array([[41., 47., 76., 51., 77.],
       [36.,  8., 63., 32., 73.],
       [35., 70., 23., 35., 50.]])

In [46]:

# middle 2x2 matrix
a[1:3,2:4]

# middle 3x3 matrix
a[0:3, 0:3]

array([[41., 47., 76.],
       [36.,  8., 63.],
       [35., 70., 23.]])

In [47]:
# Integer # Numpy choose the datatype

a = np.array([1,2,3])
a.dtype

dtype('int32')

In [48]:
# Float  # Numpy choose the datatype
a = np.array([1.,2.,3.])
a.dtype

dtype('float64')

In [49]:
# Specify a datatype
a = np.array([1,2,3], dtype = 'float')
a.dtype

dtype('float64')

In [50]:

# creating the arrays
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,11,12])

In [52]:

# SUM

a + b
np.add(a,b)

array([ 8, 10, 12, 14, 16, 18])

In [53]:

# Minus

a - b
np.subtract(a,b)

array([-6, -6, -6, -6, -6, -6])

In [54]:
# Division

a/b
np.divide(a,b)

array([0.14285714, 0.25      , 0.33333333, 0.4       , 0.45454545,
       0.5       ])

In [55]:
# Square root

np.sqrt(b)

array([2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
       3.46410162])

In [56]:

# Dot product and Matrix Maths
# Note: when we multiply in Numpy, we use elementwise multiplication, not matrix multiplication like MATLAP

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([2, 3])
d = np.array([4, 5])

In [57]:
# Inner product of vectors

c.dot(d)
np.dot(c,d)

# NumPy - elementwise multiplication
# (2*4) + (3*5)
# 8 + 15 = 23

23

In [59]:
#  Matrix vector product

a.dot(c)
np.dot(a,c)

# NumPy Elementwise
# ((1*2) + (2*3)) , ((3*2) + (4*3))
# (2 + 6) , (6 + 12)
# 8, 18

array([ 8, 18])

In [60]:
a


array([[1, 2],
       [3, 4]])

In [61]:
b

array([[5, 6],
       [7, 8]])

In [63]:
# :
# Matrix by matrix product


a.dot(b)
np.dot(a,b)

# NumPy Elementwise
# (1*5) + (2*7), (1*6) + (2*8)
# (3*5) + (4*7), (3*6) + (4*8)

# 5+14, 6+16
# 15+28, 18+32

# 19, 22
# 43, 50

array([[19, 22],
       [43, 50]])

In [64]:
a = np.array([[1,2], [3,4], [5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
# Sum of all elements

np.sum(a)

21

In [66]:
# sums the values by column
np.sum(a, axis=0)

array([ 9, 12])

In [68]:
# sums the values by row
np.sum(a, axis=1)

array([ 3,  7, 11])

In [69]:

a.shape


(3, 2)

In [70]:
# reshaping
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
# flattens
np.hstack(a)

array([1, 2, 3, 4, 5, 6])

In [72]:

#generate new array and reshape

a = np.arange(10).reshape((2,5))

a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [73]:
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [74]:
# One way of Transp
a.T

# ANother way
np.transpose(a)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [75]:
a = np.arange(15).reshape((5,3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [76]:
b = np.array([5,2,1])
b

array([5, 2, 1])

In [77]:
a * b

array([[ 0,  2,  2],
       [15,  8,  5],
       [30, 14,  8],
       [45, 20, 11],
       [60, 26, 14]])

In [79]:

a + b

array([[ 5,  3,  3],
       [ 8,  6,  6],
       [11,  9,  9],
       [14, 12, 12],
       [17, 15, 15]])

In [80]:
a/100*2

array([[0.  , 0.02, 0.04],
       [0.06, 0.08, 0.1 ],
       [0.12, 0.14, 0.16],
       [0.18, 0.2 , 0.22],
       [0.24, 0.26, 0.28]])

In [81]:
# Creating a Series by passing in a list without the Index
s = pd.Series(['28', '1.79', 'Yiannis'])
s


0         28
1       1.79
2    Yiannis
dtype: object

In [82]:
# Creating a Series by passing in a list & the Indexs
s = pd.Series(['28', '1.79 cm', 'Yiannis'], index=['Age', 'Height', "Name"])
s

Age            28
Height    1.79 cm
Name      Yiannis
dtype: object

In [83]:
# Indexing / filtering the Series
s['Name']

'Yiannis'

In [84]:
# Manually

df = pd.DataFrame(columns = ["Name", 'Gender','Age','Height'])
df

Empty DataFrame
Columns: [Name, Gender, Age, Height]
Index: []

In [85]:

# Passing Values in the DataFrame
df.loc[0] = ["Joe", "Male", 23, 1.70]
df.loc[1] = ["Tom", "Male", '50', 1.80]
df.loc[2] = ["Tine", "Female", 93, 1.79]
df

Name  Gender Age  Height
0   Joe    Male  23    1.70
1   Tom    Male  50    1.80
2  Tine  Female  93    1.79

In [86]:

# Creating DataFrame from a List
a_list = [["Joe", "Male", 23, 1.70], ["Tom", "Male", '50', 1.80]]
a_list

df = pd.DataFrame(a_list, columns = ["Name", 'Gender','Age','Height'])
df

Name Gender Age  Height
0  Joe   Male  23     1.7
1  Tom   Male  50     1.8

In [87]:
# Creating DataFrame from an Array
a = np.arange(15).reshape(5,3)
print(a)

df = pd.DataFrame(a, columns = ["A", 'B','C'])
df

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


A   B   C
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

In [88]:
# Transpose a DataFrame

#method 1
df.T

# method 2
np.transpose(df)

0  1  2   3   4
A  0  3  6   9  12
B  1  4  7  10  13
C  2  5  8  11  14

In [89]:
# This is to find out your current directory
cwd = os.getcwd()
cwd

'E:\\onedrive\\code\\python作业'

In [92]:
# Python 3: Fibonacci series up to n
def fib(n):
    a, b = 0, 1
    while (a < n):
         print(a, end=' ')
         a, b = b, a+b
    print()
fib(1000)

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 
